import type { CopyKey } from './en';

// DE (Almanya) karşılıklar. Hitap her yerde "du" — Alman tüketici app'lerinde standart; "Sie" ile karıştırılmadı.
export const deDE: Record<CopyKey, string> = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: 'PARKEN',
  onbBody1: 'Ein Tipp markiert, wo dein Auto steht. Etage, Foto und Notiz sind optional — nur wenn das Parkhaus unübersichtlich ist.',
  onbTitle2: 'GELD SPAREN',
  onbBody2: 'Tarif einmal eintragen, ParkIQ zählt bis zur nächsten Preisstufe herunter. Fährst du vorher raus, bleibt die Differenz bei dir.',
  onbTitle3: 'WIEDERFINDEN',
  onbBody3: 'Kompass und Karte führen dich zurück. Im Untergeschoss, wo GPS aufgibt, übernehmen dein Foto und die Etage.',
  skip: 'Überspringen',
  enableLocation: 'Weiter',
  notNow: 'Nicht jetzt',
  iParked: 'Geparkt',
  foundIt: 'Gefunden',
  arMode: 'Kameraansicht',
  arHint: 'Folge dem Strahl',
  arInitializing: 'Bewege das Handy langsam, damit das Tracking startet',
  arFailed: 'Kamera-Tracking fehlgeschlagen — nimm den Kompass',
  findMyCar: 'Auto finden',
  shareLocation: 'Standort teilen',
  endSession: 'Beenden',
  done: 'Fertig',
  keep: 'Weiter parken',
  undo: 'Rückgängig',
  shareCard: 'Als Bild teilen',
  // Keşif
  whereTo: 'Wohin?',
  noNearbyForFilter: 'Nichts in der Nähe passt zu diesem Filter',
  filters: 'Filter',
  searchRadius: 'Umkreis',
  results: '{count} in der Nähe',
  filterAll: 'Alle',
  filterCharging: 'Laden',
  filterCovered: 'Überdacht',
  myLocation: 'Mein Standort',
  noResults: 'Keine Orte gefunden.',
  photoAdded: 'Hinzugefügt',
  close: 'Schließen',
  noTariffYet: 'Für diesen Ort ist noch kein Tarif gespeichert',
  editTariff: 'Tarif bearbeiten',
  preferences: 'Allgemein',
  laParked: 'GEPARKT',
  laNextTier: 'NÄCHSTE STUFE {price}',
  laNowNext: 'Jetzt {now} · Dann {next}',
  wNoSession: 'Kein aktiver Parkvorgang',
  wSavedLabel: 'DIESEN MONAT GESPART',
  wParkTitle: 'Parken',
  wParkHint: 'Tippen, um den Platz zu sichern',
  poiParking: 'Parkplatz',
  poiCharging: 'Ladesäule',
  directions: 'Route',
  minWalk: '{minutes} Min zu Fuß',
  // Oturum
  shareMessage: 'Das Auto steht hier.',
  parkedStamp: 'GEPARKT.',
  parkedAt: 'Geparkt um {time}',
  savedStamp: '{amount} GESPART.',
  parkedDurationStamp: '{duration} GEPARKT.',
  stillParked: 'Stehst du noch bei {place}?',
  addTariff: 'Tarif eintragen, um die Kosten zu sehen',
  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: 'In {minutes} Min raus: {now} statt {next}',
  exitNowPay: 'Jetzt raus: {now} statt {next}',
  nowNext: 'Jetzt {now} · Dann {next}',
  nextTier: 'Nächste Stufe',
  tierAlert: 'Stufe {tier} in {minutes} Min. Jetzt {now}, danach {next}.',
  flatRate: '{amount} pauschal',
  perHour: '{amount} / Stunde',
  lastTimeTariff: 'Letztes Mal: {summary} — übernehmen?',
  // Park sheet'i + tarife formu (§7.3–7.4)
  detailsOptional: 'Details optional',
  pickOnMap: 'Auf der Karte wählen',
  pickOnMapHint: 'Karte verschieben, bis der Pin auf dem Auto liegt',
  pickAreaHint: 'Karte verschieben, um den Suchbereich zu setzen',
  useThisArea: 'Hier suchen',
  pickArea: 'Auf Karte wählen',
  usePin: 'Diesen Punkt nehmen',
  parkLocation: 'Standort',
  useMyLocation: 'Aktuellen Standort nehmen',
  floor: 'Etage',
  floorPlaceholder: 'UG 2, C',
  note: 'Notiz',
  notePlaceholder: 'Neben dem Aufzug',
  tariff: 'Tarif',
  tariffNone: 'Keiner',
  tariffHourly: 'Stündlich',
  tariffFlat: 'Pauschal',
  tariffTiered: 'Stufen',
  untilDuration: 'Dauer',
  unitMinShort: 'Min',
  unitHourShort: 'Std',
  unitToggle: 'Einheit wechseln',
  totalSoFar: 'Zu zahlen',
  addTier: 'Stufe hinzufügen',
  cumulativeHint: 'Trag den Gesamtbetrag ein, den du bei Ausfahrt in dieser Zeit zahlst — nicht den Aufschlag.',
  scanPro: 'Tafel scannen ist Pro',
  osmAttribution: 'Parkdaten © OpenStreetMap-Mitwirkende',
  scheduleWeekday: 'Werktagstarif angewendet',
  scheduleWeekend: 'Wochenendtarif angewendet',
  scheduleDay: 'Tagtarif angewendet',
  scheduleNight: 'Nachttarif angewendet',
  scheduleChanged: 'Der Tarif hat gewechselt — diese Tafel berechnet diese Zeit anders. Scanne neu oder bearbeite den Tarif.',
  scanBoard: 'Tafel scannen',
  scanning: 'Tafel wird gelesen',
  scanNotDetected: 'Tafel nicht lesbar — näher ran, Spiegelungen vermeiden oder von Hand eintragen',
  scanPartial: 'Einige Zeilen fehlen — prüf die Stufen unten',
  scanFailed: 'Scan fehlgeschlagen — von Hand eintragen',
  scanUnavailable: 'Scannen braucht den vollständigen App-Build',
  amountPerHour: 'Betrag pro Stunde',
  flatAmount: 'Gesamtbetrag',
  endQuestion: 'Parkvorgang beenden?',
  savedWord: 'GESPART',
  parkedWord: 'GEPARKT',
  duration: 'Dauer',
  paid: 'Gezahlt',
  avoided: 'Vermieden',
  costNow: 'Kosten jetzt',
  locating: 'Standort wird gesucht',
  use: 'Übernehmen',
  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: 'Du bist nah dran — schau dich um',
  walkToCar: 'Geh in Pfeilrichtung',
  indoorHint: 'Hier ist das Signal schwach — nimm Foto und Etage.',
  noSpotDetails: 'Kein Foto und keine Etage zu diesem Platz.',
  photo: 'Foto',
  addPhoto: 'Foto hinzufügen',
  retakePhoto: 'Neu aufnehmen',
  removePhoto: 'Entfernen',
  parkedWhen: 'Parkbeginn',
  justNow: 'Gerade eben',
  minutesAgo: 'vor {minutes} Min',
  custom: 'Eigene',
  customMinutes: 'Minuten',
  notParkedYet: 'Doch nicht hier geparkt? Eintrag löschen',
  remindMe: 'Erinnerung',
  reminderAnchor: 'Gemessen ab',
  anchorAfterPark: 'Nach dem Parken',
  anchorFirstTier: 'Vor der ersten Preiserhöhung',
  anchorEveryTier: 'Vor jeder Preiserhöhung',
  reminderAfterHow: 'Wie lange danach',
  reminderBeforeHow: 'Wie lange vorher',
  reminderKind: 'Art der Erinnerung',
  kindNotification: 'Mitteilung',
  kindAlarm: 'Ton',
  kindBoth: 'Beides',
  kindHint: 'Ton durchbricht Fokus-Modi. Ein echter Wecker, der auch lautlos klingelt, braucht iOS 26.',
  reminderNeedsTariff: 'Dafür braucht es einen Tarif — trag zuerst einen ein',
  reminderOff: 'Aus',
  hoursShort: '{hours} Std',
  simpleReminder: 'Du parkst seit {duration}.',
  // Durum satırları (§5.11)
  offlineTimer: 'Offline — der Timer läuft weiter',
  weakGpsNudge: 'Schwaches Signal — füg ein Foto oder die Etage hinzu',
  locationOff: 'Ortung aus · Einschalten',
  notificationsOff: 'Mitteilungen aus · In Einstellungen aktivieren',
  cameraOff: 'Kamera aus · In Einstellungen aktivieren',
  // Boş durumlar (§5.12)
  noSessions: 'Noch nichts geparkt.',
  firstParkHere: 'Dein erster Parkvorgang landet hier.',
  noActiveSession: 'Kein aktiver Parkvorgang',
  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'PRO ERKENNT DAS PARKEN',
  proBody: 'Du denkst nicht mehr daran.',
  proFeatureAuto: 'Fragt beim Trennen von CarPlay, ob der Timer starten soll',
  proFeatureScan: 'Tariftafeln mit der Kamera scannen',
  autoRenewNotice: 'Abos verlängern sich automatisch, bis du kündigst. Die Abbuchung erfolgt bei der Bestätigung und bei jeder Verlängerung über deine Apple ID. Verwalten oder kündigen in den Einstellungen.',
  proFeatureFind: 'Mit Kompass und AR zurück zum Auto',
  proFeatureFilter: 'Parkplätze nach Ladesäule, Überdachung und Entfernung filtern',
  planPerMonth: '{price} / Monat',
  planSave: '{percent}% SPAREN',
  terms: 'Nutzungsbedingungen (EULA)',
  planYearly: 'Jährlich',
  planMonthly: 'Monatlich',
  planLifetime: 'Einmalkauf',
  continueYearly: 'Weiter — {price}/Jahr',
  continueMonthly: 'Weiter — {price}/Monat',
  continueLifetime: 'Weiter — {price} einmalig',
  freeThen: '{intro}, danach {price}',
  demoPlans: 'Beispielpreise — nur im Debug-Build.',
  plansError: 'Abos konnten nicht geladen werden. Prüf deine Verbindung.',
  retry: 'Erneut versuchen',
  restore: 'Käufe wiederherstellen',
  privacy: 'Datenschutz',
  restored: 'Wiederhergestellt.',
  noPurchases: 'Keine Käufe gefunden.',
  purchaseFailed: 'Kauf nicht abgeschlossen.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: 'Aktiv',
  // Ayarlar (§7.9)
  updateRequiredTitle: 'UPDATE ERFORDERLICH',
  updateRequiredBody: 'Diese Version berechnet die Parkkosten nicht mehr korrekt. Aktualisiere, um weiterzumachen.',
  updateNow: 'Aktualisieren',
  settings: 'Einstellungen',
  appearance: 'Darstellung',
  themeLight: 'Hell',
  themeDark: 'Dunkel',
  themeSystem: 'System',
  language: 'Sprache',
  currency: 'Währung',
  alertThreshold: 'Vorwarnzeit',
  minutesShort: '{minutes} Min',
  autoDetect: 'Auto-Erkennung',
  autoDetectHint: 'Sichert den Standort, sobald Bluetooth oder CarPlay im Auto die Verbindung trennt.',
  autoDetectPro: 'Auto-Erkennung ist Pro',
  autoParkedAsk: 'Gerade geparkt? Tippe, um den Timer hier zu starten.',
  autoParkedNotice: 'Dein Parkplatz wurde gesichert. Timer starten?',
  permissions: 'Berechtigungen',
  locationGranted: 'Ortung an',
  notificationsGranted: 'Mitteilungen an',
  data: 'Daten',
  deleteAllData: 'Alle Einträge löschen',
  deleteAllConfirm: 'Alle Einträge löschen? Das lässt sich nicht rückgängig machen.',
  delete: 'Löschen',
  cancel: 'Abbrechen',
  developer: 'Entwickler',
  devPremium: 'Premium aktiv',
  devPremiumHint: 'Nur im Debug-Build. Ausschalten zeigt Paywall und gesperrte Zustände.',
  devResetOnboarding: 'Onboarding erneut zeigen',
  manageSubscription: 'Abo verwalten',
  exportData: 'Meine Daten exportieren',
  support: 'Support',
  rateAskTitle: 'MACHT PARKIQ, WAS ES SOLL?',
  rateAskBody: 'Eine Bewertung hilft anderen Fahrern, die App zu finden. Wenn etwas nicht stimmt, schreib uns lieber.',
  rateYes: 'Ja, bewerten',
  rateNo: 'Eher nicht',
  later: 'Später',
  goProUpsell: 'Tafeln scannen, zurückfinden, Parkplätze filtern',
  rateUs: 'ParkIQ bewerten',
  about: 'Über die App',
  version: 'Version',
  // Geçmiş (§7.8)
  lockedSessions: '{count} weitere Einträge in Pro',
  history: 'Verlauf',
  shareMonth: 'Diesen Monat teilen',
  monthlySaved: 'Gespart pro Monat',
  totalSaved: 'Gespart',
  sessionsCount: 'Vorgänge',
  avgDuration: 'Ø Dauer',
  sessionDetail: 'Parkvorgang',
  openInMaps: 'In Apple Maps öffnen',
  fixLocation: 'Parkstandort korrigieren',
  purchaseDoneTitle: 'Du bist Pro.',
  purchaseDoneBody: 'Tafeln scannen, Kompass und AR, Auto-Erkennung und Parkfilter sind jetzt aktiv.',
  restoredTitle: 'Wiederhergestellt.',
  restoredBody: 'Dein Pro-Zugang ist auf diesem iPhone wieder aktiv.',
  noPurchasesBody: 'Auf diesem Apple Account gibt es nichts wiederherzustellen. Wenn du mit einem anderen bezahlt hast, melde dich damit an und versuch es erneut.',
  restoring: 'Wird wiederhergestellt…',
  introFree: '{period} gratis',
  introDiscounted: '{period} für {price}',
  periodDay: '{count} Tage',
  periodWeek: '{count} Woche',
  periodMonth: '{count} Monat',
  periodYear: '{count} Jahr',
  lifetimeNote: 'Eine Zahlung, kein Abo',
  savedSoFar: 'ParkIQ hat dir bisher {amount} gespart',
  dailyMax: 'Tagesmaximum (optional)',
  beyondSchedule: 'Über den Bereich der Tafel hinaus — der Betrag ist nicht mehr sicher',
  clockFormat: 'Zeitformat',
  clock12: '1:04 PM',
  clock24: '13:04',
  units: 'Entfernung',
  unitsMetric: 'Meter',
  unitsImperial: 'Fuß und Meilen',
  followDevice: 'Gerät',
  headingUnavailable: 'Keine Kompassrichtung — die Entfernung stimmt trotzdem',
  calibrateCompass: 'Kompass ist verstellt — beweg das Handy in einer Acht',
  poiError: 'Parkplätze in der Nähe nicht geladen — prüf deine Verbindung',
  locationMissing: 'Kein Standort verfügbar — markier ihn auf der Karte',
  locationRough: 'Mit ±{meters} Genauigkeit gesichert — auf der Karte korrigieren',
  deleteSessionTitle: 'Diesen Parkvorgang löschen?',
  deleteSessionBody: 'Eintrag und Foto werden gelöscht. Das lässt sich nicht rückgängig machen.',
  compassLocked: 'Kompass und AR sind Pro. Standort, Foto und Notiz bleiben kostenlos.',
  back: 'Zurück',
  today: 'Heute',
  yesterday: 'Gestern',
  stillParkedShort: 'Stehst du noch? Dieser Parkvorgang läuft seit gestern.',
};
