// EN birincil dil. Kopya kuralları design.md §10: ünlem yasak, para rakamla konuşur,
// nokta imzası yalnız §3.3 whitelist'indeki display damgalarında.
export const en = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: 'PARK',
  onbBody1: 'One tap marks where you left the car. Floor, photo and note are optional — add them only when the garage is confusing.',
  onbTitle2: 'SAVE MONEY',
  onbBody2: 'Enter the tariff once and ParkIQ counts down to the next price step. Leave before it jumps and the difference stays in your pocket.',
  onbTitle3: 'FIND IT',
  onbBody3: 'Compass and map walk you back. Underground, where GPS gives up, the photo and floor you saved take over.',
  skip: 'Skip',
  enableLocation: 'Continue',
  notNow: 'Not now',
  iParked: 'I Parked',
  foundIt: 'Found it',
  arMode: 'Camera view',
  arHint: 'Follow the beam',
  arInitializing: 'Move the phone slowly to start tracking',
  arFailed: 'Camera tracking failed — use the compass',
  findMyCar: 'Find My Car',
  shareLocation: 'Share Location',
  endSession: 'End',
  done: 'Done',
  keep: 'Keep',
  undo: 'Undo',
  shareCard: 'Share Card',
  // Keşif
  whereTo: 'Where to?',
  noNearbyForFilter: 'Nothing nearby matches this filter',
  filters: 'Filters',
  searchRadius: 'Within',
  results: '{count} nearby',
  filterAll: 'All',
  filterCharging: 'Charging',
  filterCovered: 'Covered',
  myLocation: 'My location',
  noResults: 'No places found.',
  photoAdded: 'Added',
  close: 'Close',
  noTariffYet: 'No tariff saved for this spot yet',
  editTariff: 'Edit tariff',
  preferences: 'Preferences',
  laParked: 'PARKED',
  laNextTier: 'NEXT TIER {price}',
  laNowNext: 'Now {now} · Next {next}',
  wNoSession: 'No active session',
  wSavedLabel: 'SAVED THIS MONTH',
  wParkTitle: 'Park',
  wParkHint: 'Tap to save your spot',
  poiParking: 'Parking',
  poiCharging: 'Charging point',
  directions: 'Directions',
  minWalk: '{minutes} min walk',
  // Oturum
  shareMessage: 'The car is here.',
  parkedStamp: 'PARKED.',
  parkedAt: 'Parked at {time}',
  savedStamp: 'SAVED {amount}.',
  parkedDurationStamp: 'PARKED {duration}.',
  stillParked: 'Still parked at {place}?',
  addTariff: 'Add tariff to see cost',
  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: 'Leave within {minutes} min and pay {now} instead of {next}',
  exitNowPay: 'Leave now and pay {now} instead of {next}',
  nowNext: 'Now {now} · Next {next}',
  nextTier: 'Next tier',
  tierAlert: 'Tier {tier} in {minutes} min. Now {now}, after {next}.',
  flatRate: '{amount} flat',
  perHour: '{amount} / hour',
  lastTimeTariff: 'Last time: {summary} — use it?',
  // Park sheet'i + tarife formu (§7.3–7.4)
  detailsOptional: 'Details optional',
  pickOnMap: 'Pick on the map',
  pickOnMapHint: 'Move the map so the pin sits on your car',
  pickAreaHint: 'Move the map to set where to search',
  useThisArea: 'Search here',
  pickArea: 'Pick on map',
  usePin: 'Use this spot',
  parkLocation: 'Location',
  useMyLocation: 'Use my current location',
  floor: 'Floor',
  floorPlaceholder: 'Level −2, C',
  note: 'Note',
  notePlaceholder: 'Near the elevator',
  tariff: 'Tariff',
  tariffNone: 'None',
  tariffHourly: 'Hourly',
  tariffFlat: 'Flat',
  tariffTiered: 'Tiers',
  untilDuration: 'Duration',
  unitMinShort: 'min',
  unitHourShort: 'hr',
  unitToggle: 'Change unit',
  totalSoFar: 'Total to pay',
  addTier: 'Add tier',
  cumulativeHint: 'Enter the total for leaving within that time, not the extra amount.',
  scanPro: 'Board scanning is in Pro',
  osmAttribution: 'Parking data © OpenStreetMap contributors',
  scheduleWeekday: 'Weekday rate applied',
  scheduleWeekend: 'Weekend rate applied',
  scheduleDay: 'Daytime rate applied',
  scheduleNight: 'Night rate applied',
  scheduleChanged: 'The rate changed — this board prices this time differently. Scan again or edit the tariff.',
  scanBoard: 'Scan board',
  scanning: 'Reading the board',
  scanNotDetected: "Couldn't read the board — get closer, avoid glare, or enter it manually",
  scanPartial: 'Some rows could not be read — check the tiers below',
  scanFailed: 'Scan failed — enter it manually',
  scanUnavailable: 'Scanning needs the full app build',
  amountPerHour: 'Amount per hour',
  flatAmount: 'Total amount',
  endQuestion: 'End this session?',
  savedWord: 'SAVED',
  parkedWord: 'PARKED',
  duration: 'Duration',
  paid: 'Paid',
  avoided: 'Avoided',
  costNow: 'Cost now',
  locating: 'Finding location',
  use: 'Use',
  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: 'You’re close — look around',
  walkToCar: 'Walk toward the arrow',
  indoorHint: 'Signal is weak here — use the photo and floor note.',
  noSpotDetails: 'No photo or floor note for this spot.',
  photo: 'Photo',
  addPhoto: 'Add photo',
  retakePhoto: 'Retake',
  removePhoto: 'Remove',
  parkedWhen: 'I parked',
  justNow: 'Just now',
  minutesAgo: '{minutes} min ago',
  custom: 'Custom',
  customMinutes: 'Minutes',
  notParkedYet: 'Didn’t park here? Remove this record',
  remindMe: 'Remind me',
  reminderOff: 'Off',
  hoursShort: '{hours} h',
  simpleReminder: "You've been parked for {duration}.",
  // Durum satırları (§5.11)
  offlineTimer: 'Offline — timer still running',
  weakGpsNudge: 'Weak signal — add a photo or floor note',
  locationOff: 'Location off · Turn on',
  notificationsOff: 'Notifications off · Turn on in Settings',
  cameraOff: 'Camera off · Turn on in Settings',
  // Boş durumlar (§5.12)
  noSessions: 'No sessions yet.',
  firstParkHere: 'Your first park will land here.',
  noActiveSession: 'No active session',
  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'PRO DETECTS PARKING',
  proBody: 'You never think about it.',
  proFeatureAuto: 'Asks to start the timer when CarPlay disconnects',
  proFeatureScan: 'Scan tariff boards with the camera',
  autoRenewNotice: 'Subscriptions renew automatically until cancelled. Your Apple ID is charged at confirmation and again at each renewal. Manage or cancel in Settings.',
  proFeatureFind: 'Compass and AR guidance back to the car',
  proFeatureFilter: 'Filter parking by charger, cover and distance',
  planPerMonth: '{price} / month',
  planSave: 'SAVE {percent}%',
  terms: 'Terms (EULA)',
  planYearly: 'Yearly',
  planMonthly: 'Monthly',
  planLifetime: 'Lifetime',
  continueYearly: 'Continue — {price}/year',
  continueMonthly: 'Continue — {price}/month',
  continueLifetime: 'Continue — {price} once',
  freeThen: '{intro}, then {price}',
  demoPlans: 'Demo prices — debug build only.',
  plansError: 'Couldn’t load plans. Check your connection.',
  retry: 'Retry',
  restore: 'Restore',
  privacy: 'Privacy',
  restored: 'Restored.',
  noPurchases: 'No purchases found.',
  purchaseFailed: 'Purchase failed.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: 'Active',
  // Ayarlar (§7.9)
  updateRequiredTitle: 'UPDATE REQUIRED',
  updateRequiredBody: 'This version can no longer keep your parking costs accurate. Update to continue.',
  updateNow: 'Update',
  settings: 'Settings',
  appearance: 'Appearance',
  themeLight: 'Light',
  themeDark: 'Dark',
  themeSystem: 'System',
  language: 'Language',
  currency: 'Currency',
  alertThreshold: 'Alert me before',
  minutesShort: '{minutes} min',
  autoDetect: 'Auto-detection',
  autoDetectHint: 'Saves your spot when your car’s Bluetooth or CarPlay disconnects.',
  autoDetectPro: 'Auto-detection in Pro',
  autoParkedAsk: 'Did you just park? Tap to start the timer here.',
  autoParkedNotice: 'Your parking spot was saved. Start the timer?',
  permissions: 'Permissions',
  locationGranted: 'Location on',
  notificationsGranted: 'Notifications on',
  data: 'Data',
  deleteAllData: 'Delete all sessions',
  deleteAllConfirm: 'Delete all sessions? This cannot be undone.',
  delete: 'Delete',
  cancel: 'Cancel',
  developer: 'Developer',
  devPremium: 'Premium unlocked',
  devPremiumHint: 'Debug builds only. Turn off to see the paywall and locked states.',
  devResetOnboarding: 'Show onboarding again',
  manageSubscription: 'Manage subscription',
  exportData: 'Export my data',
  support: 'Support',
  rateAskTitle: 'IS PARKIQ WORKING FOR YOU?',
  rateAskBody: 'A rating helps other drivers find it. If something is off, tell us instead.',
  rateYes: 'Yes, rate it',
  rateNo: 'Not really',
  later: 'Later',
  goProUpsell: 'Scan boards, get guided back, filter parking',
  rateUs: 'Rate ParkIQ',
  about: 'About',
  version: 'Version',
  // Geçmiş (§7.8)
  lockedSessions: '{count} more sessions in Pro',
  history: 'History',
  shareMonth: 'Share this month',
  monthlySaved: 'Saved per month',
  totalSaved: 'Saved',
  sessionsCount: 'Sessions',
  avgDuration: 'Avg time',
  sessionDetail: 'Session',
  openInMaps: 'Open in Maps',
  fixLocation: 'Fix parking location',
  purchaseDoneTitle: 'You are Pro.',
  purchaseDoneBody: 'Board scanning, compass and AR guidance, auto-detect and parking filters are unlocked.',
  restoredTitle: 'Restored.',
  restoredBody: 'Your Pro access is back on this iPhone.',
  noPurchasesBody: 'Nothing to restore on this Apple Account. If you paid with another one, sign in with it and try again.',
  restoring: 'Restoring…',
  introFree: '{{period}} free',
  introDiscounted: '{{period}} for {{price}}',
  periodDay: '{{count}} day',
  periodWeek: '{{count}} week',
  periodMonth: '{{count}} month',
  periodYear: '{{count}} year',
  lifetimeNote: 'One payment, no subscription',
  savedSoFar: 'ParkIQ has saved you {{amount}} so far',
  dailyMax: 'Daily maximum (optional)',
  beyondSchedule: 'Past what the board covers — the amount is no longer certain',
  clockFormat: 'Time format',
  clock12: '1:04 PM',
  clock24: '13:04',
  units: 'Distance',
  unitsMetric: 'Metres',
  unitsImperial: 'Feet and miles',
  followDevice: 'Follow device',
  headingUnavailable: 'No compass direction — the distance is still correct',
  calibrateCompass: 'Compass is off — wave the phone in a figure 8',
  poiError: 'Could not load nearby parking — check your connection',
  locationMissing: 'Could not get a location — mark it on the map',
  locationRough: 'Saved with ±{{meters}} accuracy — fix it on the map',
  deleteSessionTitle: 'Delete this parking?',
  deleteSessionBody: 'The record and its photo are removed. This cannot be undone.',
  compassLocked: 'Compass and AR guidance are Pro. Your spot, photo and note stay free.',
  back: 'Back',
  today: 'Today',
  yesterday: 'Yesterday',
  stillParkedShort: 'Still parked? This session started yesterday.',
} as const;
export type CopyKey = keyof typeof en;
