// EN birincil dil. Kopya kuralları design.md §10: ünlem yasak, para rakamla konuşur,
// nokta imzası yalnız §3.3 whitelist'indeki display damgalarında.
export const en = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: 'PARK',
  onbBody1: 'One tap marks where you left the car. Floor, photo and note are optional — add them only when the garage is confusing.',
  onbTitle2: 'SAVE MONEY',
  onbBody2: 'Enter the tariff once and ParkIQ counts down to the next price step. Leave before it jumps and the difference stays in your pocket.',
  onbTitle3: 'FIND IT',
  onbBody3: 'Compass and map walk you back. Underground, where GPS gives up, the photo and floor you saved take over.',
  skip: 'Skip',
  enableLocation: 'Continue',
  notNow: 'Not now',

  iParked: 'I Parked',
  findMyCar: 'Find My Car',
  shareLocation: 'Share Location',
  endSession: 'End',
  done: 'Done',
  keep: 'Keep',
  undo: 'Undo',
  shareCard: 'Share Card',

  // Keşif
  whereTo: 'Where to?',
  filterAll: 'All',
  filterCharging: 'Charging',
  filterCovered: 'Covered',
  myLocation: 'My location',
  noResults: 'No places found.',
  photoAdded: 'Added',
  close: 'Close',
  noTariffYet: 'No tariff saved for this spot yet',
  editTariff: 'Edit tariff',
  preferences: 'Preferences',
  poiParking: 'Parking',
  poiCharging: 'Charging point',
  directions: 'Directions',
  minWalk: '{minutes} min walk',

  // Oturum
  shareMessage: 'The car is here.',
  parkedStamp: 'PARKED.',
  parkedAt: 'Parked at {time}',
  savedStamp: 'SAVED {amount}.',
  parkedDurationStamp: 'PARKED {duration}.',
  stillParked: 'Still parked at {place}?',
  addTariff: 'Add tariff to see cost',

  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: 'Leave within {minutes} min and pay {now} instead of {next}',
  exitNowPay: 'Leave now and pay {now} instead of {next}',
  nowNext: 'Now {now} · Next {next}',
  nextTier: 'Next tier',
  tierAlert: 'Tier {tier} in {minutes} min. Now {now}, after {next}.',
  flatRate: '{amount} flat',
  perHour: '{amount} / hour',
  lastTimeTariff: 'Last time: {summary} — use it?',

  // Park sheet'i + tarife formu (§7.3–7.4)
  detailsOptional: 'Details optional',
  floor: 'Floor',
  floorPlaceholder: 'Level −2, C',
  note: 'Note',
  notePlaceholder: 'Near the elevator',
  tariff: 'Tariff',
  tariffNone: 'None',
  tariffHourly: 'Hourly',
  tariffFlat: 'Flat',
  tariffTiered: 'Tiers',
  untilHours: 'Up to (hours)',
  totalSoFar: 'Total to pay',
  addTier: 'Add tier',
  cumulativeHint: 'Enter the total for leaving within that time, not the extra amount.',
  scanPro: 'Board scanning is in Pro',
  osmAttribution: 'Parking data © OpenStreetMap contributors',
  scanBoard: 'Scan board',
  scanning: 'Reading the board',
  scanNotDetected: "Couldn't read the board — enter it manually",
  scanFailed: 'Scan failed — enter it manually',
  scanUnavailable: 'Scanning needs the full app build',
  amountPerHour: 'Amount per hour',
  flatAmount: 'Total amount',
  endQuestion: 'End this session?',
  savedWord: 'SAVED',
  parkedWord: 'PARKED',
  duration: 'Duration',
  paid: 'Paid',
  avoided: 'Avoided',
  costNow: 'Cost now',

  locating: 'Finding location',
  use: 'Use',

  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: 'You’re close — look around',
  walkToCar: 'Walk toward the arrow',
  indoorHint: 'Signal is weak here — use the photo and floor note.',
  noSpotDetails: 'No photo or floor note for this spot.',
  photo: 'Photo',
  addPhoto: 'Add photo',
  retakePhoto: 'Retake',
  removePhoto: 'Remove',
  parkedWhen: 'I parked',
  justNow: 'Just now',
  minutesAgo: '{minutes} min ago',
  custom: 'Custom',
  customMinutes: 'Minutes',
  notParkedYet: 'Didn’t park here? Remove this record',
  remindMe: 'Remind me',
  reminderOff: 'Off',
  hoursShort: '{hours} h',
  simpleReminder: "You've been parked for {duration}.",

  // Durum satırları (§5.11)
  offlineTimer: 'Offline — timer still running',
  weakGpsNudge: 'Weak signal — add a photo or floor note',
  locationOff: 'Location off · Turn on',
  notificationsOff: 'Notifications off · Turn on in Settings',
  cameraOff: 'Camera off · Turn on in Settings',

  // Boş durumlar (§5.12)
  noSessions: 'No sessions yet.',
  firstParkHere: 'Your first park will land here.',
  noActiveSession: 'No active session',

  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'PRO DETECTS PARKING',
  proBody: 'You never think about it.',
  proFeatureAuto: 'Auto-detection when you leave the car',
  proFeatureScan: 'Scan tariff boards with the camera',
  autoRenewNotice: 'Subscriptions renew automatically until cancelled. Your Apple ID is charged at confirmation and again at each renewal. Manage or cancel in Settings.',
  proFeatureHistory: 'Unlimited history and stats',
  planYearly: 'Yearly',
  planMonthly: 'Monthly',
  planLifetime: 'Lifetime',
  continueYearly: 'Continue — {price}/year',
  continueMonthly: 'Continue — {price}/month',
  continueLifetime: 'Continue — {price} once',
  freeThen: '{intro}, then {price}',
  demoPlans: 'Demo prices — debug build only.',
  plansError: 'Couldn’t load plans. Check your connection.',
  retry: 'Retry',
  restore: 'Restore',
  terms: 'Terms',
  privacy: 'Privacy',
  restored: 'Restored.',
  noPurchases: 'No purchases found.',
  purchaseFailed: 'Purchase failed.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: 'Active',

  // Ayarlar (§7.9)
  settings: 'Settings',
  appearance: 'Appearance',
  themeLight: 'Light',
  themeDark: 'Dark',
  themeSystem: 'System',
  language: 'Language',
  currency: 'Currency',
  alertThreshold: 'Alert me before',
  minutesShort: '{minutes} min',
  autoDetect: 'Auto-detection',
  autoDetectHint: 'Saves your spot when your car’s Bluetooth or CarPlay disconnects.',
  autoDetectPro: 'Auto-detection in Pro',
  autoParkedNotice: 'Your parking spot was saved. Start the timer?',
  permissions: 'Permissions',
  locationGranted: 'Location on',
  notificationsGranted: 'Notifications on',
  data: 'Data',
  deleteAllData: 'Delete all sessions',
  deleteAllConfirm: 'Delete all sessions? This cannot be undone.',
  delete: 'Delete',
  cancel: 'Cancel',
  developer: 'Developer',
  devPremium: 'Premium unlocked',
  devPremiumHint: 'Debug builds only. Turn off to see the paywall and locked states.',
  devResetOnboarding: 'Show onboarding again',
  manageSubscription: 'Manage subscription',
  exportData: 'Export my data',
  support: 'Support',
  rateUs: 'Rate ParkIQ',
  about: 'About',
  version: 'Version',

  // Geçmiş (§7.8)
  lockedSessions: '{count} more sessions in Pro',
  history: 'History',
  shareMonth: 'Share this month',
  monthlySaved: 'Saved per month',
  totalSaved: 'Saved',
  sessionsCount: 'Sessions',
  avgDuration: 'Avg time',
  sessionDetail: 'Session',
  openInMaps: 'Open in Maps',
  back: 'Back',
  today: 'Today',
  yesterday: 'Yesterday',
  stillParkedShort: 'Still parked? This session started yesterday.',
} as const;

export type CopyKey = keyof typeof en;
