export const en = {
  auth: {
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    loginButton: "Sign In",
    registerButton: "Sign Up",
    appleLogin: "Continue with Apple",
    googleLogin: "Continue with Google",
    facebookLogin: "Continue with Facebook",
    backToLogin: "Back to Login",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    sendResetLink: "Send Reset Link",
    firstName: "First Name",
    lastName: "Last Name",
    phone: "Phone Number",
    bloodType: "Blood Type",
    licensePlate: "License Plate",
    confirmPassword: "Confirm Password",
    passwordsDoNotMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    emailRequired: "Please enter your email",
    passwordRequired: "Please enter your password",
    firstNameRequired: "Please enter your first name",
    lastNameRequired: "Please enter your last name",
    phoneRequired: "Please enter your phone number",
    bloodTypeRequired: "Please select your blood type",
    licensePlateRequired: "Please enter your license plate",
    resetLinkSent: "Password reset link has been sent to your email",
    enterEmailForReset: "Enter your email to receive a password reset link",
    loginSubtitle: "Welcome back! Please sign in to continue.",
    registerSubtitle: "Create your account to get started",
    optional: "Optional",
    emailConfirmationRequired: "Email confirmation required",
    emailConfirmationMessage: "Registration successful! Please click the confirmation link sent to your email. You can sign in after confirming your email.",
    emailConfirmationProfileMessage: "Registration successful! Please click the confirmation link sent to your email. Your profile information will be saved after email confirmation.",
    emailNotConfirmed: "Please confirm your email address before logging in. Check your email for the confirmation link.",
    emailNotConfirmedExpoGo: "Please confirm your email address. Click the link in your email, then return here and try logging in again.",
    resendConfirmationEmail: "Resend Confirmation Email",
    confirmationEmailResent: "Confirmation email has been resent. Please check your email inbox.",
    confirmationEmailResentExpoGo: "Confirmation email has been sent. Click the link in your email, then return here and log in.",
    resendConfirmationEmailError: "Failed to resend confirmation email. Please try again.",
    profileNotFound: "Account not found.",
    completeProfile: "Complete Profile",
    completeProfileDescription: "Please complete your profile information to continue",
    profileIncomplete: "Your profile is incomplete",
  },
  onboarding: {
    skip: "Skip",
    next: "Next",
    getStarted: "Get Started",
    slide1Title: "Find Parking Easily",
    slide1Description: "Discover nearby parking spots with real-time availability and pricing information.",
    slide2Title: "Track Your Parking",
    slide2Description: "Monitor your parking sessions with smart timers and automatic reminders.",
    slide3Title: "Save Money",
    slide3Description: "Get the best parking rates and avoid unnecessary charges with smart notifications.",
    slide4Title: "Get Started",
    slide4Description: "Start parking smarter today. Create your account and begin your journey.",
  },
  map: {
    parkingDetails: "Parking Details",
    distance: "Distance",
    priceInfo: "Price Information",
    noPriceInfo: "Price information not found",
    addPriceInfo: "Would you like to add price information?",
    openInMaps: "Open in Apple Maps",
    priceTier: "{{duration}} hours: {{price}} {{currency}}",
    priceDisclaimer: "Price information is submitted by users, do not rely on its accuracy.",
    addPriceTitle: "Add Price Information",
    addPriceDescription: "Add price information for this parking spot",
    currency: "Currency",
    priceTiers: "Price Tiers",
    addTier: "Add Tier",
    tierDuration: "Duration (hours)",
    tierPrice: "Price",
    removeTier: "Remove",
    submitPrice: "Submit Price",
    priceSubmitted: "Price information submitted successfully",
    priceSubmitError: "An error occurred while submitting price information",
    currencyRequired: "Currency must be selected",
    tierRequired: "At least one price tier must be added",
    userNotFoundError: "User profile not found. Please restart the app or sign in again.",
    title: "Map",
    startParking: "Start Parking",
    noLocation: "Location not available",
    nearbyPrices: "Nearby Prices",
    noPrices: "No prices found",
  },
  parking: {
    title: "Parking",
    startParking: "Start Parking",
    activeParking: "Active Parking",
    endParking: "End Parking",
    timer: "Parking Time",
    noActiveSession: "No active parking session",
    sessionEnded: "Parking session ended",
    setupParking: "Start Parking",
    currentLocation: "Current Location",
    note: "Note (optional)",
    notePlaceholder: "Add a note about this parking session",
    parkedMinutesAgo: "I parked X minutes ago",
    startTimeAdjustment: "Start Time Adjustment",
    ago: "ago",
    minutes: "minutes",
    enableReminder: "Enable Reminder",
    reminderOffset: "Reminder Offset",
    reminderAfter: "Remind After",
    photo: "Photo",
    photoPlaceholder: "Photo feature coming soon",
    takePhoto: "Take Photo",
    confirmParking: "Confirm Parking",
    reminderTitle: "Parking Reminder",
    reminderBody: "Don't forget to check your parking!",
    editNote: "Edit Note",
    reminderEnabled: "Reminder Enabled",
    reminderDisabled: "Reminder Disabled",
    summary: "Parking Summary",
    adjustedStartTime: "Adjusted Start Time",
    location: "Location",
    reminderStatus: "Reminder Status",
    summaryTitle: "Parking Summary",
    atTime: "At Time",
    afterDuration: "After Duration",
    remindAt: "Remind at",
  },
  history: {
    title: "History",
    noHistory: "No parking history",
    startTime: "Start",
    endTime: "End",
    duration: "Duration",
    pullToRefresh: "Pull to refresh",
    details: "Parking Details",
    detailTitle: "Parking Details",
    delete: "Delete",
    deleteSession: "Delete Session",
    deleteConfirm: "Are you sure you want to delete this parking session? This action cannot be undone.",
    timeDetails: "Time Details",
    parkingCost: "Parking Cost",
    total: "Total",
  },
  prices: {
    title: "Prices",
    submitPrice: "Submit Price",
    placeId: "Place ID (optional)",
    currency: "Currency",
    priceJson: "Price JSON",
    submit: "Submit",
  },
  profile: {
    title: "Profile",
    statistics: "Statistics",
    totalSessions: "Total Sessions",
    totalTime: "Total Time",
    saved: "Saved",
    recentActivity: "Recent Activity",
    noRecentActivity: "No recent activity",
    quickActions: "Quick Actions",
    rateApp: "Rate App",
    helpSupport: "Help & Support",
    shareApp: "Share App",
    moneySaved: "Money Saved",
    noSavings: "No savings calculated yet",
    savingsDescription: "Savings are calculated for sessions that ended 15 minutes before the next pricing tier",
    actual: "Actual",
    wouldBe: "Would be",
    noEmail: "No email",
    user: "User",
    parkingSession: "Parking Session",
    justNow: "Just now",
    minutesAgo: "{{count}} minute ago",
    minutesAgo_plural: "{{count}} minutes ago",
    hoursAgo: "{{count}} hour ago",
    hoursAgo_plural: "{{count}} hours ago",
    yesterday: "Yesterday",
    daysAgo: "{{count}} day ago",
    daysAgo_plural: "{{count}} days ago",
    personalInfo: "Personal Information",
  },
  settings: {
    title: "Settings",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    logout: "Logout",
    logoutConfirm: "Are you sure you want to log out?",
    reminderOffset: "Reminder Offset",
    currency: "Currency",
    language: "Language",
    languageEnglish: "English",
    languageTurkish: "Türkçe",
    selectCurrency: "Select Currency",
    selectLanguage: "Select Language",
    deleteAccount: "Delete Account",
    deleteAccountConfirm: "Are you sure you want to delete your account? This action cannot be undone.",
    deleteAccountMock: "This is a mock action. Account deletion feature coming soon.",
    accountDeleted: "Your account has been deleted successfully.",
    deleteAccountError: "Failed to delete account. Please try again.",
    appearance: "Appearance",
    reminders: "Reminders",
    notifications: "Notifications",
    emailNotifications: "Email Notifications",
    enabled: "Enabled",
    dataPrivacy: "Data & Privacy",
    exportData: "Export Data",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    about: "About",
    version: "Version",
    buildNumber: "Build Number",
    account: "Account",
    delete: "Delete",
  },
  common: {
    loading: "Loading...",
    error: "Error",
    retry: "Retry",
    cancel: "Cancel",
    save: "Save",
    done: "Done",
    select: "Select",
    hourShort: "h",
    minuteShort: "m",
    ongoing: "Ongoing",
    today: "Today",
    yesterday: "Yesterday",
    info: "Info",
    ok: "OK",
  },
};

