import type { CopyKey } from './en';

// ES-ES (İspanya İspanyolcası). Hitap "tú"; sözlük İspanya: aparcamiento / aparcar / coche.
export const esES: Record<CopyKey, string> = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: 'APARCA',
  onbBody1: 'Un toque marca dónde has dejado el coche. Planta, foto y nota son opcionales — añádelas solo si el aparcamiento es confuso.',
  onbTitle2: 'AHORRA',
  onbBody2: 'Introduce la tarifa una vez y ParkIQ cuenta lo que falta para el siguiente tramo. Si sales antes del salto, la diferencia se queda en tu bolsillo.',
  onbTitle3: 'ENCUÉNTRALO',
  onbBody3: 'La brújula y el mapa te llevan de vuelta. Bajo tierra, donde el GPS se rinde, tiran la foto y la planta que guardaste.',
  skip: 'Saltar',
  enableLocation: 'Continuar',
  notNow: 'Ahora no',
  iParked: 'He aparcado',
  foundIt: 'Lo he encontrado',
  arMode: 'Vista de cámara',
  arHint: 'Sigue el haz',
  arInitializing: 'Mueve el móvil despacio para iniciar el seguimiento',
  arFailed: 'Falló el seguimiento de cámara — usa la brújula',
  findMyCar: 'Buscar mi coche',
  shareLocation: 'Compartir ubicación',
  endSession: 'Terminar',
  done: 'Listo',
  keep: 'Seguir',
  undo: 'Deshacer',
  shareCard: 'Compartir tarjeta',
  // Keşif
  whereTo: '¿Adónde?',
  noNearbyForFilter: 'Nada cerca coincide con este filtro',
  filters: 'Filtros',
  searchRadius: 'Distancia',
  results: '{count} cerca',
  filterAll: 'Todos',
  filterCharging: 'Recarga',
  filterCovered: 'Cubierto',
  myLocation: 'Mi ubicación',
  noResults: 'Sin resultados.',
  photoAdded: 'Añadida',
  close: 'Cerrar',
  noTariffYet: 'Aún no hay tarifa guardada para este sitio',
  editTariff: 'Editar tarifa',
  preferences: 'Preferencias',
  laParked: 'APARCADO',
  laNextTier: 'PRÓXIMO TRAMO {price}',
  laNowNext: 'Ahora {now} · Luego {next}',
  wNoSession: 'Sin sesión activa',
  wSavedLabel: 'AHORRADO ESTE MES',
  wParkTitle: 'Aparcar',
  wParkHint: 'Toca para guardar tu sitio',
  poiParking: 'Aparcamiento',
  poiCharging: 'Punto de recarga',
  directions: 'Cómo llegar',
  minWalk: '{minutes} min a pie',
  // Oturum
  shareMessage: 'El coche está aquí.',
  parkedStamp: 'APARCADO.',
  parkedAt: 'Aparcado a las {time}',
  savedStamp: '{amount} AHORRADOS.',
  parkedDurationStamp: 'APARCADO {duration}.',
  stillParked: '¿Sigues aparcado en {place}?',
  addTariff: 'Añade la tarifa para ver el coste',
  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: 'Sal en {minutes} min y paga {now} en vez de {next}',
  exitNowPay: 'Sal ahora y paga {now} en vez de {next}',
  nowNext: 'Ahora {now} · Luego {next}',
  nextTier: 'Siguiente tramo',
  tierAlert: 'Tramo {tier} en {minutes} min. Ahora {now}, después {next}.',
  flatRate: '{amount} fijo',
  perHour: '{amount} / hora',
  lastTimeTariff: 'La última vez: {summary} — ¿usarla?',
  // Park sheet'i + tarife formu (§7.3–7.4)
  detailsOptional: 'Detalles opcionales',
  pickOnMap: 'Elegir en el mapa',
  pickOnMapHint: 'Mueve el mapa hasta que el pin quede sobre tu coche',
  pickAreaHint: 'Mueve el mapa para elegir dónde buscar',
  useThisArea: 'Buscar aquí',
  pickArea: 'Marcar en el mapa',
  usePin: 'Usar este sitio',
  parkLocation: 'Ubicación',
  useMyLocation: 'Usar mi ubicación actual',
  floor: 'Planta',
  floorPlaceholder: '−2, zona C',
  note: 'Nota',
  notePlaceholder: 'Junto al ascensor',
  tariff: 'Tarifa',
  tariffNone: 'Ninguna',
  tariffHourly: 'Por horas',
  tariffFlat: 'Fija',
  tariffTiered: 'Tramos',
  untilDuration: 'Duración',
  unitMinShort: 'min',
  unitHourShort: 'h',
  unitToggle: 'Cambiar unidad',
  totalSoFar: 'Total a pagar',
  addTier: 'Añadir tramo',
  cumulativeHint: 'Escribe el total que pagarías al salir dentro de ese tiempo, no el importe adicional.',
  scanPro: 'Escanear carteles es de Pro',
  osmAttribution: 'Datos de aparcamiento © colaboradores de OpenStreetMap',
  scheduleWeekday: 'Tarifa de laborables aplicada',
  scheduleWeekend: 'Tarifa de fin de semana aplicada',
  scheduleDay: 'Tarifa de día aplicada',
  scheduleNight: 'Tarifa de noche aplicada',
  scheduleChanged: 'La tarifa ha cambiado — este cartel cobra distinto a esta hora. Vuelve a escanear o edita la tarifa.',
  scanBoard: 'Escanear cartel',
  scanning: 'Leyendo el cartel',
  scanNotDetected: 'No se ha podido leer el cartel — acércate, evita los reflejos o introdúcela a mano',
  scanPartial: 'Algunas líneas no se han leído — revisa los tramos de abajo',
  scanFailed: 'Escaneo fallido — introdúcela a mano',
  scanUnavailable: 'El escaneo necesita la versión completa de la app',
  amountPerHour: 'Importe por hora',
  flatAmount: 'Importe total',
  endQuestion: '¿Terminar la sesión?',
  savedWord: 'AHORRADO',
  parkedWord: 'APARCADO',
  duration: 'Duración',
  paid: 'Pagado',
  avoided: 'Evitado',
  costNow: 'Coste ahora',
  locating: 'Buscando ubicación',
  use: 'Usar',
  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: 'Estás cerca — mira alrededor',
  walkToCar: 'Camina hacia la flecha',
  indoorHint: 'Aquí la señal es débil — usa la foto y la planta.',
  noSpotDetails: 'Sin foto ni planta para este sitio.',
  photo: 'Foto',
  addPhoto: 'Añadir foto',
  retakePhoto: 'Repetir',
  removePhoto: 'Quitar',
  parkedWhen: 'He aparcado',
  justNow: 'Ahora mismo',
  minutesAgo: 'hace {minutes} min',
  custom: 'Otro',
  customMinutes: 'Minutos',
  notParkedYet: '¿No has aparcado aquí? Borra el registro',
  remindMe: 'Avisarme',
  reminderAnchor: 'Contar desde',
  anchorAfterPark: 'Después de aparcar',
  anchorFirstTier: 'Antes de la primera subida',
  anchorEveryTier: 'Antes de cada subida',
  reminderAfterHow: 'Cuánto después',
  reminderBeforeHow: 'Cuánto antes',
  reminderKind: 'Cómo avisarme',
  kindNotification: 'Notificación',
  kindAlarm: 'Sonido',
  kindBoth: 'Ambos',
  kindHint: 'El sonido atraviesa los modos de concentración. Una alarma que suene en silencio necesita iOS 26.',
  reminderNeedsTariff: 'Esto necesita una tarifa — añádela primero',
  reminderOff: 'Desactivado',
  hoursShort: '{hours} h',
  simpleReminder: 'Llevas {duration} aparcado.',
  // Durum satırları (§5.11)
  offlineTimer: 'Sin conexión — el contador sigue',
  weakGpsNudge: 'Señal débil — añade una foto o la planta',
  locationOff: 'Ubicación desactivada · Activar',
  notificationsOff: 'Notificaciones desactivadas · Actívalas en Ajustes',
  cameraOff: 'Cámara desactivada · Actívala en Ajustes',
  // Boş durumlar (§5.12)
  noSessions: 'Aún no hay sesiones.',
  firstParkHere: 'Tu primer aparcamiento aparecerá aquí.',
  noActiveSession: 'Sin sesión activa',
  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'PRO DETECTA QUE APARCAS',
  proBody: 'Tú no piensas en ello.',
  proFeatureAuto: 'Pregunta si arrancar el contador cuando CarPlay se desconecta',
  proFeatureScan: 'Escanea los carteles de tarifas con la cámara',
  autoRenewNotice: 'Las suscripciones se renuevan automáticamente hasta que las canceles. El cargo se hace en tu Apple ID al confirmar y en cada renovación. Puedes gestionarla o cancelarla en Ajustes.',
  proFeatureFind: 'Brújula y AR para volver al coche',
  proFeatureFilter: 'Filtra aparcamientos por recarga, cubierto y distancia',
  planPerMonth: '{price} / mes',
  planSave: 'AHORRA {percent} %',
  terms: 'Términos (EULA)',
  planYearly: 'Anual',
  planMonthly: 'Mensual',
  planLifetime: 'Para siempre',
  continueYearly: 'Continuar — {price}/año',
  continueMonthly: 'Continuar — {price}/mes',
  continueLifetime: 'Continuar — {price} una vez',
  freeThen: '{intro}, luego {price}',
  demoPlans: 'Precios de ejemplo — solo en versión de desarrollo.',
  plansError: 'No se han podido cargar los planes. Revisa tu conexión.',
  retry: 'Reintentar',
  restore: 'Restaurar compras',
  privacy: 'Privacidad',
  restored: 'Restaurado.',
  noPurchases: 'No se han encontrado compras.',
  purchaseFailed: 'La compra no se ha completado.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: 'Activo',
  // Ayarlar (§7.9)
  updateRequiredTitle: 'ACTUALIZACIÓN NECESARIA',
  updateRequiredBody: 'Esta versión ya no calcula bien lo que pagas por aparcar. Actualiza para continuar.',
  updateNow: 'Actualizar',
  settings: 'Ajustes',
  appearance: 'Apariencia',
  themeLight: 'Claro',
  themeDark: 'Oscuro',
  themeSystem: 'Sistema',
  language: 'Idioma',
  currency: 'Moneda',
  alertThreshold: 'Antelación del aviso',
  minutesShort: '{minutes} min',
  autoDetect: 'Detección automática',
  autoDetectHint: 'Guarda tu sitio cuando se desconecta el Bluetooth del coche o CarPlay.',
  autoDetectPro: 'La detección automática es de Pro',
  autoParkedAsk: '¿Acabas de aparcar? Toca para arrancar el contador aquí.',
  autoParkedNotice: 'Se ha guardado tu sitio. ¿Arrancamos el contador?',
  permissions: 'Permisos',
  locationGranted: 'Ubicación activada',
  notificationsGranted: 'Notificaciones activadas',
  data: 'Datos',
  deleteAllData: 'Borrar todas las sesiones',
  deleteAllConfirm: '¿Borrar todas las sesiones? No se puede deshacer.',
  delete: 'Borrar',
  cancel: 'Cancelar',
  developer: 'Desarrollador',
  devPremium: 'Premium activado',
  devPremiumHint: 'Solo en versiones de desarrollo. Desactívalo para ver el paywall y los estados bloqueados.',
  devResetOnboarding: 'Volver a mostrar el onboarding',
  manageSubscription: 'Gestionar suscripción',
  exportData: 'Exportar mis datos',
  support: 'Soporte',
  rateAskTitle: '¿PARKIQ TE SIRVE?',
  rateAskBody: 'Una valoración ayuda a que otros conductores lo encuentren. Si algo falla, cuéntanoslo.',
  rateYes: 'Sí, valorar',
  rateNo: 'No mucho',
  later: 'Más tarde',
  goProUpsell: 'Escanea carteles, vuelve guiado al coche, filtra aparcamientos',
  rateUs: 'Valorar ParkIQ',
  about: 'Información',
  version: 'Versión',
  // Geçmiş (§7.8)
  lockedSessions: '{count} sesiones más en Pro',
  history: 'Historial',
  shareMonth: 'Compartir el mes',
  monthlySaved: 'Ahorro mensual',
  totalSaved: 'Ahorrado',
  sessionsCount: 'Sesiones',
  avgDuration: 'Tiempo medio',
  sessionDetail: 'Sesión',
  openInMaps: 'Abrir en Mapas',
  fixLocation: 'Corregir la ubicación',
  purchaseDoneTitle: 'Ya eres Pro.',
  purchaseDoneBody: 'Escaneo de carteles, brújula y AR, detección automática y filtros de aparcamiento ya están activos.',
  restoredTitle: 'Restaurado.',
  restoredBody: 'Tu acceso Pro vuelve a estar activo en este iPhone.',
  noPurchasesBody: 'No hay nada que restaurar en esta Apple Account. Si pagaste con otra, inicia sesión con ella e inténtalo de nuevo.',
  restoring: 'Restaurando…',
  introFree: '{period} gratis',
  introDiscounted: '{period} por {price}',
  periodDay: '{count} día',
  periodWeek: '{count} semana',
  periodMonth: '{count} mes',
  periodYear: '{count} año',
  lifetimeNote: 'Un pago, sin suscripción',
  savedSoFar: 'ParkIQ te ha ahorrado {amount} hasta ahora',
  dailyMax: 'Máximo diario (opcional)',
  beyondSchedule: 'Has pasado lo que cubre el cartel — el importe ya no es seguro',
  clockFormat: 'Formato de hora',
  clock12: '1:04 PM',
  clock24: '13:04',
  units: 'Distancia',
  unitsMetric: 'Metros',
  unitsImperial: 'Pies y millas',
  followDevice: 'Seguir el dispositivo',
  headingUnavailable: 'Sin dirección de brújula — la distancia sigue siendo correcta',
  calibrateCompass: 'La brújula está descalibrada — mueve el móvil dibujando un 8',
  poiError: 'No se han podido cargar los aparcamientos cercanos — revisa tu conexión',
  locationMissing: 'No se ha podido obtener la ubicación — márcala en el mapa',
  locationRough: 'Guardado con ±{meters} de precisión — corrígelo en el mapa',
  deleteSessionTitle: '¿Borrar este aparcamiento?',
  deleteSessionBody: 'Se borran el registro y su foto. No se puede deshacer.',
  compassLocked: 'La brújula y el AR son de Pro. Tu sitio, foto y nota siguen siendo gratis.',
  back: 'Atrás',
  today: 'Hoy',
  yesterday: 'Ayer',
  stillParkedShort: '¿Sigues aparcado? Esta sesión empezó ayer.',
};
