import type { CopyKey } from './en';

// es-ES üstüne biner; yalnız Meksika'da farklı olanı ezer: estacionar/carro/celular/lugar sözlüğü, "Ajustes"→"Configuración", añadir→agregar, coste→costo, cartel→letrero ve bileşik geçmiş yerine geçmiş zaman.
export const esMX: Partial<Record<CopyKey, string>> = {
  onbTitle1: 'ESTACIONA',
  onbBody1: 'Un toque marca dónde dejaste el carro. Nivel, foto y nota son opcionales — agrégalos solo si el estacionamiento es confuso.',
  onbBody2: 'Ingresa la tarifa una vez y ParkIQ cuenta lo que falta para el siguiente tramo. Si sales antes del salto, la diferencia se queda en tu bolsillo.',
  onbBody3: 'La brújula y el mapa te llevan de vuelta. Bajo tierra, donde el GPS se rinde, entran la foto y el nivel que guardaste.',
  iParked: 'Me estacioné',
  foundIt: 'Lo encontré',
  arInitializing: 'Mueve el celular despacio para iniciar el seguimiento',
  findMyCar: 'Buscar mi carro',
  filterCovered: 'Techado',
  noTariffYet: 'Aún no hay tarifa guardada para este lugar',
  laParked: 'ESTACIONADO',
  wParkTitle: 'Estacionar',
  wParkHint: 'Toca para guardar tu lugar',
  poiParking: 'Estacionamiento',
  shareMessage: 'El carro está aquí.',
  parkedStamp: 'ESTACIONADO.',
  parkedAt: 'Estacionado a las {time}',
  parkedDurationStamp: 'ESTACIONADO {duration}.',
  stillParked: '¿Sigues estacionado en {place}?',
  addTariff: 'Agrega la tarifa para ver el costo',
  pickOnMapHint: 'Mueve el mapa hasta que el pin quede sobre tu carro',
  usePin: 'Usar este lugar',
  floor: 'Nivel',
  cumulativeHint: 'Escribe el total que pagarías al salir dentro de ese tiempo, no el monto adicional.',
  addTier: 'Agregar tramo',
  scanPro: 'Escanear letreros es de Pro',
  osmAttribution: 'Datos de estacionamiento © colaboradores de OpenStreetMap',
  scheduleWeekday: 'Tarifa de día hábil aplicada',
  scheduleChanged: 'La tarifa cambió — este letrero cobra distinto a esta hora. Vuelve a escanear o edita la tarifa.',
  scanBoard: 'Escanear letrero',
  scanning: 'Leyendo el letrero',
  scanNotDetected: 'No se pudo leer el letrero — acércate, evita los reflejos o escríbela a mano',
  scanPartial: 'Algunas líneas no se leyeron — revisa los tramos de abajo',
  scanFailed: 'Escaneo fallido — escríbela a mano',
  amountPerHour: 'Monto por hora',
  flatAmount: 'Monto total',
  parkedWord: 'ESTACIONADO',
  costNow: 'Costo ahora',
  indoorHint: 'Aquí la señal es débil — usa la foto y el nivel.',
  noSpotDetails: 'Sin foto ni nivel para este lugar.',
  photoAdded: 'Agregada',
  addPhoto: 'Agregar foto',
  notePlaceholder: 'Junto al elevador',
  parkedWhen: 'Me estacioné',
  notParkedYet: '¿No te estacionaste aquí? Borra el registro',
  anchorAfterPark: 'Después de estacionar',
  reminderNeedsTariff: 'Esto necesita una tarifa — agrégala primero',
  simpleReminder: 'Llevas {duration} estacionado.',
  weakGpsNudge: 'Señal débil — agrega una foto o el nivel',
  notificationsOff: 'Notificaciones desactivadas · Actívalas en Configuración',
  cameraOff: 'Cámara desactivada · Actívala en Configuración',
  firstParkHere: 'Tu primera sesión aparecerá aquí.',
  proHeadline: 'PRO DETECTA QUE TE ESTACIONAS',
  proFeatureAuto: 'Pregunta si iniciar el contador cuando CarPlay se desconecta',
  proFeatureScan: 'Escanea los letreros de tarifas con la cámara',
  autoRenewNotice: 'Las suscripciones se renuevan automáticamente hasta que las canceles. El cargo se hace en tu Apple ID al confirmar y en cada renovación. Puedes gestionarla o cancelarla en Configuración.',
  proFeatureFind: 'Brújula y AR para volver al carro',
  proFeatureFilter: 'Filtra estacionamientos por recarga, techado y distancia',
  plansError: 'No se pudieron cargar los planes. Revisa tu conexión.',
  noPurchases: 'No se encontraron compras.',
  purchaseFailed: 'La compra no se completó.',
  settings: 'Configuración',
  autoDetectHint: 'Guarda tu lugar cuando se desconecta el Bluetooth del carro o CarPlay.',
  autoParkedAsk: '¿Te acabas de estacionar? Toca para iniciar el contador aquí.',
  autoParkedNotice: 'Se guardó tu lugar. ¿Iniciamos el contador?',
  goProUpsell: 'Escanea letreros, vuelve guiado al carro, filtra estacionamientos',
  purchaseDoneBody: 'Escaneo de letreros, brújula y AR, detección automática y filtros de estacionamiento ya están activos.',
  beyondSchedule: 'Pasaste lo que cubre el letrero — el monto ya no es seguro',
  calibrateCompass: 'La brújula está descalibrada — mueve el celular dibujando un 8',
  poiError: 'No se pudieron cargar los estacionamientos cercanos — revisa tu conexión',
  locationMissing: 'No se pudo obtener la ubicación — márcala en el mapa',
  deleteSessionTitle: '¿Borrar este registro?',
  compassLocked: 'La brújula y el AR son de Pro. Tu lugar, foto y nota siguen siendo gratis.',
  stillParkedShort: '¿Sigues estacionado? Esta sesión empezó ayer.',
};
