import type { CopyKey } from './en';

// FR-FR: hitap "vous"; otopark yeri "parking", eylem "stationnement"; Apple Maps Fransızca'da "Plans".
export const frFR: Record<CopyKey, string> = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: 'GAREZ-VOUS',
  onbBody1: 'Un appui suffit pour marquer où vous avez laissé la voiture. Niveau, photo et note restent facultatifs — à remplir seulement quand le parking est compliqué.',
  onbTitle2: 'ÉCONOMISEZ',
  onbBody2: 'Saisissez le tarif une fois : ParkIQ décompte le temps qui reste avant le palier suivant. Sortez avant qu’il change et la différence reste dans votre poche.',
  onbTitle3: 'RETROUVEZ-LA',
  onbBody3: 'La boussole et la carte vous ramènent. En sous-sol, là où le GPS lâche, la photo et le niveau enregistrés prennent le relais.',
  skip: 'Passer',
  enableLocation: 'Continuer',
  notNow: 'Pas maintenant',
  iParked: 'Je me gare',
  foundIt: 'Je l’ai trouvée',
  arMode: 'Vue caméra',
  arHint: 'Suivez le faisceau',
  arInitializing: 'Bougez lentement le téléphone pour lancer le suivi',
  arFailed: 'Échec du suivi caméra — utilisez la boussole',
  findMyCar: 'Retrouver ma voiture',
  shareLocation: 'Partager la position',
  endSession: 'Terminer',
  done: 'OK',
  keep: 'Continuer',
  undo: 'Annuler',
  shareCard: 'Partager en image',
  // Keşif
  whereTo: 'Où allez-vous ?',
  noNearbyForFilter: 'Aucun résultat à proximité avec ce filtre',
  filters: 'Filtres',
  searchRadius: 'Rayon',
  results: '{count} à proximité',
  filterAll: 'Tous',
  filterCharging: 'Recharge',
  filterCovered: 'Couvert',
  myLocation: 'Ma position',
  noResults: 'Aucun lieu trouvé.',
  photoAdded: 'Ajoutée',
  close: 'Fermer',
  noTariffYet: 'Aucun tarif enregistré pour ce lieu',
  editTariff: 'Modifier le tarif',
  preferences: 'Préférences',
  laParked: 'GARÉE',
  laNextTier: 'PALIER SUIVANT {price}',
  laNowNext: 'Actuel {now} · Ensuite {next}',
  wNoSession: 'Aucun stationnement en cours',
  wSavedLabel: 'ÉCONOMISÉ CE MOIS-CI',
  wParkTitle: 'Se garer',
  wParkHint: 'Touchez pour enregistrer votre place',
  poiParking: 'Parking',
  poiCharging: 'Borne de recharge',
  directions: 'Itinéraire',
  minWalk: '{minutes} min à pied',
  // Oturum
  shareMessage: 'La voiture est ici.',
  parkedStamp: 'GARÉE.',
  parkedAt: 'Garée à {time}',
  savedStamp: '{amount} DANS LA POCHE.',
  parkedDurationStamp: 'GARÉE {duration}.',
  stillParked: 'Toujours garé à {place} ?',
  addTariff: 'Ajoutez le tarif pour voir le montant',
  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: 'Sortez dans les {minutes} min : {now} au lieu de {next}',
  exitNowPay: 'Sortez maintenant : {now} au lieu de {next}',
  nowNext: 'Actuel {now} · Ensuite {next}',
  nextTier: 'Palier suivant',
  tierAlert: 'Palier {tier} dans {minutes} min. Maintenant {now}, après {next}.',
  flatRate: 'Forfait {amount}',
  perHour: '{amount} / heure',
  lastTimeTariff: 'La dernière fois : {summary} — l’utiliser ?',
  // Park sheet'i + tarife formu (§7.3–7.4)
  detailsOptional: 'Détails facultatifs',
  pickOnMap: 'Choisir sur la carte',
  pickOnMapHint: 'Déplacez la carte pour poser le repère sur votre voiture',
  pickAreaHint: 'Déplacez la carte pour choisir la zone de recherche',
  useThisArea: 'Chercher ici',
  pickArea: 'Choisir sur la carte',
  usePin: 'Utiliser ce point',
  parkLocation: 'Position',
  useMyLocation: 'Utiliser ma position actuelle',
  floor: 'Niveau',
  floorPlaceholder: 'Niveau −2, C',
  note: 'Note',
  notePlaceholder: 'Près de l’ascenseur',
  tariff: 'Tarif',
  tariffNone: 'Aucun',
  tariffHourly: 'Horaire',
  tariffFlat: 'Forfait',
  tariffTiered: 'Paliers',
  untilDuration: 'Durée',
  unitMinShort: 'min',
  unitHourShort: 'h',
  unitToggle: 'Changer d’unité',
  totalSoFar: 'Total à payer',
  addTier: 'Ajouter un palier',
  cumulativeHint: 'Saisissez le total à payer si vous sortez dans ce délai, pas le supplément.',
  scanPro: 'Scan du panneau : réservé à Pro',
  osmAttribution: 'Données parking © les contributeurs OpenStreetMap',
  scheduleWeekday: 'Tarif semaine appliqué',
  scheduleWeekend: 'Tarif week-end appliqué',
  scheduleDay: 'Tarif jour appliqué',
  scheduleNight: 'Tarif nuit appliqué',
  scheduleChanged: 'Le tarif a changé — ce panneau applique un autre prix à cette heure. Scannez à nouveau ou modifiez le tarif.',
  scanBoard: 'Scanner le panneau',
  scanning: 'Lecture du panneau',
  scanNotDetected: 'Panneau illisible — rapprochez-vous, évitez les reflets ou saisissez à la main',
  scanPartial: 'Certaines lignes n’ont pas été lues — vérifiez les paliers ci-dessous',
  scanFailed: 'Échec du scan — saisissez à la main',
  scanUnavailable: 'Le scan demande la version complète de l’app',
  amountPerHour: 'Montant par heure',
  flatAmount: 'Montant total',
  endQuestion: 'Terminer ce stationnement ?',
  savedWord: 'ÉCONOMISÉ',
  parkedWord: 'GARÉE',
  duration: 'Durée',
  paid: 'Payé',
  avoided: 'Économisé',
  costNow: 'Coût actuel',
  locating: 'Recherche de la position',
  use: 'Utiliser',
  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: 'Vous y êtes presque — regardez autour de vous',
  walkToCar: 'Marchez dans le sens de la flèche',
  indoorHint: 'Signal faible ici — servez-vous de la photo et du niveau.',
  noSpotDetails: 'Ni photo ni niveau enregistrés pour cette place.',
  photo: 'Photo',
  addPhoto: 'Ajouter une photo',
  retakePhoto: 'Reprendre',
  removePhoto: 'Retirer',
  parkedWhen: 'Arrivée',
  justNow: 'À l’instant',
  minutesAgo: 'il y a {minutes} min',
  custom: 'Personnalisé',
  customMinutes: 'Minutes',
  notParkedYet: 'Pas garé ici ? Supprimez ce stationnement',
  remindMe: 'Me rappeler',
  reminderAnchor: 'Point de départ',
  anchorAfterPark: 'Après le stationnement',
  anchorFirstTier: 'Avant la première hausse',
  anchorEveryTier: 'Avant chaque hausse',
  reminderAfterHow: 'Combien de temps après',
  reminderBeforeHow: 'Combien de temps avant',
  reminderKind: 'Type d’alerte',
  kindNotification: 'Notification',
  kindAlarm: 'Son',
  kindBoth: 'Les deux',
  kindHint: 'Le son passe au travers des modes de concentration. Une vraie alarme qui sonne en silencieux demande iOS 26.',
  reminderNeedsTariff: 'Il faut un tarif pour ça — ajoutez-en un d’abord',
  reminderOff: 'Désactivé',
  hoursShort: '{hours} h',
  simpleReminder: 'Vous êtes garé depuis {duration}.',
  // Durum satırları (§5.11)
  offlineTimer: 'Hors ligne — le compteur tourne toujours',
  weakGpsNudge: 'Signal faible — ajoutez une photo ou le niveau',
  locationOff: 'Localisation désactivée · Activer',
  notificationsOff: 'Notifications désactivées · Activer dans Réglages',
  cameraOff: 'Appareil photo désactivé · Activer dans Réglages',
  // Boş durumlar (§5.12)
  noSessions: 'Aucun stationnement pour l’instant.',
  firstParkHere: 'Votre premier stationnement apparaîtra ici.',
  noActiveSession: 'Aucun stationnement en cours',
  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'PRO DÉTECTE LE STATIONNEMENT',
  proBody: 'Vous n’y pensez jamais.',
  proFeatureAuto: 'Propose de lancer le compteur quand CarPlay se déconnecte',
  proFeatureScan: 'Scannez les panneaux tarifaires à l’appareil photo',
  autoRenewNotice: 'L’abonnement se renouvelle automatiquement jusqu’à son annulation. Le montant est débité de votre Apple ID à la confirmation puis à chaque renouvellement. Gérez ou annulez dans Réglages.',
  proFeatureFind: 'Boussole et guidage AR jusqu’à la voiture',
  proFeatureFilter: 'Filtrez les parkings par borne, couvert et distance',
  planPerMonth: '{price} / mois',
  planSave: 'ÉCONOMISEZ {percent} %',
  terms: 'Conditions (EULA)',
  planYearly: 'Annuel',
  planMonthly: 'Mensuel',
  planLifetime: 'À vie',
  continueYearly: 'Continuer — {price}/an',
  continueMonthly: 'Continuer — {price}/mois',
  continueLifetime: 'Continuer — {price} une fois',
  freeThen: '{intro}, puis {price}',
  demoPlans: 'Tarifs de démo — build de développement uniquement.',
  plansError: 'Impossible de charger les offres. Vérifiez votre connexion.',
  retry: 'Réessayer',
  restore: 'Restaurer les achats',
  privacy: 'Confidentialité',
  restored: 'Restauré.',
  noPurchases: 'Aucun achat trouvé.',
  purchaseFailed: 'L’achat a échoué.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: 'Actif',
  // Ayarlar (§7.9)
  updateRequiredTitle: 'MISE À JOUR REQUISE',
  updateRequiredBody: 'Cette version ne calcule plus vos montants de stationnement correctement. Mettez à jour pour continuer.',
  updateNow: 'Mettre à jour',
  settings: 'Réglages',
  appearance: 'Apparence',
  themeLight: 'Clair',
  themeDark: 'Sombre',
  themeSystem: 'Système',
  language: 'Langue',
  currency: 'Devise',
  alertThreshold: 'Me prévenir avant',
  minutesShort: '{minutes} min',
  autoDetect: 'Détection auto',
  autoDetectHint: 'Enregistre votre place quand le Bluetooth de la voiture ou CarPlay se déconnecte.',
  autoDetectPro: 'Détection auto : réservée à Pro',
  autoParkedAsk: 'Vous venez de vous garer ? Touchez pour lancer le compteur ici.',
  autoParkedNotice: 'Votre place est enregistrée. Lancer le compteur ?',
  permissions: 'Autorisations',
  locationGranted: 'Localisation activée',
  notificationsGranted: 'Notifications activées',
  data: 'Données',
  deleteAllData: 'Supprimer tous les stationnements',
  deleteAllConfirm: 'Supprimer tous les stationnements ? Action irréversible.',
  delete: 'Supprimer',
  cancel: 'Annuler',
  developer: 'Développeur',
  devPremium: 'Premium activé',
  devPremiumHint: 'Uniquement en build de développement. Désactivez pour voir le paywall et les états verrouillés.',
  devResetOnboarding: 'Revoir l’introduction',
  manageSubscription: 'Gérer l’abonnement',
  exportData: 'Exporter mes données',
  support: 'Assistance',
  rateAskTitle: 'PARKIQ VOUS REND SERVICE ?',
  rateAskBody: 'Une note aide d’autres conducteurs à le trouver. Si quelque chose cloche, dites-le-nous.',
  rateYes: 'Oui, mettre une note',
  rateNo: 'Pas vraiment',
  later: 'Plus tard',
  goProUpsell: 'Scannez les panneaux, retrouvez la voiture, filtrez les parkings',
  rateUs: 'Noter ParkIQ',
  about: 'À propos',
  version: 'Version',
  // Geçmiş (§7.8)
  lockedSessions: '{count} stationnements en plus avec Pro',
  history: 'Historique',
  shareMonth: 'Partager le mois',
  monthlySaved: 'Économies par mois',
  totalSaved: 'Économisé',
  sessionsCount: 'Stationnements',
  avgDuration: 'Temps moyen',
  sessionDetail: 'Stationnement',
  openInMaps: 'Ouvrir dans Plans',
  fixLocation: 'Corriger la position',
  purchaseDoneTitle: 'Vous êtes Pro.',
  purchaseDoneBody: 'Scan des panneaux, boussole et guidage AR, détection auto et filtres de parking sont actifs.',
  restoredTitle: 'Restauré.',
  restoredBody: 'Votre accès Pro est de retour sur cet iPhone.',
  noPurchasesBody: 'Rien à restaurer sur cet Apple Account. Si vous avez payé avec un autre, connectez-vous avec celui-là et réessayez.',
  restoring: 'Restauration…',
  introFree: 'Gratuit pendant {period}',
  introDiscounted: '{price} pendant {period}',
  periodDay: '{count} jour',
  periodWeek: '{count} semaine',
  periodMonth: '{count} mois',
  periodYear: '{count} an',
  lifetimeNote: 'Un paiement, sans abonnement',
  savedSoFar: 'ParkIQ vous a fait économiser {amount} jusqu’ici',
  dailyMax: 'Plafond journalier (facultatif)',
  beyondSchedule: 'Au-delà de ce que le panneau couvre — le montant n’est plus sûr',
  clockFormat: 'Format de l’heure',
  clock12: '1:04 PM',
  clock24: '13:04',
  units: 'Distance',
  unitsMetric: 'Mètres',
  unitsImperial: 'Pieds et miles',
  followDevice: 'Suivre l’appareil',
  headingUnavailable: 'Pas de direction boussole — la distance reste juste',
  calibrateCompass: 'Boussole déréglée — dessinez un 8 avec le téléphone',
  poiError: 'Impossible de charger les parkings à proximité — vérifiez votre connexion',
  locationMissing: 'Position introuvable — placez-la sur la carte',
  locationRough: 'Enregistré à ±{meters} près — corrigez sur la carte',
  deleteSessionTitle: 'Supprimer ce stationnement ?',
  deleteSessionBody: 'La fiche et sa photo seront supprimées. Action irréversible.',
  compassLocked: 'La boussole et l’AR sont dans Pro. Votre place, votre photo et votre note restent gratuites.',
  back: 'Retour',
  today: 'Aujourd’hui',
  yesterday: 'Hier',
  stillParkedShort: 'Toujours garé ? Ce stationnement a commencé hier.',
};
