import type { CopyKey } from './en';

// IT karşılıklar. "tu" hitabı; araba "auto" (dişil), park oturumu "sosta",
// fiyat kademesi "scatto", tarife panosu "cartello"; kesme işareti tipografik ’.
export const it: Record<CopyKey, string> = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: 'PARCHEGGIA',
  onbBody1: 'Un tocco segna dove hai lasciato l’auto. Piano, foto e nota sono facoltativi — aggiungili solo se il parcheggio è confuso.',
  onbTitle2: 'RISPARMIA',
  onbBody2: 'Inserisci la tariffa una volta e ParkIQ conta quanto manca allo scatto successivo. Esci prima dello scatto e la differenza resta in tasca.',
  onbTitle3: 'TROVALA',
  onbBody3: 'Bussola e mappa ti riportano indietro. Nei sotterranei, dove il GPS si arrende, subentrano la foto e il piano che hai salvato.',
  skip: 'Salta',
  enableLocation: 'Continua',
  notNow: 'Non ora',
  iParked: 'Ho parcheggiato',
  foundIt: 'Trovata',
  arMode: 'Vista fotocamera',
  arHint: 'Segui il raggio',
  arInitializing: 'Muovi il telefono lentamente per avviare il tracciamento',
  arFailed: 'Tracciamento fallito — usa la bussola',
  findMyCar: 'Trova l’auto',
  shareLocation: 'Condividi posizione',
  endSession: 'Termina',
  done: 'Fatto',
  keep: 'Prosegui',
  undo: 'Annulla',
  shareCard: 'Condividi scheda',
  // Keşif
  whereTo: 'Dove vai?',
  noNearbyForFilter: 'Nessun risultato vicino con questo filtro',
  filters: 'Filtri',
  searchRadius: 'Entro',
  results: '{count} qui vicino',
  filterAll: 'Tutti',
  filterCharging: 'Ricarica',
  filterCovered: 'Coperto',
  myLocation: 'La mia posizione',
  noResults: 'Nessun luogo trovato.',
  photoAdded: 'Aggiunta',
  close: 'Chiudi',
  noTariffYet: 'Nessuna tariffa salvata per questo posto',
  editTariff: 'Modifica tariffa',
  preferences: 'Preferenze',
  laParked: 'PARCHEGGIATO',
  laNextTier: 'PROSSIMO SCATTO {price}',
  laNowNext: 'Ora {now} · Poi {next}',
  wNoSession: 'Nessuna sosta attiva',
  wSavedLabel: 'RISPARMIO DEL MESE',
  wParkTitle: 'Parcheggia',
  wParkHint: 'Tocca per salvare il posto',
  poiParking: 'Parcheggio',
  poiCharging: 'Colonnina di ricarica',
  directions: 'Indicazioni',
  minWalk: '{minutes} min a piedi',
  // Oturum
  shareMessage: 'L’auto è qui.',
  parkedStamp: 'PARCHEGGIATO.',
  parkedAt: 'In sosta dalle {time}',
  savedStamp: '{amount} IN TASCA.',
  parkedDurationStamp: 'PARCHEGGIATO {duration}.',
  stillParked: 'Ancora in sosta a {place}?',
  addTariff: 'Aggiungi la tariffa per vedere il costo',
  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: 'Esci entro {minutes} min e paghi {now} invece di {next}',
  exitNowPay: 'Esci ora e paghi {now} invece di {next}',
  nowNext: 'Ora {now} · Poi {next}',
  nextTier: 'Prossimo scatto',
  tierAlert: 'Scatto {tier} tra {minutes} min. Ora {now}, dopo {next}.',
  flatRate: '{amount} fisso',
  perHour: '{amount} / ora',
  lastTimeTariff: 'L’ultima volta: {summary} — la usi?',
  // Park sheet'i + tarife formu (§7.3–7.4)
  detailsOptional: 'Dettagli facoltativi',
  pickOnMap: 'Segna sulla mappa',
  pickOnMapHint: 'Sposta la mappa finché il pin è sull’auto',
  pickAreaHint: 'Sposta la mappa per scegliere dove cercare',
  useThisArea: 'Cerca qui',
  pickArea: 'Scegli sulla mappa',
  usePin: 'Usa questo punto',
  parkLocation: 'Posizione',
  useMyLocation: 'Usa la posizione attuale',
  floor: 'Piano',
  floorPlaceholder: '-2, settore C',
  note: 'Nota',
  notePlaceholder: 'Vicino all’ascensore',
  tariff: 'Tariffa',
  tariffNone: 'Nessuna',
  tariffHourly: 'Oraria',
  tariffFlat: 'Fissa',
  tariffTiered: 'A scatti',
  untilDuration: 'Durata',
  unitMinShort: 'min',
  unitHourShort: 'h',
  unitToggle: 'Cambia unità',
  totalSoFar: 'Totale da pagare',
  addTier: 'Aggiungi scatto',
  cumulativeHint: 'Inserisci il totale che paghi uscendo entro quel tempo, non il supplemento.',
  scanPro: 'Scansione del cartello in Pro',
  osmAttribution: 'Dati parcheggi © contributori OpenStreetMap',
  scheduleWeekday: 'Applicata la tariffa feriale',
  scheduleWeekend: 'Applicata la tariffa del weekend',
  scheduleDay: 'Applicata la tariffa diurna',
  scheduleNight: 'Applicata la tariffa notturna',
  scheduleChanged: 'La tariffa è cambiata — a quest’ora il cartello applica prezzi diversi. Scansiona di nuovo o modifica la tariffa.',
  scanBoard: 'Scansiona il cartello',
  scanning: 'Lettura del cartello',
  scanNotDetected: 'Cartello illeggibile — avvicinati, evita i riflessi o inseriscila a mano',
  scanPartial: 'Alcune righe non sono state lette — controlla gli scatti qui sotto',
  scanFailed: 'Scansione fallita — inseriscila a mano',
  scanUnavailable: 'La scansione richiede la versione completa dell’app',
  amountPerHour: 'Importo orario',
  flatAmount: 'Importo totale',
  endQuestion: 'Terminare la sosta?',
  savedWord: 'IN TASCA',
  parkedWord: 'PARCHEGGIATO',
  duration: 'Durata',
  paid: 'Pagato',
  avoided: 'Risparmiato',
  costNow: 'Costo attuale',
  locating: 'Ricerca posizione',
  use: 'Usa',
  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: 'Sei vicino — guardati intorno',
  walkToCar: 'Cammina verso la freccia',
  indoorHint: 'Qui il segnale è debole — usa la foto e il piano.',
  noSpotDetails: 'Nessuna foto né piano per questo posto.',
  photo: 'Foto',
  addPhoto: 'Aggiungi foto',
  retakePhoto: 'Scatta di nuovo',
  removePhoto: 'Rimuovi',
  parkedWhen: 'Ho parcheggiato',
  justNow: 'Adesso',
  minutesAgo: '{minutes} min fa',
  custom: 'Altro',
  customMinutes: 'Minuti',
  notParkedYet: 'Non hai parcheggiato qui? Elimina la sosta',
  remindMe: 'Promemoria',
  reminderAnchor: 'Rispetto a',
  anchorAfterPark: 'Dopo il parcheggio',
  anchorFirstTier: 'Prima del primo aumento',
  anchorEveryTier: 'Prima di ogni aumento',
  reminderAfterHow: 'Quanto dopo',
  reminderBeforeHow: 'Quanto prima',
  reminderKind: 'Come avvisarti',
  kindNotification: 'Notifica',
  kindAlarm: 'Suono',
  kindBoth: 'Entrambi',
  kindHint: 'Il suono passa anche in Full Immersion. Una sveglia che suona in silenzioso richiede iOS 26.',
  reminderNeedsTariff: 'Serve una tariffa — aggiungila prima',
  reminderOff: 'Disattivo',
  hoursShort: '{hours} h',
  simpleReminder: 'Sei in sosta da {duration}.',
  // Durum satırları (§5.11)
  offlineTimer: 'Offline — il timer continua',
  weakGpsNudge: 'Segnale debole — aggiungi una foto o il piano',
  locationOff: 'Posizione disattivata · Attiva',
  notificationsOff: 'Notifiche disattivate · Attiva in Impostazioni',
  cameraOff: 'Fotocamera disattivata · Attiva in Impostazioni',
  // Boş durumlar (§5.12)
  noSessions: 'Ancora nessuna sosta.',
  firstParkHere: 'Il primo parcheggio comparirà qui.',
  noActiveSession: 'Nessuna sosta attiva',
  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'PRO SE NE ACCORGE DA SOLO',
  proBody: 'Tu non ci pensi.',
  proFeatureAuto: 'Chiede di avviare il timer quando CarPlay si scollega',
  proFeatureScan: 'Scansiona i cartelli tariffari con la fotocamera',
  autoRenewNotice: 'L’abbonamento si rinnova automaticamente finché non lo annulli. L’addebito avviene sul tuo Apple ID alla conferma e a ogni rinnovo. Puoi gestirlo o annullarlo in Impostazioni.',
  proFeatureFind: 'Ritorno all’auto con bussola e AR',
  proFeatureFilter: 'Filtra i parcheggi per ricarica, copertura e distanza',
  planPerMonth: '{price} / mese',
  planSave: 'RISPARMI {percent}%',
  terms: 'Condizioni (EULA)',
  planYearly: 'Annuale',
  planMonthly: 'Mensile',
  planLifetime: 'Per sempre',
  continueYearly: 'Continua — {price}/anno',
  continueMonthly: 'Continua — {price}/mese',
  continueLifetime: 'Continua — {price} una volta',
  freeThen: '{intro}, poi {price}',
  demoPlans: 'Prezzi di prova — solo build di debug.',
  plansError: 'Piani non caricati. Controlla la connessione.',
  retry: 'Riprova',
  restore: 'Ripristina acquisti',
  privacy: 'Privacy',
  restored: 'Ripristinato.',
  noPurchases: 'Nessun acquisto trovato.',
  purchaseFailed: 'Acquisto non riuscito.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: 'Attivo',
  // Ayarlar (§7.9)
  updateRequiredTitle: 'AGGIORNAMENTO NECESSARIO',
  updateRequiredBody: 'Questa versione non calcola più i costi in modo corretto. Aggiorna per continuare.',
  updateNow: 'Aggiorna',
  settings: 'Impostazioni',
  appearance: 'Aspetto',
  themeLight: 'Chiaro',
  themeDark: 'Scuro',
  themeSystem: 'Sistema',
  language: 'Lingua',
  currency: 'Valuta',
  alertThreshold: 'Preavviso',
  minutesShort: '{minutes} min',
  autoDetect: 'Rilevamento automatico',
  autoDetectHint: 'Salva il posto quando il Bluetooth dell’auto o CarPlay si scollega.',
  autoDetectPro: 'Rilevamento automatico in Pro',
  autoParkedAsk: 'Hai appena parcheggiato? Tocca per avviare il timer qui.',
  autoParkedNotice: 'Posto salvato. Avvio il timer?',
  permissions: 'Autorizzazioni',
  locationGranted: 'Posizione attiva',
  notificationsGranted: 'Notifiche attive',
  data: 'Dati',
  deleteAllData: 'Elimina tutte le soste',
  deleteAllConfirm: 'Eliminare tutte le soste? L’operazione è irreversibile.',
  delete: 'Elimina',
  cancel: 'Annulla',
  developer: 'Sviluppatore',
  devPremium: 'Premium attivo',
  devPremiumHint: 'Solo build di debug. Disattiva per vedere il paywall e gli stati bloccati.',
  devResetOnboarding: 'Mostra di nuovo l’onboarding',
  manageSubscription: 'Gestisci abbonamento',
  exportData: 'Esporta i miei dati',
  support: 'Assistenza',
  rateAskTitle: 'PARKIQ FA IL SUO LAVORO?',
  rateAskBody: 'Una valutazione aiuta altri automobilisti a trovarla. Se qualcosa non va, scrivici.',
  rateYes: 'Sì, la valuto',
  rateNo: 'Non proprio',
  later: 'Più tardi',
  goProUpsell: 'Scansiona i cartelli, torna all’auto, filtra i parcheggi',
  rateUs: 'Valuta ParkIQ',
  about: 'Info',
  version: 'Versione',
  // Geçmiş (§7.8)
  lockedSessions: 'Altre {count} soste in Pro',
  history: 'Cronologia',
  shareMonth: 'Condividi il mese',
  monthlySaved: 'Risparmio mensile',
  totalSaved: 'Risparmio',
  sessionsCount: 'Soste',
  avgDuration: 'Media',
  sessionDetail: 'Sosta',
  openInMaps: 'Apri in Mappe',
  fixLocation: 'Correggi la posizione',
  purchaseDoneTitle: 'Ora sei Pro.',
  purchaseDoneBody: 'Scansione dei cartelli, bussola e AR, rilevamento automatico e filtri parcheggio sono attivi.',
  restoredTitle: 'Ripristinato.',
  restoredBody: 'Il tuo accesso Pro è di nuovo attivo su questo iPhone.',
  noPurchasesBody: 'Niente da ripristinare su questo Apple Account. Se hai pagato con un altro, accedi con quello e riprova.',
  restoring: 'Ripristino…',
  introFree: '{period} gratis',
  introDiscounted: '{period} a {price}',
  periodDay: '{count} giorno',
  periodWeek: '{count} settimana',
  periodMonth: '{count} mese',
  periodYear: '{count} anno',
  lifetimeNote: 'Un pagamento, nessun abbonamento',
  savedSoFar: 'Finora ParkIQ ti ha fatto risparmiare {amount}',
  dailyMax: 'Massimo giornaliero (facoltativo)',
  beyondSchedule: 'Oltre quello che indica il cartello — l’importo non è più certo',
  clockFormat: 'Formato ora',
  clock12: '1:04 PM',
  clock24: '13:04',
  units: 'Distanza',
  unitsMetric: 'Metri',
  unitsImperial: 'Piedi e miglia',
  followDevice: 'Segui il dispositivo',
  headingUnavailable: 'Nessuna direzione dalla bussola — la distanza è comunque corretta',
  calibrateCompass: 'Bussola da calibrare — muovi il telefono a forma di 8',
  poiError: 'Parcheggi vicini non caricati — controlla la connessione',
  locationMissing: 'Posizione non rilevata — indicala sulla mappa',
  locationRough: 'Salvata con precisione ±{meters} — correggila sulla mappa',
  deleteSessionTitle: 'Eliminare questa sosta?',
  deleteSessionBody: 'La sosta e la sua foto vengono eliminate. L’operazione è irreversibile.',
  compassLocked: 'Bussola e AR sono in Pro. Posto, foto e nota restano gratis.',
  back: 'Indietro',
  today: 'Oggi',
  yesterday: 'Ieri',
  stillParkedShort: 'Ancora in sosta? Questa sosta è iniziata ieri.',
};
