import type { CopyKey } from './en';

// JA karşılıklar. Kibar ama kısa です/ます; ünlem yok, damga noktası Japonca 「。」 olarak korundu.
export const ja: Record<CopyKey, string> = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: '駐車する',
  onbBody1: 'ワンタップで車をとめた場所を記録します。階数・写真・メモは任意です。わかりにくい駐車場のときだけ足してください。',
  onbTitle2: '節約する',
  onbBody2: '料金を一度入力すれば、次の値上がりまでの残り時間をParkIQが数えます。上がる前に出れば、その差額は手元に残ります。',
  onbTitle3: '見つける',
  onbBody3: 'コンパスと地図が車まで案内します。GPSが届かない地下では、保存した写真と階数が頼りになります。',
  skip: 'スキップ',
  enableLocation: '続ける',
  notNow: 'あとで',
  iParked: 'ここにとめた',
  foundIt: '見つけた',
  arMode: 'カメラ表示',
  arHint: '光の線をたどる',
  arInitializing: 'スマホをゆっくり動かすと認識が始まります',
  arFailed: 'カメラで認識できません — コンパスを使ってください',
  findMyCar: '車を探す',
  shareLocation: '位置を共有',
  endSession: '終了',
  done: '完了',
  keep: '続ける',
  undo: '取り消す',
  shareCard: 'カードを共有',
  // Keşif
  whereTo: 'どこへ？',
  noNearbyForFilter: 'この条件に合う駐車場は近くにありません',
  filters: '絞り込み',
  searchRadius: '範囲',
  results: '近くに{count}件',
  filterAll: 'すべて',
  filterCharging: '充電',
  filterCovered: '屋内',
  myLocation: '現在地',
  noResults: '該当する場所がありません。',
  photoAdded: '追加しました',
  close: '閉じる',
  noTariffYet: 'この場所の料金はまだ登録されていません',
  editTariff: '料金を編集',
  preferences: '基本設定',
  laParked: '駐車中',
  laNextTier: '次の料金 {price}',
  laNowNext: '現在 {now} · 次 {next}',
  wNoSession: '駐車中ではありません',
  wSavedLabel: '今月の節約額',
  wParkTitle: '駐車',
  wParkHint: 'タップで位置を保存',
  poiParking: '駐車場',
  poiCharging: '充電スポット',
  directions: '経路',
  minWalk: '徒歩{minutes}分',
  // Oturum
  shareMessage: '車はここです。',
  parkedStamp: '駐車完了。',
  parkedAt: '{time}から駐車中',
  savedStamp: '{amount} 節約。',
  parkedDurationStamp: '{duration} 駐車。',
  stillParked: 'まだ{place}に駐車中ですか？',
  addTariff: '料金を入力すると金額がわかります',
  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: '{minutes}分以内に出れば {next} ではなく {now}',
  exitNowPay: '今出れば {next} ではなく {now}',
  nowNext: '現在 {now} · 次 {next}',
  nextTier: '次の料金',
  tierAlert: 'あと{minutes}分で{tier}段階目。現在 {now}、その後 {next}。',
  flatRate: '一律 {amount}',
  perHour: '{amount} / 時間',
  lastTimeTariff: '前回：{summary} — 使いますか？',
  // Park sheet'i + tarife formu (§7.3–7.4)
  detailsOptional: '詳細は任意',
  pickOnMap: '地図で選ぶ',
  pickOnMapHint: '地図を動かしてピンを車の位置に合わせてください',
  pickAreaHint: '地図を動かして探す場所を決めてください',
  useThisArea: 'ここで検索',
  pickArea: '地図で選ぶ',
  usePin: 'ここにする',
  parkLocation: '位置',
  useMyLocation: '現在地を使う',
  floor: '階',
  floorPlaceholder: 'B2 Cブロック',
  note: 'メモ',
  notePlaceholder: 'エレベーターの近く',
  tariff: '料金',
  tariffNone: 'なし',
  tariffHourly: '時間制',
  tariffFlat: '一律',
  tariffTiered: '段階制',
  untilDuration: '時間',
  unitMinShort: '分',
  unitHourShort: '時間',
  unitToggle: '単位を変更',
  totalSoFar: '支払う合計',
  addTier: '段階を追加',
  cumulativeHint: 'その時間内に出た場合の合計額を入力してください。追加分ではありません。',
  scanPro: '料金表スキャンはProの機能です',
  osmAttribution: '駐車場データ © OpenStreetMap contributors',
  scheduleWeekday: '平日料金を適用',
  scheduleWeekend: '土日料金を適用',
  scheduleDay: '昼間料金を適用',
  scheduleNight: '夜間料金を適用',
  scheduleChanged: '料金が変わりました — この料金表では今の時間帯は別の金額です。もう一度スキャンするか、料金を編集してください。',
  scanBoard: '料金表をスキャン',
  scanning: '料金表を読み取り中',
  scanNotDetected: '料金表を読み取れません — 近づく、反射を避ける、または手で入力してください',
  scanPartial: '一部の行を読み取れません — 下の段階を確認してください',
  scanFailed: 'スキャンできません — 手で入力してください',
  scanUnavailable: 'スキャンは完全版のビルドでのみ使えます',
  amountPerHour: '1時間あたりの金額',
  flatAmount: '合計金額',
  endQuestion: 'この駐車を終了しますか？',
  savedWord: '節約',
  parkedWord: '駐車',
  duration: '駐車時間',
  paid: '支払い',
  avoided: '節約額',
  costNow: '現在の金額',
  locating: '位置を取得中',
  use: '使う',
  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: 'もうすぐです — 周りを見てください',
  walkToCar: '矢印の方向に歩いてください',
  indoorHint: 'ここは電波が弱いです。写真と階のメモを頼りにしてください。',
  noSpotDetails: 'この場所の写真も階のメモもありません。',
  photo: '写真',
  addPhoto: '写真を追加',
  retakePhoto: '撮り直す',
  removePhoto: '削除',
  parkedWhen: '駐車した時刻',
  justNow: 'たった今',
  minutesAgo: '{minutes}分前',
  custom: 'カスタム',
  customMinutes: '分',
  notParkedYet: 'ここではない場合は記録を削除',
  remindMe: 'リマインダー',
  reminderAnchor: '基準',
  anchorAfterPark: '駐車してから',
  anchorFirstTier: '最初の値上がりの前',
  anchorEveryTier: '毎回の値上がりの前',
  reminderAfterHow: 'どれくらい後',
  reminderBeforeHow: 'どれくらい前',
  reminderKind: '知らせ方',
  kindNotification: '通知',
  kindAlarm: '音',
  kindBoth: '両方',
  kindHint: '音は集中モードでも鳴ります。消音中でも鳴る本当のアラームにはiOS 26が必要です。',
  reminderNeedsTariff: 'これには料金が必要です。先に入力してください',
  reminderOff: 'オフ',
  hoursShort: '{hours}時間',
  simpleReminder: '駐車してから{duration}が経ちました。',
  // Durum satırları (§5.11)
  offlineTimer: 'オフライン — 計測は続いています',
  weakGpsNudge: '電波が弱いです — 写真か階のメモを追加',
  locationOff: '位置情報オフ · オンにする',
  notificationsOff: '通知オフ · 設定でオンにする',
  cameraOff: 'カメラオフ · 設定でオンにする',
  // Boş durumlar (§5.12)
  noSessions: 'まだ記録がありません。',
  firstParkHere: '最初の駐車はここに残ります。',
  noActiveSession: '駐車中ではありません',
  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'Proは駐車を自動で見つける',
  proBody: '意識する必要はありません。',
  proFeatureAuto: 'CarPlayが切れると計測開始を確認',
  proFeatureScan: '料金表をカメラでスキャン',
  autoRenewNotice: '購読は解約するまで自動更新されます。料金は購入確定時と毎回の更新時にApple IDへ請求されます。管理と解約は設定から行えます。',
  proFeatureFind: 'コンパスとARで車まで案内',
  proFeatureFilter: '充電・屋内・距離で駐車場を絞り込み',
  planPerMonth: '月 {price}',
  planSave: '{percent}% 節約',
  terms: '利用規約 (EULA)',
  planYearly: '年間',
  planMonthly: '月間',
  planLifetime: '買い切り',
  continueYearly: '続ける — 年 {price}',
  continueMonthly: '続ける — 月 {price}',
  continueLifetime: '続ける — 一括 {price}',
  freeThen: '{intro}、その後 {price}',
  demoPlans: 'サンプル価格 — 開発ビルドのみ。',
  plansError: 'プランを読み込めません。接続を確認してください。',
  retry: '再試行',
  restore: '購入を復元',
  privacy: 'プライバシー',
  restored: '復元しました。',
  noPurchases: '購入履歴が見つかりません。',
  purchaseFailed: '購入できませんでした。',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: '有効',
  // Ayarlar (§7.9)
  updateRequiredTitle: 'アップデートが必要です',
  updateRequiredBody: 'このバージョンでは駐車料金を正しく計算できません。続けるにはアップデートしてください。',
  updateNow: 'アップデート',
  settings: '設定',
  appearance: '外観',
  themeLight: 'ライト',
  themeDark: 'ダーク',
  themeSystem: 'システム',
  language: '言語',
  currency: '通貨',
  alertThreshold: '何分前に知らせる',
  minutesShort: '{minutes}分',
  autoDetect: '自動検出',
  autoDetectHint: '車のBluetoothやCarPlayが切れたときに位置を保存します。',
  autoDetectPro: '自動検出はProの機能です',
  autoParkedAsk: '駐車しましたか？タップするとここで計測を始めます。',
  autoParkedNotice: '駐車位置を保存しました。計測を始めますか？',
  permissions: '権限',
  locationGranted: '位置情報オン',
  notificationsGranted: '通知オン',
  data: 'データ',
  deleteAllData: 'すべての記録を削除',
  deleteAllConfirm: 'すべての記録を削除しますか？元に戻せません。',
  delete: '削除',
  cancel: 'キャンセル',
  developer: '開発者',
  devPremium: 'プレミアム有効',
  devPremiumHint: '開発ビルド専用です。オフにするとペイウォールとロック状態を確認できます。',
  devResetOnboarding: 'オンボーディングを再表示',
  manageSubscription: '購読を管理',
  exportData: 'データを書き出す',
  support: 'サポート',
  rateAskTitle: 'ParkIQは役に立っていますか？',
  rateAskBody: '評価は他のドライバーがこのアプリを見つける助けになります。気になる点があれば、先に教えてください。',
  rateYes: 'はい、評価する',
  rateNo: 'あまり',
  later: 'あとで',
  goProUpsell: '料金表をスキャン、車まで案内、駐車場を絞り込み',
  rateUs: 'ParkIQを評価',
  about: 'このアプリについて',
  version: 'バージョン',
  // Geçmiş (§7.8)
  lockedSessions: 'Proでさらに{count}件',
  history: '履歴',
  shareMonth: '今月を共有',
  monthlySaved: '月ごとの節約額',
  totalSaved: '節約額',
  sessionsCount: '回数',
  avgDuration: '平均時間',
  sessionDetail: '駐車記録',
  openInMaps: 'マップで開く',
  fixLocation: '駐車位置を修正',
  purchaseDoneTitle: 'Proになりました。',
  purchaseDoneBody: '料金表スキャン、コンパスとAR案内、自動検出、駐車場の絞り込みが使えます。',
  restoredTitle: '復元しました。',
  restoredBody: 'このiPhoneでProが再び有効になりました。',
  noPurchasesBody: 'このApple Accountに復元できるものはありません。別のアカウントで購入した場合は、そのアカウントでサインインしてからもう一度お試しください。',
  restoring: '復元中…',
  introFree: '{period}無料',
  introDiscounted: '{period} {price}',
  periodDay: '{count}日間',
  periodWeek: '{count}週間',
  periodMonth: '{count}か月',
  periodYear: '{count}年間',
  lifetimeNote: '一度の支払い、購読なし',
  savedSoFar: 'ParkIQでこれまでに{amount}の節約',
  dailyMax: '1日の上限（任意）',
  beyondSchedule: '料金表の範囲を超えました — 金額はもう確実ではありません',
  clockFormat: '時刻表示',
  clock12: '午後1:04',
  clock24: '13:04',
  units: '距離',
  unitsMetric: 'メートル',
  unitsImperial: 'フィートとマイル',
  followDevice: '現在地に追従',
  headingUnavailable: 'コンパスの方角が出ません — 距離は正しいままです',
  calibrateCompass: 'コンパスがずれています — スマホを8の字に動かしてください',
  poiError: '近くの駐車場を取得できません — 接続を確認してください',
  locationMissing: '位置を取得できません — 地図で指定してください',
  locationRough: '誤差±{meters}で保存しました — 地図で修正してください',
  deleteSessionTitle: 'この駐車記録を削除しますか？',
  deleteSessionBody: '記録と写真が削除されます。元に戻せません。',
  compassLocked: 'コンパスとAR案内はProです。位置、写真、メモは無料のままです。',
  back: '戻る',
  today: '今日',
  yesterday: '昨日',
  stillParkedShort: 'まだ駐車中ですか？この記録は昨日から続いています。',
};
