// KO karşılıklar. Hitap kipi baştan sona nazik 해요체; buton etiketleri isim öbeği tutuldu.
// Damgalarda Korece'de büyük/küçük harf yok — doğal yazıldı, nokta imzası korundu.
import type { CopyKey } from './en';
export const ko: Record<CopyKey, string> = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: '주차',
  onbBody1: '탭 한 번으로 차를 세운 자리를 기록해요. 층, 사진, 메모는 선택이에요 — 주차장이 복잡할 때만 적으세요.',
  onbTitle2: '요금 절약',
  onbBody2: '요금표를 한 번 입력하면 다음 요금 단계까지 남은 시간을 ParkIQ가 세어줘요. 요금이 오르기 전에 나오면 그 차액은 안 내도 돼요.',
  onbTitle3: '차 찾기',
  onbBody3: '나침반과 지도가 차까지 데려다줘요. GPS가 안 잡히는 지하에서는 저장해 둔 사진과 층이 대신해요.',
  skip: '건너뛰기',
  enableLocation: '계속',
  notNow: '나중에',
  iParked: '여기 주차',
  foundIt: '찾았어요',
  arMode: '카메라 보기',
  arHint: '빛줄기를 따라가세요',
  arInitializing: '추적을 시작하려면 폰을 천천히 움직이세요',
  arFailed: '카메라 추적 실패 — 나침반을 쓰세요',
  findMyCar: '내 차 찾기',
  shareLocation: '위치 공유',
  endSession: '종료',
  done: '완료',
  keep: '유지',
  undo: '되돌리기',
  shareCard: '카드 공유',
  // Keşif
  whereTo: '어디로 갈까요?',
  noNearbyForFilter: '이 필터에 맞는 곳이 주변에 없어요',
  filters: '필터',
  searchRadius: '반경',
  results: '주변 {count}곳',
  filterAll: '전체',
  filterCharging: '충전',
  filterCovered: '실내',
  myLocation: '내 위치',
  noResults: '검색 결과가 없어요.',
  photoAdded: '추가됨',
  close: '닫기',
  noTariffYet: '이 자리에 저장된 요금표가 없어요',
  editTariff: '요금표 수정',
  preferences: '환경설정',
  laParked: '주차 중',
  laNextTier: '다음 단계 {price}',
  laNowNext: '지금 {now} · 다음 {next}',
  wNoSession: '진행 중인 주차 없음',
  wSavedLabel: '이번 달 절약',
  wParkTitle: '주차',
  wParkHint: '눌러서 자리 저장',
  poiParking: '주차장',
  poiCharging: '충전소',
  directions: '길찾기',
  minWalk: '도보 {minutes}분',
  // Oturum
  shareMessage: '차는 여기 있어요.',
  parkedStamp: '주차 완료.',
  parkedAt: '{time}부터 주차 중',
  savedStamp: '{amount} 절약.',
  parkedDurationStamp: '{duration} 주차.',
  stillParked: '아직 {place}에 주차 중인가요?',
  addTariff: '요금을 보려면 요금표를 넣으세요',
  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: '{minutes}분 안에 나오면 {next} 대신 {now}',
  exitNowPay: '지금 나오면 {next} 대신 {now}',
  nowNext: '지금 {now} · 다음 {next}',
  nextTier: '다음 단계',
  tierAlert: '{minutes}분 뒤 {tier}단계. 지금 {now}, 이후 {next}.',
  flatRate: '정액 {amount}',
  perHour: '{amount} / 시간',
  lastTimeTariff: '지난번: {summary} — 그대로 쓸까요?',
  // Park sheet'i + tarife formu (§7.3–7.4)
  detailsOptional: '세부 정보는 선택',
  pickOnMap: '지도에서 선택',
  pickOnMapHint: '핀이 차 위에 오도록 지도를 움직이세요',
  pickAreaHint: '검색할 곳으로 지도를 움직이세요',
  useThisArea: '여기서 검색',
  pickArea: '지도에서 지정',
  usePin: '이 자리 사용',
  parkLocation: '위치',
  useMyLocation: '현재 위치 사용',
  floor: '층',
  floorPlaceholder: '지하 2층, C구역',
  note: '메모',
  notePlaceholder: '엘리베이터 옆',
  tariff: '요금표',
  tariffNone: '없음',
  tariffHourly: '시간당',
  tariffFlat: '정액',
  tariffTiered: '단계별',
  untilDuration: '시간',
  unitMinShort: '분',
  unitHourShort: '시간',
  unitToggle: '단위 변경',
  totalSoFar: '낼 금액',
  addTier: '단계 추가',
  cumulativeHint: '그 시간 안에 나올 때 내는 총액을 넣으세요. 추가 금액이 아니에요.',
  scanPro: '요금표 스캔은 Pro',
  osmAttribution: '주차장 데이터 © OpenStreetMap 기여자',
  scheduleWeekday: '평일 요금 적용',
  scheduleWeekend: '주말 요금 적용',
  scheduleDay: '주간 요금 적용',
  scheduleNight: '야간 요금 적용',
  scheduleChanged: '요금이 바뀌었어요 — 이 요금표는 지금 시간대를 다르게 계산해요. 다시 스캔하거나 요금표를 고치세요.',
  scanBoard: '요금표 스캔',
  scanning: '요금표 읽는 중',
  scanNotDetected: '요금표를 못 읽었어요 — 더 가까이서, 빛 반사를 피하거나 직접 입력하세요',
  scanPartial: '일부 줄을 못 읽었어요 — 아래 단계를 확인하세요',
  scanFailed: '스캔 실패 — 직접 입력하세요',
  scanUnavailable: '스캔은 정식 앱 빌드에서만 돼요',
  amountPerHour: '시간당 금액',
  flatAmount: '총 금액',
  endQuestion: '주차를 끝낼까요?',
  savedWord: '절약',
  parkedWord: '주차',
  duration: '주차 시간',
  paid: '낸 금액',
  avoided: '아낀 금액',
  costNow: '현재 요금',
  locating: '위치 찾는 중',
  use: '사용',
  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: '거의 다 왔어요 — 주위를 둘러보세요',
  walkToCar: '화살표 방향으로 걸으세요',
  indoorHint: '여기는 신호가 약해요 — 사진과 층 메모를 보세요.',
  noSpotDetails: '이 자리에는 사진도 층 메모도 없어요.',
  photo: '사진',
  addPhoto: '사진 추가',
  retakePhoto: '다시 찍기',
  removePhoto: '삭제',
  parkedWhen: '주차한 시각',
  justNow: '방금',
  minutesAgo: '{minutes}분 전',
  custom: '직접 입력',
  customMinutes: '분',
  notParkedYet: '여기 주차한 게 아닌가요? 기록을 지우세요',
  remindMe: '알림 받기',
  reminderAnchor: '기준',
  anchorAfterPark: '주차한 뒤',
  anchorFirstTier: '첫 요금 인상 전',
  anchorEveryTier: '매 요금 인상 전',
  reminderAfterHow: '얼마 뒤',
  reminderBeforeHow: '얼마 전',
  reminderKind: '알림 방식',
  kindNotification: '알림',
  kindAlarm: '소리',
  kindBoth: '둘 다',
  kindHint: '소리 알림은 집중 모드를 뚫어요. 무음에서도 울리는 진짜 알람은 iOS 26이 필요해요.',
  reminderNeedsTariff: '요금표가 있어야 해요 — 먼저 넣으세요',
  reminderOff: '끔',
  hoursShort: '{hours}시간',
  simpleReminder: '{duration}째 주차 중이에요.',
  // Durum satırları (§5.11)
  offlineTimer: '오프라인 — 타이머는 계속 돌아요',
  weakGpsNudge: '신호가 약해요 — 사진이나 층 메모를 남기세요',
  locationOff: '위치 꺼짐 · 켜기',
  notificationsOff: '알림 꺼짐 · 설정에서 켜기',
  cameraOff: '카메라 꺼짐 · 설정에서 켜기',
  // Boş durumlar (§5.12)
  noSessions: '아직 주차 기록이 없어요.',
  firstParkHere: '첫 주차가 여기에 남아요.',
  noActiveSession: '진행 중인 주차 없음',
  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'PRO가 주차를 감지해요',
  proBody: '신경 쓸 일이 없어요.',
  proFeatureAuto: 'CarPlay가 끊기면 타이머를 켤지 물어봐요',
  proFeatureScan: '요금표를 카메라로 스캔해요',
  autoRenewNotice: '구독은 취소할 때까지 자동으로 갱신돼요. 요금은 구매 확인 시점과 갱신 때마다 Apple 계정으로 청구돼요. 설정에서 관리하거나 취소할 수 있어요.',
  proFeatureFind: '나침반과 AR로 차까지 안내해요',
  proFeatureFilter: '충전, 실내, 거리로 주차장을 걸러요',
  planPerMonth: '월 {price}',
  planSave: '{percent}% 절약',
  terms: '이용약관 (EULA)',
  planYearly: '연간',
  planMonthly: '월간',
  planLifetime: '평생',
  continueYearly: '계속 — 연 {price}',
  continueMonthly: '계속 — 월 {price}',
  continueLifetime: '계속 — 한 번 {price}',
  freeThen: '{intro}, 이후 {price}',
  demoPlans: '예시 가격 — 디버그 빌드 전용.',
  plansError: '요금제를 불러오지 못했어요. 연결을 확인하세요.',
  retry: '다시 시도',
  restore: '구매 복원',
  privacy: '개인정보 처리방침',
  restored: '복원했어요.',
  noPurchases: '구매 내역이 없어요.',
  purchaseFailed: '구매하지 못했어요.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: '사용 중',
  // Ayarlar (§7.9)
  updateRequiredTitle: '업데이트 필요',
  updateRequiredBody: '이 버전은 주차 요금을 더 이상 정확히 계산하지 못해요. 계속하려면 업데이트하세요.',
  updateNow: '업데이트',
  settings: '설정',
  appearance: '화면',
  themeLight: '라이트',
  themeDark: '다크',
  themeSystem: '시스템',
  language: '언어',
  currency: '통화',
  alertThreshold: '알림 시점',
  minutesShort: '{minutes}분',
  autoDetect: '자동 감지',
  autoDetectHint: '차의 Bluetooth나 CarPlay 연결이 끊기면 자리를 저장해요.',
  autoDetectPro: '자동 감지는 Pro',
  autoParkedAsk: '방금 주차했나요? 누르면 여기서 타이머가 시작돼요.',
  autoParkedNotice: '주차 자리를 저장했어요. 타이머를 시작할까요?',
  permissions: '권한',
  locationGranted: '위치 켜짐',
  notificationsGranted: '알림 켜짐',
  data: '데이터',
  deleteAllData: '주차 기록 전체 삭제',
  deleteAllConfirm: '주차 기록을 전부 지울까요? 되돌릴 수 없어요.',
  delete: '삭제',
  cancel: '취소',
  developer: '개발자',
  devPremium: '프리미엄 켜짐',
  devPremiumHint: '디버그 빌드 전용. 끄면 페이월과 잠긴 화면이 보여요.',
  devResetOnboarding: '온보딩 다시 보기',
  manageSubscription: '구독 관리',
  exportData: '내 데이터 내보내기',
  support: '문의',
  rateAskTitle: 'ParkIQ가 도움이 되나요?',
  rateAskBody: '별점을 주면 다른 운전자들이 찾기 쉬워져요. 뭔가 아쉬웠다면 저희에게 알려주세요.',
  rateYes: '네, 별점 줄게요',
  rateNo: '별로예요',
  later: '나중에',
  goProUpsell: '요금표 스캔, 차까지 안내, 주차장 필터',
  rateUs: 'ParkIQ 별점 주기',
  about: '앱 정보',
  version: '버전',
  // Geçmiş (§7.8)
  lockedSessions: 'Pro에서 {count}건 더',
  history: '기록',
  shareMonth: '이번 달 공유',
  monthlySaved: '월별 절약',
  totalSaved: '절약',
  sessionsCount: '주차',
  avgDuration: '평균 시간',
  sessionDetail: '주차 기록',
  openInMaps: '지도에서 열기',
  fixLocation: '주차 위치 수정',
  purchaseDoneTitle: '이제 Pro예요.',
  purchaseDoneBody: '요금표 스캔, 나침반과 AR 안내, 자동 감지, 주차장 필터를 쓸 수 있어요.',
  restoredTitle: '복원했어요.',
  restoredBody: '이 iPhone에서 Pro가 다시 켜졌어요.',
  noPurchasesBody: '이 Apple Account에는 복원할 게 없어요. 다른 계정으로 결제했다면 그 계정으로 로그인해서 다시 해보세요.',
  restoring: '복원 중…',
  introFree: '{period} 무료',
  introDiscounted: '{period} {price}',
  periodDay: '{count}일',
  periodWeek: '{count}주',
  periodMonth: '{count}개월',
  periodYear: '{count}년',
  lifetimeNote: '한 번 결제, 구독 없음',
  savedSoFar: 'ParkIQ가 지금까지 {amount} 아껴줬어요',
  dailyMax: '일 최대 요금 (선택)',
  beyondSchedule: '요금표에 없는 시간대예요 — 금액이 정확하지 않아요',
  clockFormat: '시간 표시',
  clock12: '오후 1:04',
  clock24: '13:04',
  units: '거리',
  unitsMetric: '미터',
  unitsImperial: '피트와 마일',
  followDevice: '방향 따라가기',
  headingUnavailable: '나침반 방향을 못 잡아요 — 거리는 정확해요',
  calibrateCompass: '나침반이 어긋났어요 — 폰을 8자로 흔드세요',
  poiError: '주변 주차장을 못 불러왔어요 — 연결을 확인하세요',
  locationMissing: '위치를 못 잡았어요 — 지도에 표시하세요',
  locationRough: '±{meters} 오차로 저장했어요 — 지도에서 고치세요',
  deleteSessionTitle: '이 주차 기록을 지울까요?',
  deleteSessionBody: '기록과 사진이 지워져요. 되돌릴 수 없어요.',
  compassLocked: '나침반과 AR 안내는 Pro예요. 자리, 사진, 메모는 계속 무료예요.',
  back: '뒤로',
  today: '오늘',
  yesterday: '어제',
  stillParkedShort: '아직 주차 중인가요? 이 기록은 어제 시작됐어요.',
};
