import type { CopyKey } from './en';

// NL (Nederland) — hitap "je"; damgalar büyük harf ve nokta imzası korunur, kısa etiket tercih edildi.
export const nlNL: Record<CopyKey, string> = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: 'PARKEER',
  onbBody1: 'Eén tik markeert waar je de auto achterlaat. Verdieping, foto en notitie zijn optioneel — vul ze alleen in als de garage onoverzichtelijk is.',
  onbTitle2: 'BESPAAR',
  onbBody2: 'Voer het tarief één keer in, dan telt ParkIQ af naar de volgende prijsstap. Vertrek voor de sprong, dan houd je het verschil in je zak.',
  onbTitle3: 'VIND JE AUTO',
  onbBody3: 'Kompas en kaart brengen je terug. Ondergronds, waar GPS het opgeeft, nemen de foto en verdieping die je bewaarde het over.',
  skip: 'Overslaan',
  enableLocation: 'Doorgaan',
  notNow: 'Nu niet',
  iParked: 'Geparkeerd',
  foundIt: 'Gevonden',
  arMode: 'Camerabeeld',
  arHint: 'Volg de lijn',
  arInitializing: 'Beweeg de telefoon langzaam om te starten',
  arFailed: 'Camera volgt niet — gebruik het kompas',
  findMyCar: 'Vind mijn auto',
  shareLocation: 'Locatie delen',
  endSession: 'Stoppen',
  done: 'Klaar',
  keep: 'Laat lopen',
  undo: 'Ongedaan maken',
  shareCard: 'Besparing delen',
  // Keşif
  whereTo: 'Waarheen?',
  noNearbyForFilter: 'Niets in de buurt met dit filter',
  filters: 'Filters',
  searchRadius: 'Binnen',
  results: '{count} in de buurt',
  filterAll: 'Alles',
  filterCharging: 'Laden',
  filterCovered: 'Overdekt',
  myLocation: 'Mijn locatie',
  noResults: 'Geen plekken gevonden.',
  photoAdded: 'Toegevoegd',
  close: 'Sluiten',
  noTariffYet: 'Nog geen tarief voor deze plek',
  editTariff: 'Tarief aanpassen',
  preferences: 'Voorkeuren',
  laParked: 'GEPARKEERD',
  laNextTier: 'HIERNA {price}',
  laNowNext: 'Nu {now} · Straks {next}',
  wNoSession: 'Niet geparkeerd',
  wSavedLabel: 'DEZE MAAND BESPAARD',
  wParkTitle: 'Parkeren',
  wParkHint: 'Tik om je plek te bewaren',
  poiParking: 'Parkeerplaats',
  poiCharging: 'Laadpunt',
  directions: 'Route',
  minWalk: '{minutes} min lopen',
  // Oturum
  shareMessage: 'De auto staat hier.',
  parkedStamp: 'GEPARKEERD.',
  parkedAt: 'Geparkeerd om {time}',
  savedStamp: '{amount} BESPAARD.',
  parkedDurationStamp: '{duration} GEPARKEERD.',
  stillParked: 'Sta je nog bij {place}?',
  addTariff: 'Voeg tarief toe om kosten te zien',
  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: 'Vertrek binnen {minutes} min: {now} in plaats van {next}',
  exitNowPay: 'Vertrek nu: {now} in plaats van {next}',
  nowNext: 'Nu {now} · Straks {next}',
  nextTier: 'Volgende stap',
  tierAlert: 'Stap {tier} over {minutes} min. Nu {now}, daarna {next}.',
  flatRate: '{amount} vast',
  perHour: '{amount} / uur',
  lastTimeTariff: 'Vorige keer: {summary} — gebruiken?',
  // Park sheet'i + tarife formu (§7.3–7.4)
  detailsOptional: 'Details optioneel',
  pickOnMap: 'Kies op de kaart',
  pickOnMapHint: 'Schuif de kaart tot de speld op je auto staat',
  pickAreaHint: 'Schuif de kaart naar het gebied waar je zoekt',
  useThisArea: 'Hier zoeken',
  pickArea: 'Kies op kaart',
  usePin: 'Deze plek gebruiken',
  parkLocation: 'Locatie',
  useMyLocation: 'Mijn huidige locatie gebruiken',
  floor: 'Verdieping',
  floorPlaceholder: 'Niveau −2, C',
  note: 'Notitie',
  notePlaceholder: 'Naast de lift',
  tariff: 'Tarief',
  tariffNone: 'Geen',
  tariffHourly: 'Per uur',
  tariffFlat: 'Vast',
  tariffTiered: 'Stappen',
  untilDuration: 'Duur',
  unitMinShort: 'min',
  unitHourShort: 'u',
  unitToggle: 'Eenheid wisselen',
  totalSoFar: 'Te betalen',
  addTier: 'Stap toevoegen',
  cumulativeHint: 'Vul het totaal in dat je betaalt als je binnen die tijd weggaat, niet het extra bedrag.',
  scanPro: 'Bord scannen zit in Pro',
  osmAttribution: 'Parkeerdata © OpenStreetMap-bijdragers',
  scheduleWeekday: 'Doordeweeks tarief gebruikt',
  scheduleWeekend: 'Weekendtarief gebruikt',
  scheduleDay: 'Dagtarief gebruikt',
  scheduleNight: 'Nachttarief gebruikt',
  scheduleChanged: 'Het tarief is gewisseld — dit bord rekent op dit tijdstip anders. Scan opnieuw of pas het tarief aan.',
  scanBoard: 'Bord scannen',
  scanning: 'Bord wordt gelezen',
  scanNotDetected: 'Bord niet leesbaar — ga dichterbij, vermijd weerkaatsing of vul het zelf in',
  scanPartial: 'Sommige regels zijn niet gelezen — controleer de stappen hieronder',
  scanFailed: 'Scannen mislukt — vul het zelf in',
  scanUnavailable: 'Scannen werkt alleen in de volledige app',
  amountPerHour: 'Bedrag per uur',
  flatAmount: 'Totaalbedrag',
  endQuestion: 'Parkeren stoppen?',
  savedWord: 'BESPAARD',
  parkedWord: 'GEPARKEERD',
  duration: 'Duur',
  paid: 'Betaald',
  avoided: 'Bespaard',
  costNow: 'Kosten nu',
  locating: 'Locatie zoeken',
  use: 'Gebruiken',
  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: 'Je bent dichtbij — kijk om je heen',
  walkToCar: 'Loop de pijl achterna',
  indoorHint: 'Zwak signaal hier — gebruik je foto en verdieping.',
  noSpotDetails: 'Geen foto of verdieping bij deze plek.',
  photo: 'Foto',
  addPhoto: 'Foto toevoegen',
  retakePhoto: 'Opnieuw',
  removePhoto: 'Verwijderen',
  parkedWhen: 'Ik parkeerde',
  justNow: 'Zojuist',
  minutesAgo: '{minutes} min geleden',
  custom: 'Anders',
  customMinutes: 'Minuten',
  notParkedYet: 'Niet hier geparkeerd? Verwijder dit item',
  remindMe: 'Herinnering',
  reminderAnchor: 'Tel vanaf',
  anchorAfterPark: 'Na het parkeren',
  anchorFirstTier: 'Voor de eerste prijsstijging',
  anchorEveryTier: 'Voor elke prijsstijging',
  reminderAfterHow: 'Hoe lang erna',
  reminderBeforeHow: 'Hoe lang ervoor',
  reminderKind: 'Hoe waarschuwen',
  kindNotification: 'Melding',
  kindAlarm: 'Geluid',
  kindBoth: 'Allebei',
  kindHint: 'Geluid komt door Focus heen. Een echt alarm dat ook op stil afgaat, vraagt iOS 26.',
  reminderNeedsTariff: 'Hiervoor is een tarief nodig — voeg er eerst een toe',
  reminderOff: 'Uit',
  hoursShort: '{hours} u',
  simpleReminder: 'Je staat al {duration} geparkeerd.',
  // Durum satırları (§5.11)
  offlineTimer: 'Offline — de teller loopt door',
  weakGpsNudge: 'Zwak signaal — voeg een foto of verdieping toe',
  locationOff: 'Locatie uit · Inschakelen',
  notificationsOff: 'Meldingen uit · Zet aan in Instellingen',
  cameraOff: 'Camera uit · Zet aan in Instellingen',
  // Boş durumlar (§5.12)
  noSessions: 'Nog niets geparkeerd.',
  firstParkHere: 'Je eerste parkeersessie komt hier.',
  noActiveSession: 'Geen actieve sessie',
  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'PRO ZIET DAT JE PARKEERT',
  proBody: 'Jij hoeft er niet aan te denken.',
  proFeatureAuto: 'Vraagt de teller te starten zodra CarPlay loskoppelt',
  proFeatureScan: 'Scan tariefborden met de camera',
  autoRenewNotice: 'Abonnementen verlengen automatisch tot je opzegt. Het bedrag wordt bij bevestiging en bij elke verlenging van je Apple Account afgeschreven. Beheren of opzeggen doe je in Instellingen.',
  proFeatureFind: 'Kompas en AR wijzen de weg terug naar je auto',
  proFeatureFilter: 'Filter op laadpunt, overdekt en afstand',
  planPerMonth: '{price} / maand',
  planSave: 'BESPAAR {percent}%',
  terms: 'Voorwaarden (EULA)',
  planYearly: 'Jaarlijks',
  planMonthly: 'Maandelijks',
  planLifetime: 'Voor altijd',
  continueYearly: 'Doorgaan — {price}/jaar',
  continueMonthly: 'Doorgaan — {price}/maand',
  continueLifetime: 'Doorgaan — {price} eenmalig',
  freeThen: '{intro}, daarna {price}',
  demoPlans: 'Voorbeeldprijzen — alleen in de debugbuild.',
  plansError: 'Abonnementen niet geladen. Controleer je verbinding.',
  retry: 'Opnieuw',
  restore: 'Aankopen herstellen',
  privacy: 'Privacy',
  restored: 'Hersteld.',
  noPurchases: 'Geen aankopen gevonden.',
  purchaseFailed: 'Aankoop mislukt.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: 'Actief',
  // Ayarlar (§7.9)
  updateRequiredTitle: 'UPDATE NODIG',
  updateRequiredBody: 'Deze versie rekent je parkeerkosten niet meer goed uit. Werk bij om verder te gaan.',
  updateNow: 'Bijwerken',
  settings: 'Instellingen',
  appearance: 'Weergave',
  themeLight: 'Licht',
  themeDark: 'Donker',
  themeSystem: 'Systeem',
  language: 'Taal',
  currency: 'Valuta',
  alertThreshold: 'Vooraf waarschuwen',
  minutesShort: '{minutes} min',
  autoDetect: 'Automatisch herkennen',
  autoDetectHint: 'Bewaart je plek zodra de Bluetooth of CarPlay van je auto loskoppelt.',
  autoDetectPro: 'Automatisch herkennen zit in Pro',
  autoParkedAsk: 'Net geparkeerd? Tik om de teller hier te starten.',
  autoParkedNotice: 'Je plek is bewaard. Teller starten?',
  permissions: 'Toegang',
  locationGranted: 'Locatie aan',
  notificationsGranted: 'Meldingen aan',
  data: 'Gegevens',
  deleteAllData: 'Alle sessies verwijderen',
  deleteAllConfirm: 'Alle sessies verwijderen? Dit kun je niet terugdraaien.',
  delete: 'Verwijderen',
  cancel: 'Annuleer',
  developer: 'Ontwikkelaar',
  devPremium: 'Premium aan',
  devPremiumHint: 'Alleen in debugbuilds. Zet uit om de paywall en vergrendelde staten te zien.',
  devResetOnboarding: 'Onboarding opnieuw tonen',
  manageSubscription: 'Abonnement beheren',
  exportData: 'Mijn gegevens exporteren',
  support: 'Hulp',
  rateAskTitle: 'DOET PARKIQ ZIJN WERK?',
  rateAskBody: 'Met een beoordeling vinden andere automobilisten de app. Klopt er iets niet, zeg het ons.',
  rateYes: 'Ja, beoordelen',
  rateNo: 'Niet echt',
  later: 'Later',
  goProUpsell: 'Borden scannen, terug naar je auto, parkeren filteren',
  rateUs: 'ParkIQ beoordelen',
  about: 'Over',
  version: 'Versie',
  // Geçmiş (§7.8)
  lockedSessions: 'Nog {count} sessies in Pro',
  history: 'Geschiedenis',
  shareMonth: 'Deze maand delen',
  monthlySaved: 'Bespaard per maand',
  totalSaved: 'Bespaard',
  sessionsCount: 'Sessies',
  avgDuration: 'Gem. duur',
  sessionDetail: 'Sessie',
  openInMaps: 'Openen in Apple Maps',
  fixLocation: 'Parkeerlocatie corrigeren',
  purchaseDoneTitle: 'Je bent Pro.',
  purchaseDoneBody: 'Borden scannen, kompas en AR, automatisch herkennen en parkeerfilters staan nu aan.',
  restoredTitle: 'Hersteld.',
  restoredBody: 'Je Pro-toegang staat weer op deze iPhone.',
  noPurchasesBody: 'Op dit Apple Account valt niets te herstellen. Betaald met een ander account? Log daarmee in en probeer opnieuw.',
  restoring: 'Herstellen…',
  introFree: '{period} gratis',
  introDiscounted: '{period} voor {price}',
  periodDay: '{count} dag',
  periodWeek: '{count} week',
  periodMonth: '{count} maand',
  periodYear: '{count} jaar',
  lifetimeNote: 'Eén betaling, geen abonnement',
  savedSoFar: 'ParkIQ bespaarde je tot nu toe {amount}',
  dailyMax: 'Dagmaximum (optioneel)',
  beyondSchedule: 'Voorbij wat het bord aangeeft — het bedrag is niet meer zeker',
  clockFormat: 'Tijdnotatie',
  clock12: '1:04 PM',
  clock24: '13:04',
  units: 'Afstand',
  unitsMetric: 'Meters',
  unitsImperial: 'Voet en mijl',
  followDevice: 'Volg mijn positie',
  headingUnavailable: 'Geen kompasrichting — de afstand klopt wel',
  calibrateCompass: 'Kompas is ontregeld — zwaai je telefoon in een acht',
  poiError: 'Parkeerplekken in de buurt niet geladen — controleer je verbinding',
  locationMissing: 'Geen locatie gevonden — zet hem zelf op de kaart',
  locationRough: 'Bewaard met ±{meters} nauwkeurigheid — corrigeer op de kaart',
  deleteSessionTitle: 'Deze parkeersessie verwijderen?',
  deleteSessionBody: 'De registratie en de foto verdwijnen. Dit kun je niet terugdraaien.',
  compassLocked: 'Kompas en AR zitten in Pro. Je plek, foto en notitie blijven gratis.',
  back: 'Terug',
  today: 'Vandaag',
  yesterday: 'Gisteren',
  stillParkedShort: 'Sta je er nog? Deze sessie loopt sinds gisteren.',
};
