import type { CopyKey } from './en';

// PT-BR karşılıkları. Hitap "você"; damgalar "{amount} NO BOLSO." — TR'deki "cebinde" duygusu.
export const ptBR: Record<CopyKey, string> = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: 'ESTACIONE',
  onbBody1: 'Um toque marca onde você deixou o carro. Andar, foto e nota são opcionais — preencha só quando o estacionamento for confuso.',
  onbTitle2: 'ECONOMIZE',
  onbBody2: 'Digite a tarifa uma vez e o ParkIQ conta o tempo até a próxima faixa de preço. Se você sair antes de subir, a diferença fica no seu bolso.',
  onbTitle3: 'ENCONTRE',
  onbBody3: 'Bússola e mapa levam você de volta. No subsolo, onde o GPS falha, entram a foto e o andar que você salvou.',
  skip: 'Pular',
  enableLocation: 'Continuar',
  notNow: 'Agora não',
  iParked: 'Estacionei',
  foundIt: 'Achei',
  arMode: 'Ver pela câmera',
  arHint: 'Caminhe até o marcador',
  arInitializing: 'Mova o celular devagar para iniciar o rastreamento',
  arFailed: 'O rastreamento da câmera falhou — use a bússola',
  findMyCar: 'Achar meu carro',
  shareLocation: 'Compartilhar local',
  endSession: 'Encerrar',
  done: 'Pronto',
  undo: 'Desfazer',
  shareCard: 'Compartilhar cartão',
  // Keşif
  whereTo: 'Para onde?',
  noNearbyForFilter: 'Nada por perto com esse filtro',
  filters: 'Filtros',
  searchRadius: 'Raio',
  results: '{count} por perto',
  filterAll: 'Todos',
  filterCharging: 'Recarga',
  filterCovered: 'Coberto',
  myLocation: 'Meu local',
  noResults: 'Nenhum lugar encontrado.',
  photoAdded: 'Adicionada',
  close: 'Fechar',
  noTariffYet: 'Nenhuma tarifa salva para este local',
  editTariff: 'Editar tarifa',
  preferences: 'Preferências',
  laParked: 'ESTACIONADO',
  laNextTier: 'PRÓXIMA FAIXA {price}',
  laNowNext: 'Agora {now} · Depois {next}',
  wNoSession: 'Nenhuma sessão ativa',
  wSavedLabel: 'ECONOMIA DO MÊS',
  wParkTitle: 'Estacionar',
  wParkHint: 'Toque para salvar o local',
  poiParking: 'Estacionamento',
  poiCharging: 'Ponto de recarga',
  directions: 'Como chegar',
  minWalk: '{minutes} min a pé',
  // Oturum
  shareMessage: 'O carro está aqui.',
  parkedStamp: 'ESTACIONADO.',
  parkedAt: 'Estacionado às {time}',
  savedStamp: '{amount} NO BOLSO.',
  parkedDurationStamp: '{duration} ESTACIONADO.',
  stillParked: 'Ainda está em {place}?',
  addTariff: 'Adicione a tarifa para ver o custo',
  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: 'Saia em {minutes} min e pague {now} em vez de {next}',
  exitNowPay: 'Saia agora e pague {now} em vez de {next}',
  nowNext: 'Agora {now} · Depois {next}',
  nextTier: 'Próxima faixa',
  tierAlert: 'Faixa {tier} em {minutes} min. Agora {now}, depois {next}.',
  flatRate: '{amount} fixo',
  perHour: '{amount} / hora',
  lastTimeTariff: 'Da última vez: {summary} — usar?',
  // Park sheet'i + tarife formu (§7.3–7.4)
  pickOnMap: 'Marcar no mapa',
  pickOnMapHint: 'Mova o mapa até o pino ficar sobre o carro',
  pickAreaHint: 'Mova o mapa para definir onde buscar',
  useThisArea: 'Buscar aqui',
  pickArea: 'Escolher no mapa',
  usePin: 'Usar este local',
  parkLocation: 'Local',
  useMyLocation: 'Usar minha localização atual',
  floor: 'Andar',
  floorPlaceholder: 'S2, bloco C',
  note: 'Nota',
  notePlaceholder: 'Perto do elevador',
  tariff: 'Tarifa',
  tariffNone: 'Nenhuma',
  tariffHourly: 'Por hora',
  tariffFlat: 'Fixa',
  tariffTiered: 'Faixas',
  untilDuration: 'Duração',
  unitMinShort: 'min',
  unitHourShort: 'h',
  unitToggle: 'Mudar unidade',
  totalSoFar: 'Total a pagar',
  addTier: 'Adicionar faixa',
  cumulativeHint: 'Digite o total a pagar saindo dentro desse tempo, não o valor adicional.',
  scanPro: 'Leitura da placa é no Pro',
  osmAttribution: 'Dados de estacionamento © colaboradores do OpenStreetMap',
  scheduleWeekday: 'Tarifa de dia útil aplicada',
  scheduleWeekend: 'Tarifa de fim de semana aplicada',
  scheduleDay: 'Tarifa diurna aplicada',
  scheduleNight: 'Tarifa noturna aplicada',
  scheduleChanged: 'A tarifa mudou — a placa cobra outro valor neste horário. Leia de novo ou edite a tarifa.',
  scanBoard: 'Ler a placa',
  scanning: 'Lendo a placa',
  scanNotDetected: 'Não deu para ler a placa — chegue mais perto, evite reflexo ou digite os valores',
  scanPartial: 'Algumas linhas não foram lidas — confira as faixas abaixo',
  scanFailed: 'A leitura falhou — digite os valores',
  scanUnavailable: 'A leitura só funciona na versão completa do app',
  amountPerHour: 'Valor por hora',
  flatAmount: 'Valor total',
  addDetails: 'Adicionar detalhes',
  savedWord: 'NO BOLSO',
  parkedWord: 'ESTACIONADO',
  duration: 'Duração',
  paid: 'Pago',
  avoided: 'Economia',
  costNow: 'Custo agora',
  locating: 'Localizando',
  use: 'Usar',
  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: 'Você está perto — olhe em volta',
  walkToCar: 'Siga o ponto',
  indoorHint: 'O sinal está fraco aqui — use a foto e o andar.',
  noSpotDetails: 'Sem foto nem andar salvos para este local.',
  photo: 'Foto',
  addPhoto: 'Adicionar foto',
  retakePhoto: 'Tirar de novo',
  removePhoto: 'Remover',
  parkedWhen: 'Estacionei',
  justNow: 'Agora mesmo',
  minutesAgo: 'há {minutes} min',
  custom: 'Outro',
  customMinutes: 'Minutos',
  notParkedYet: 'Não estacionou aqui? Apague o registro',
  remindMe: 'Lembrete',
  reminderAnchor: 'Contar a partir de',
  anchorAfterPark: 'Depois de estacionar',
  anchorEveryTier: 'Antes de cada aumento',
  reminderAfterHow: 'Quanto tempo depois',
  reminderBeforeHow: 'Quanto tempo antes',
  reminderKind: 'Como avisar',
  kindNotification: 'Notificação',
  kindAlarm: 'Som',
  kindBoth: 'Os dois',
  kindHint: 'O som passa pelos modos de Foco. Um alarme que toca no silencioso exige o iOS 26.',
  reminderNeedsTariff: 'Isto precisa de uma tarifa — adicione uma antes',
  reminderOff: 'Desligado',
  hoursShort: '{hours} h',
  simpleReminder: 'Você está estacionado há {duration}.',
  // Durum satırları (§5.11)
  offlineTimer: 'Sem conexão — o cronômetro continua',
  weakGpsNudge: 'Sinal fraco — adicione uma foto ou o andar',
  locationOff: 'Localização desligada · Ligar',
  notificationsOff: 'Notificações desligadas · Ligue nos Ajustes',
  cameraOff: 'Câmera desligada · Ligue nos Ajustes',
  // Boş durumlar (§5.12)
  noSessions: 'Nenhuma sessão ainda.',
  firstParkHere: 'Seu primeiro estacionamento aparece aqui.',
  noActiveSession: 'Nenhuma sessão ativa',
  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'O PRO PERCEBE SOZINHO',
  proBody: 'Você nem pensa nisso.',
  proFeatureAuto: 'Detecção automática',
  proFeatureScan: 'Escanear tarifas',
  autoRenewNotice: 'Renova automaticamente até o cancelamento. Gerencie nos Ajustes.',
  proFeatureFind: 'Bússola e RA',
  proFeatureFilter: 'Filtros de estacionamento',
  proFeaturePool: 'Tarifas sugeridas por outros motoristas',
  planPerMonth: '{price} / mês',
  planSave: 'ECONOMIZE {percent}%',
  terms: 'Termos (EULA)',
  planYearly: 'Anual',
  planMonthly: 'Mensal',
  planLifetime: 'Vitalício',
  continueYearly: 'Continuar — {price}/ano',
  continueMonthly: 'Continuar — {price}/mês',
  continueLifetime: 'Continuar — {price} uma vez',
  freeThen: '{intro}, depois {price}',
  demoPlans: 'Preços de exemplo — só na versão de teste.',
  plansError: 'Não foi possível carregar os planos. Verifique sua conexão.',
  retry: 'Tentar de novo',
  restore: 'Restaurar compras',
  privacy: 'Privacidade',
  restored: 'Restaurado.',
  noPurchases: 'Nenhuma compra encontrada.',
  purchaseFailed: 'A compra não foi concluída.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: 'Ativo',
  // Ayarlar (§7.9)
  updateRequiredTitle: 'ATUALIZAÇÃO NECESSÁRIA',
  updateRequiredBody: 'Esta versão não calcula mais os valores de estacionamento corretamente. Atualize para continuar.',
  updateNow: 'Atualizar',
  settings: 'Ajustes',
  appearance: 'Aparência',
  themeLight: 'Claro',
  themeDark: 'Escuro',
  themeSystem: 'Sistema',
  language: 'Idioma',
  currency: 'Moeda',
  alertThreshold: 'Avisar antes',
  minutesShort: '{minutes} min',
  autoDetect: 'Detecção automática',
  autoDetectHint: 'Salva o local quando o Bluetooth do carro ou o CarPlay desconecta.',
  autoDetectPro: 'Detecção automática é no Pro',
  autoParkedAsk: 'Acabou de estacionar? Toque para iniciar o cronômetro aqui.',
  autoParkedNotice: 'O local foi salvo. Iniciar o cronômetro?',
  permissions: 'Permissões',
  locationGranted: 'Localização ligada',
  notificationsGranted: 'Notificações ligadas',
  data: 'Dados',
  deleteAllData: 'Apagar todas as sessões',
  deleteAllConfirm: 'Apagar todas as sessões? Isso não pode ser desfeito.',
  delete: 'Apagar',
  cancel: 'Cancelar',
  developer: 'Desenvolvedor',
  devPremium: 'Premium liberado',
  devPremiumHint: 'Só na versão de teste. Desligue para ver o paywall e os estados bloqueados.',
  devResetOnboarding: 'Mostrar o onboarding de novo',
  manageSubscription: 'Gerenciar assinatura',
  exportData: 'Exportar meus dados',
  support: 'Suporte',
  rateAskTitle: 'O PARKIQ ESTÁ RESOLVENDO?',
  rateAskBody: 'Uma avaliação ajuda outros motoristas a encontrar o app. Se algo está errado, fale com a gente.',
  rateYes: 'Sim, avaliar',
  rateNo: 'Nem tanto',
  later: 'Depois',
  goProUpsell: 'Leia placas, volte guiado ao carro, filtre estacionamentos',
  rateUs: 'Avaliar o ParkIQ',
  about: 'Sobre',
  version: 'Versão',
  // Geçmiş (§7.8)
  lockedSessions: 'Mais {count} sessões no Pro',
  history: 'Histórico',
  shareMonth: 'Compartilhar o mês',
  monthlySaved: 'Economia por mês',
  totalSaved: 'Economia',
  sessionsCount: 'Sessões',
  avgDuration: 'Tempo médio',
  sessionDetail: 'Sessão',
  openInMaps: 'Abrir no Mapas',
  fixLocation: 'Corrigir o local do carro',
  purchaseDoneTitle: 'Você é Pro.',
  purchaseDoneBody: 'Leitura de placa, bússola e AR, detecção automática e filtros de estacionamento estão liberados.',
  restoredTitle: 'Restaurado.',
  restoredBody: 'Seu acesso Pro voltou neste iPhone.',
  noPurchasesBody: 'Nada para restaurar nesta Apple Account. Se você pagou com outra, entre com ela e tente de novo.',
  restoring: 'Restaurando…',
  introFree: '{period} grátis',
  introDiscounted: '{period} por {price}',
  periodDay: '{count} dia',
  periodWeek: '{count} semana',
  periodMonth: '{count} mês',
  periodYear: '{count} ano',
  lifetimeNote: 'Pagamento único',
  dailyMax: 'Máximo diário (opcional)',
  beyondSchedule: 'Além do que a placa cobre — o valor já não é exato',
  clockFormat: 'Formato de hora',
  clock12: '1:04 PM',
  clock24: '13:04',
  units: 'Distância',
  unitsMetric: 'Metros',
  unitsImperial: 'Pés e milhas',
  followDevice: 'Seguir o celular',
  headingUnavailable: 'Sem direção da bússola — a distância continua certa',
  calibrateCompass: 'Bússola desregulada — faça um 8 no ar com o celular',
  poiError: 'Não deu para carregar os estacionamentos por perto — verifique sua conexão',
  locationMissing: 'Não deu para obter a localização — marque no mapa',
  locationRough: 'Salvo com precisão de ±{meters} — corrija no mapa',
  deleteSessionTitle: 'Apagar este registro?',
  deleteSessionBody: 'O registro e a foto são apagados. Isso não pode ser desfeito.',
  compassLocked: 'Bússola e AR são do Pro. O local, a foto e a nota continuam grátis.',
  back: 'Voltar',
  today: 'Hoje',
  yesterday: 'Ontem',
  stillParkedShort: 'Ainda estacionado? Esta sessão começou ontem.',
  // Park anı hızlı soruları (§7.3) + aktif sheet Detaylar satırı (§7.5)
  qLevel: 'Qual andar?',
  qTariff: 'Quanto custa?',
  qRemind: 'Quanto tempo depois de estacionar?',
  ground: 'Térreo',
  otherLevel: 'Outro',
  enterTariff: 'Digitar',
  scanShort: 'Escanear',
  lastTimeChip: 'Última vez · {summary}',
  details: 'Detalhes',
  inHoursAfter: 'em {hours} h',
  remindAfterSummary: '{duration} depois de estacionar',
  remindBeforeSummary: '{duration} antes de cada aumento',
  remindBeforeFirstSummary: '{duration} antes do primeiro aumento',
  // Tarife havuzu (§ sürücülerden gelen fiyatlar)
  pooledChip: 'Sugerida · {summary}',
  pooledFrom: 'Enviada por {count} motoristas que estacionaram aqui. Confira na placa.',
  tariffPool: 'Compartilhar tarifas',
  tariffPoolHint: 'Sua tarifa é sugerida a quem estaciona no mesmo lugar, e a deles a você. Viaja o preço de um local, nada sobre você. Desligado: nenhuma das duas.',
  savedSoFarLead: 'Foi isso que o ParkIQ já economizou para você.',
  // Soru akışı ilerletme + bitirme onayı (§7.3, §7.8)
  nextStep: 'Avançar',
  endQuestion: 'Encerrar esta sessão?',
  endAndSave: 'Encerrar e economizar {amount}',
  keep: 'Continuar estacionado',
  alarmStop: 'Parar',
};
