import type { CopyKey } from './en';

// pt-BR üstüne Avrupa Portekizcesi farkı: telemóvel/câmara/definições, "a + mastar" (gerund yok), partilhar, poupar, piso, escalão, registo.
export const ptPT: Partial<Record<CopyKey, string>> = {
  onbBody1: 'Um toque marca onde deixou o carro. Piso, foto e nota são opcionais — preencha só quando o parque for confuso.',
  onbTitle2: 'POUPE',
  onbBody2: 'Introduza a tarifa uma vez e o ParkIQ conta o tempo até ao escalão seguinte. Se sair antes de subir, a diferença fica no bolso.',
  onbBody3: 'Bússola e mapa levam-no de volta. Na cave, onde o GPS falha, entram a foto e o piso que guardou.',
  skip: 'Ignorar',
  foundIt: 'Encontrei',
  arMode: 'Ver pela câmara',
  arInitializing: 'Mova o telemóvel devagar para começar o rastreio',
  arFailed: 'O rastreio da câmara falhou — use a bússola',
  findMyCar: 'Encontrar o carro',
  shareLocation: 'Partilhar localização',
  endSession: 'Terminar',
  shareCard: 'Partilhar cartão',
  filterCharging: 'Carregamento',
  myLocation: 'O meu local',
  noTariffYet: 'Sem tarifa guardada para este local',
  laNextTier: 'ESCALÃO SEGUINTE {price}',
  wSavedLabel: 'POUPANÇA DO MÊS',
  wParkHint: 'Toque para guardar o local',
  poiCharging: 'Posto de carregamento',
  nextTier: 'Escalão seguinte',
  tierAlert: 'Escalão {tier} em {minutes} min. Agora {now}, depois {next}.',
  pickAreaHint: 'Mova o mapa para definir onde procurar',
  useThisArea: 'Procurar aqui',
  useMyLocation: 'Usar a minha localização',
  floor: 'Piso',
  floorPlaceholder: '−2, bloco C',
  tariffTiered: 'Escalões',
  addTier: 'Adicionar escalão',
  cumulativeHint: 'Introduza o total a pagar se sair dentro desse tempo, não o valor adicional.',
  scanPartial: 'Algumas linhas não foram lidas — verifique os escalões abaixo',
  scanNotDetected: 'Não foi possível ler a placa — chegue mais perto, evite reflexos ou introduza os valores',
  scanFailed: 'A leitura falhou — introduza os valores',
  scanning: 'A ler a placa',
  endQuestion: 'Terminar esta sessão?',
  avoided: 'Poupança',
  locating: 'A localizar',
  indoorHint: 'O sinal está fraco aqui — use a foto e o piso.',
  noSpotDetails: 'Sem foto nem piso guardados para este local.',
  notParkedYet: 'Não estacionou aqui? Apague o registo',
  simpleReminder: 'Está estacionado há {duration}.',
  offlineTimer: 'Sem ligação — o cronómetro continua',
  weakGpsNudge: 'Sinal fraco — adicione uma foto ou o piso',
  notificationsOff: 'Notificações desligadas · Ative nas Definições',
  cameraOff: 'Câmara desligada · Ative nas Definições',
  firstParkHere: 'O primeiro estacionamento aparece aqui.',
  proHeadline: 'O PRO DETETA SOZINHO',
  proBody: 'Nem pensa nisso.',
  proFeatureAuto: 'Pergunta se inicia o cronómetro quando o CarPlay se desliga',
  proFeatureScan: 'Lê a placa de tarifas com a câmara',
  autoRenewNotice: 'A subscrição renova-se automaticamente até ser cancelada. O pagamento sai da sua Apple Account na confirmação e em cada renovação. Pode gerir ou cancelar nas Definições.',
  proFeatureFilter: 'Filtra parques por carregamento, cobertura e distância',
  planSave: 'POUPE {percent}%',
  plansError: 'Não foi possível carregar os planos. Verifique a ligação.',
  settings: 'Definições',
  autoDetect: 'Deteção automática',
  autoDetectHint: 'Guarda o local quando o Bluetooth do carro ou o CarPlay se desliga.',
  autoDetectPro: 'Deteção automática é no Pro',
  autoParkedAsk: 'Acabou de estacionar? Toque para iniciar o cronómetro aqui.',
  autoParkedNotice: 'O local foi guardado. Iniciar o cronómetro?',
  manageSubscription: 'Gerir subscrição',
  exportData: 'Exportar os meus dados',
  rateAskTitle: 'O PARKIQ ESTÁ A DAR JEITO?',
  rateAskBody: 'Uma avaliação ajuda outros condutores a encontrar a app. Se algo está mal, diga-nos antes.',
  goProUpsell: 'Leia placas, volte guiado ao carro, filtre parques',
  monthlySaved: 'Poupança por mês',
  totalSaved: 'Poupança',
  shareMonth: 'Partilhar o mês',
  purchaseDoneTitle: 'Já é Pro.',
  purchaseDoneBody: 'Leitura de placa, bússola e AR, deteção automática e filtros de parques ficam ativos.',
  restoredBody: 'O acesso Pro voltou neste iPhone.',
  noPurchasesBody: 'Nada para restaurar nesta Apple Account. Se pagou com outra, inicie sessão nessa e tente de novo.',
  restoring: 'A restaurar…',
  lifetimeNote: 'Pagamento único, sem subscrição',
  savedSoFar: 'O ParkIQ já lhe poupou {amount}',
  followDevice: 'Seguir o telemóvel',
  calibrateCompass: 'Bússola desregulada — faça um 8 no ar com o telemóvel',
  poiError: 'Não foi possível carregar os parques por perto — verifique a ligação',
  locationMissing: 'Não foi possível obter a localização — marque no mapa',
  locationRough: 'Guardado com precisão de ±{meters} — corrija no mapa',
  deleteSessionTitle: 'Apagar este registo?',
  deleteSessionBody: 'O registo e a foto são apagados. Isso não pode ser desfeito.',
};
