import type { CopyKey } from './en';

// SV karşılıkları. Hitap "du"; damgalar "PARKERAD." / "{amount} SPARAT." — para önce, TR'deki "cebinde" duygusu.
export const sv: Record<CopyKey, string> = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: 'PARKERA',
  onbBody1: 'Ett tryck markerar var du lämnade bilen. Plan, foto och anteckning är valfria — fyll i dem bara när garaget är rörigt.',
  onbTitle2: 'SPARA PENGAR',
  onbBody2: 'Ange taxan en gång, så räknar ParkIQ ner till nästa prissteg. Åker du innan det höjs stannar mellanskillnaden i din ficka.',
  onbTitle3: 'HITTA',
  onbBody3: 'Kompass och karta leder dig tillbaka. Under jord, där GPS ger upp, tar fotot och planen du sparade över.',
  skip: 'Hoppa över',
  enableLocation: 'Fortsätt',
  notNow: 'Inte nu',
  iParked: 'Jag parkerade',
  foundIt: 'Hittade den',
  arMode: 'Kameravy',
  arHint: 'Följ strålen',
  arInitializing: 'Rör telefonen långsamt för att starta spårningen',
  arFailed: 'Kameraspårningen misslyckades — använd kompassen',
  findMyCar: 'Hitta bilen',
  shareLocation: 'Dela plats',
  endSession: 'Avsluta',
  done: 'Klar',
  keep: 'Fortsätt',
  undo: 'Ångra',
  shareCard: 'Dela kort',
  // Keşif
  whereTo: 'Vart ska du?',
  noNearbyForFilter: 'Inget i närheten matchar filtret',
  filters: 'Filter',
  searchRadius: 'Inom',
  results: '{count} i närheten',
  filterAll: 'Alla',
  filterCharging: 'Laddning',
  filterCovered: 'P-hus',
  myLocation: 'Min plats',
  noResults: 'Inga platser hittades.',
  photoAdded: 'Tillagt',
  close: 'Stäng',
  noTariffYet: 'Ingen taxa sparad för den här platsen än',
  editTariff: 'Ändra taxa',
  preferences: 'Preferenser',
  laParked: 'PARKERAD',
  laNextTier: 'NÄSTA STEG {price}',
  laNowNext: 'Nu {now} · Sedan {next}',
  wNoSession: 'Ingen aktiv parkering',
  wSavedLabel: 'SPARAT DENNA MÅNAD',
  wParkTitle: 'Parkera',
  wParkHint: 'Tryck för att spara platsen',
  poiParking: 'Parkering',
  poiCharging: 'Laddstation',
  directions: 'Vägbeskrivning',
  minWalk: '{minutes} min gång',
  // Oturum
  shareMessage: 'Bilen står här.',
  parkedStamp: 'PARKERAD.',
  parkedAt: 'Parkerad {time}',
  savedStamp: '{amount} SPARAT.',
  parkedDurationStamp: 'PARKERAD {duration}.',
  stillParked: 'Står bilen kvar vid {place}?',
  addTariff: 'Lägg till taxa för att se kostnaden',
  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: 'Åk inom {minutes} min och betala {now} i stället för {next}',
  exitNowPay: 'Åk nu och betala {now} i stället för {next}',
  nowNext: 'Nu {now} · Sedan {next}',
  nextTier: 'Nästa steg',
  tierAlert: 'Steg {tier} om {minutes} min. Nu {now}, sedan {next}.',
  flatRate: '{amount} fast',
  perHour: '{amount} / timme',
  lastTimeTariff: 'Förra gången: {summary} — använda den?',
  // Park sheet'i + tarife formu (§7.3–7.4)
  detailsOptional: 'Detaljer är valfria',
  pickOnMap: 'Välj på kartan',
  pickOnMapHint: 'Flytta kartan tills nålen står på bilen',
  pickAreaHint: 'Flytta kartan för att välja var du söker',
  useThisArea: 'Sök här',
  pickArea: 'Välj på kartan',
  usePin: 'Använd den här platsen',
  parkLocation: 'Plats',
  useMyLocation: 'Använd min nuvarande plats',
  floor: 'Plan',
  floorPlaceholder: 'Plan −2, C',
  note: 'Anteckning',
  notePlaceholder: 'Vid hissen',
  tariff: 'Taxa',
  tariffNone: 'Ingen',
  tariffHourly: 'Per timme',
  tariffFlat: 'Fast',
  tariffTiered: 'Steg',
  untilDuration: 'Tid',
  unitMinShort: 'min',
  unitHourShort: 'tim',
  unitToggle: 'Byt enhet',
  totalSoFar: 'Att betala',
  addTier: 'Lägg till steg',
  cumulativeHint: 'Ange totalsumman du betalar om du åker inom den tiden, inte tillägget.',
  scanPro: 'Skyltskanning ingår i Pro',
  osmAttribution: 'Parkeringsdata © OpenStreetMap-bidragsgivare',
  scheduleWeekday: 'Vardagstaxa används',
  scheduleWeekend: 'Helgtaxa används',
  scheduleDay: 'Dagtaxa används',
  scheduleNight: 'Nattaxa används',
  scheduleChanged: 'Taxan har ändrats — skylten prissätter den här tiden annorlunda. Skanna om eller ändra taxan.',
  scanBoard: 'Skanna skylten',
  scanning: 'Läser skylten',
  scanNotDetected: 'Kunde inte läsa skylten — gå närmare, undvik reflexer eller skriv in den',
  scanPartial: 'Vissa rader kunde inte läsas — kontrollera stegen nedan',
  scanFailed: 'Skanningen misslyckades — skriv in taxan',
  scanUnavailable: 'Skanning kräver den fullständiga appversionen',
  amountPerHour: 'Belopp per timme',
  flatAmount: 'Totalbelopp',
  endQuestion: 'Avsluta parkeringen?',
  savedWord: 'SPARAT',
  parkedWord: 'PARKERAD',
  duration: 'Tid',
  paid: 'Betalt',
  avoided: 'Sparat',
  costNow: 'Kostnad nu',
  locating: 'Söker plats',
  use: 'Använd',
  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: 'Du är nära — titta dig omkring',
  walkToCar: 'Gå i pilens riktning',
  indoorHint: 'Svag signal här — använd fotot och planen du sparade.',
  noSpotDetails: 'Inget foto och ingen plan sparad för den här platsen.',
  photo: 'Foto',
  addPhoto: 'Lägg till foto',
  retakePhoto: 'Ta om',
  removePhoto: 'Ta bort',
  parkedWhen: 'Jag parkerade',
  justNow: 'Nyss',
  minutesAgo: 'för {minutes} min sedan',
  custom: 'Eget',
  customMinutes: 'Minuter',
  notParkedYet: 'Parkerade du inte här? Ta bort posten',
  remindMe: 'Påminn mig',
  reminderAnchor: 'Räkna från',
  anchorAfterPark: 'Efter parkering',
  anchorFirstTier: 'Före första prishöjningen',
  anchorEveryTier: 'Före varje prishöjning',
  reminderAfterHow: 'Hur länge efter',
  reminderBeforeHow: 'Hur länge före',
  reminderKind: 'Hur du påminns',
  kindNotification: 'Notis',
  kindAlarm: 'Ljud',
  kindBoth: 'Båda',
  kindHint: 'Ljud tränger igenom Fokus. Ett riktigt larm som ringer i tyst läge kräver iOS 26.',
  reminderNeedsTariff: 'Det här kräver en taxa — lägg till en först',
  reminderOff: 'Av',
  hoursShort: '{hours} tim',
  simpleReminder: 'Du har stått parkerad i {duration}.',
  // Durum satırları (§5.11)
  offlineTimer: 'Offline — tiden räknas ändå',
  weakGpsNudge: 'Svag signal — lägg till foto eller plan',
  locationOff: 'Platstjänster av · Slå på',
  notificationsOff: 'Notiser av · Slå på i Inställningar',
  cameraOff: 'Kamera av · Slå på i Inställningar',
  // Boş durumlar (§5.12)
  noSessions: 'Inga parkeringar än.',
  firstParkHere: 'Din första parkering hamnar här.',
  noActiveSession: 'Ingen aktiv parkering',
  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'PRO SER NÄR DU PARKERAR',
  proBody: 'Du behöver aldrig tänka på det.',
  proFeatureAuto: 'Frågar om tiden ska starta när CarPlay kopplas ur',
  proFeatureScan: 'Skanna taxeskyltar med kameran',
  autoRenewNotice: 'Prenumerationen förnyas automatiskt tills du säger upp den. Ditt Apple-ID debiteras vid köpet och vid varje förnyelse. Hantera eller säg upp i Inställningar.',
  proFeatureFind: 'Kompass och AR som leder tillbaka till bilen',
  proFeatureFilter: 'Filtrera parkering på laddare, tak och avstånd',
  planPerMonth: '{price} / mån',
  planSave: 'SPARA {percent} %',
  terms: 'Villkor (EULA)',
  planYearly: 'Per år',
  planMonthly: 'Per månad',
  planLifetime: 'Livstid',
  continueYearly: 'Fortsätt — {price}/år',
  continueMonthly: 'Fortsätt — {price}/mån',
  continueLifetime: 'Fortsätt — {price} en gång',
  freeThen: '{intro}, sedan {price}',
  demoPlans: 'Demopriser — bara i utvecklingsbygget.',
  plansError: 'Kunde inte hämta planerna. Kontrollera anslutningen.',
  retry: 'Försök igen',
  restore: 'Återställ köp',
  privacy: 'Integritet',
  restored: 'Återställt.',
  noPurchases: 'Inga köp hittades.',
  purchaseFailed: 'Köpet gick inte igenom.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: 'Aktiv',
  // Ayarlar (§7.9)
  updateRequiredTitle: 'UPPDATERING KRÄVS',
  updateRequiredBody: 'Den här versionen kan inte längre räkna ut dina parkeringskostnader rätt. Uppdatera för att fortsätta.',
  updateNow: 'Uppdatera',
  settings: 'Inställningar',
  appearance: 'Utseende',
  themeLight: 'Ljust',
  themeDark: 'Mörkt',
  themeSystem: 'System',
  language: 'Språk',
  currency: 'Valuta',
  alertThreshold: 'Varna före',
  minutesShort: '{minutes} min',
  autoDetect: 'Automatisk registrering',
  autoDetectHint: 'Sparar platsen när bilens Bluetooth eller CarPlay kopplas ur.',
  autoDetectPro: 'Automatisk registrering ingår i Pro',
  autoParkedAsk: 'Parkerade du nyss? Tryck för att starta tiden här.',
  autoParkedNotice: 'Parkeringsplatsen är sparad. Ska tiden starta?',
  permissions: 'Behörigheter',
  locationGranted: 'Platstjänster på',
  notificationsGranted: 'Notiser på',
  data: 'Data',
  deleteAllData: 'Radera alla parkeringar',
  deleteAllConfirm: 'Radera alla parkeringar? Det går inte att ångra.',
  delete: 'Radera',
  cancel: 'Avbryt',
  developer: 'Utvecklare',
  devPremium: 'Premium aktiverat',
  devPremiumHint: 'Bara i utvecklingsbygget. Stäng av för att se paywall och låsta lägen.',
  devResetOnboarding: 'Visa introduktionen igen',
  manageSubscription: 'Hantera prenumeration',
  exportData: 'Exportera mina data',
  support: 'Support',
  rateAskTitle: 'FUNGERAR PARKIQ FÖR DIG?',
  rateAskBody: 'Ett betyg hjälper andra bilister att hitta appen. Är något fel, säg till oss i stället.',
  rateYes: 'Ja, ge betyg',
  rateNo: 'Inte riktigt',
  later: 'Senare',
  goProUpsell: 'Skanna skyltar, hitta tillbaka, filtrera parkering',
  rateUs: 'Betygsätt ParkIQ',
  about: 'Om',
  version: 'Version',
  // Geçmiş (§7.8)
  lockedSessions: '{count} parkeringar till i Pro',
  history: 'Historik',
  shareMonth: 'Dela månaden',
  monthlySaved: 'Sparat per månad',
  totalSaved: 'Sparat',
  sessionsCount: 'Parkeringar',
  avgDuration: 'Snittid',
  sessionDetail: 'Parkering',
  openInMaps: 'Öppna i Kartor',
  fixLocation: 'Justera parkeringsplatsen',
  purchaseDoneTitle: 'Du har Pro.',
  purchaseDoneBody: 'Skyltskanning, kompass och AR, automatisk registrering och parkeringsfilter är nu på.',
  restoredTitle: 'Återställt.',
  restoredBody: 'Din Pro-åtkomst är tillbaka på den här iPhonen.',
  noPurchasesBody: 'Inget att återställa på det här Apple Account. Betalade du med ett annat, logga in med det och försök igen.',
  restoring: 'Återställer…',
  introFree: '{period} gratis',
  introDiscounted: '{period} för {price}',
  periodDay: '{count} dag',
  periodWeek: '{count} vecka',
  periodMonth: '{count} månad',
  periodYear: '{count} år',
  lifetimeNote: 'En betalning, ingen prenumeration',
  savedSoFar: 'ParkIQ har sparat {amount} åt dig hittills',
  dailyMax: 'Dygnsmax (valfritt)',
  beyondSchedule: 'Bortom det skylten täcker — beloppet är inte längre säkert',
  clockFormat: 'Tidsformat',
  clock12: '1:04 PM',
  clock24: '13:04',
  units: 'Avstånd',
  unitsMetric: 'Meter',
  unitsImperial: 'Fot och miles',
  followDevice: 'Följ enheten',
  headingUnavailable: 'Ingen kompassriktning — avståndet stämmer ändå',
  calibrateCompass: 'Kompassen är fel — rita en åtta med telefonen',
  poiError: 'Kunde inte hämta parkeringar i närheten — kontrollera anslutningen',
  locationMissing: 'Kunde inte hämta någon plats — markera den på kartan',
  locationRough: 'Sparat med ±{meters} noggrannhet — justera på kartan',
  deleteSessionTitle: 'Radera den här parkeringen?',
  deleteSessionBody: 'Posten och fotot tas bort. Det går inte att ångra.',
  compassLocked: 'Kompass och AR ingår i Pro. Platsen, fotot och anteckningen är gratis.',
  back: 'Tillbaka',
  today: 'I dag',
  yesterday: 'I går',
  stillParkedShort: 'Står bilen kvar? Parkeringen började i går.',
};
