// TR karşılıklar. Damga çevirileri design.md §3.3 whitelist'inden:
// "PARK ETTİN." / "₺X CEBİNDE." — birebir çeviri değil, aynı duygu.
import type { CopyKey } from './en';
export const tr: Record<CopyKey, string> = {
  onbTitle1: 'PARK ET',
  onbBody1: 'Tek dokunuş arabayı bıraktığın yeri işaretler. Kat, fotoğraf ve not isteğe bağlı — yalnız otopark karışıksa doldur.',
  onbTitle2: 'TASARRUF ET',
  onbBody2: 'Tarifeyi bir kez gir, ParkIQ bir sonraki fiyat kademesine kalan süreyi saysın. Kademe atlamadan çıkarsan aradaki fark cebinde kalır.',
  onbTitle3: 'BUL',
  onbBody3: 'Pusula ve harita seni arabaya geri götürür. GPS’in çalışmadığı kapalı otoparkta kaydettiğin fotoğraf ve kat devreye girer.',
  skip: 'Atla',
  enableLocation: 'Devam Et',
  notNow: 'Şimdi değil',
  iParked: 'Park Ettim',
  foundIt: 'Buldum',
  arMode: 'Kamera görünümü',
  arHint: 'Işını takip et',
  arInitializing: 'Takip için telefonu yavaşça gezdir',
  arFailed: 'Kamera takibi başarısız — pusulayı kullan',
  findMyCar: 'Arabamı Bul',
  shareLocation: 'Konumu Paylaş',
  endSession: 'Bitir',
  done: 'Tamam',
  keep: 'Devam',
  undo: 'Geri Al',
  shareCard: 'Kartı Paylaş',
  whereTo: 'Nereye?',
  noNearbyForFilter: 'Bu filtreye uyan yakın yer yok',
  filters: 'Filtreler',
  searchRadius: 'Mesafe',
  results: '{count} yakın yer',
  filterAll: 'Tümü',
  filterCharging: 'Şarj',
  filterCovered: 'Kapalı',
  myLocation: 'Konumum',
  noResults: 'Sonuç bulunamadı.',
  photoAdded: 'Eklendi',
  close: 'Kapat',
  noTariffYet: 'Bu yer için kayıtlı tarife yok',
  editTariff: 'Tarifeyi düzenle',
  preferences: 'Tercihler',
  laParked: 'PARK EDİLDİ',
  laNextTier: 'SONRAKİ DİLİM {price}',
  laNowNext: 'Şimdi {now} · Sonra {next}',
  wNoSession: 'Aktif oturum yok',
  wSavedLabel: 'BU AY TASARRUF',
  wParkTitle: 'Park Et',
  wParkHint: 'Yerini tek dokunuşla kaydet',
  poiParking: 'Otopark',
  poiCharging: 'Şarj noktası',
  directions: 'Yol tarifi',
  minWalk: '{minutes} dk yürüme',
  shareMessage: 'Araba burada.',
  parkedStamp: 'PARK ETTİN.',
  parkedAt: '{time} itibarıyla parkta',
  savedStamp: '{amount} CEBİNDE.',
  parkedDurationStamp: '{duration} PARK.',
  stillParked: 'Hâlâ {place} konumunda mısın?',
  addTariff: 'Maliyeti görmek için tarife ekle',
  exitWithinPay: '{minutes} dk içinde çık, {next} yerine {now} öde',
  exitNowPay: 'Şimdi çık, {next} yerine {now} öde',
  nowNext: 'Şimdi {now} · Sonra {next}',
  nextTier: 'Sonraki dilim',
  tierAlert: '{minutes} dk sonra {tier}. dilim. Şimdi {now}, sonra {next}.',
  flatRate: 'Sabit {amount}',
  perHour: '{amount} / saat',
  lastTimeTariff: 'Geçen seferki: {summary} — kullan?',
  detailsOptional: 'Detaylar opsiyonel',
  pickOnMap: 'Haritada seç',
  pickOnMapHint: 'Haritayı kaydır, pini arabanın üstüne getir',
  pickAreaHint: 'Nerede aranacağını haritayı kaydırarak seç',
  useThisArea: 'Burada ara',
  pickArea: 'Haritadan seç',
  usePin: 'Burayı kullan',
  parkLocation: 'Konum',
  useMyLocation: 'Şu anki konumumu kullan',
  floor: 'Kat',
  floorPlaceholder: '-2. kat, C blok',
  note: 'Not',
  notePlaceholder: 'Asansörün yanında',
  tariff: 'Tarife',
  tariffNone: 'Yok',
  tariffHourly: 'Saatlik',
  tariffFlat: 'Sabit',
  tariffTiered: 'Dilimli',
  untilDuration: 'Süre',
  unitMinShort: 'dk',
  unitHourShort: 'sa',
  unitToggle: 'Birimi değiştir',
  totalSoFar: 'Ödenecek toplam',
  addTier: 'Dilim ekle',
  cumulativeHint: 'O süre içinde çıkarsan ödeyeceğin TOPLAMI gir, ek tutarı değil.',
  scanPro: 'Pano tarama Pro’da',
  osmAttribution: 'Otopark verisi © OpenStreetMap katkıcıları',
  scheduleWeekday: 'Hafta içi tarifesi alındı',
  scheduleWeekend: 'Hafta sonu tarifesi alındı',
  scheduleDay: 'Gündüz tarifesi alındı',
  scheduleNight: 'Gece tarifesi alındı',
  scheduleChanged: 'Tarife değişti — bu pano şu an farklı fiyatlandırıyor. Yeniden tara ya da tarifeyi düzenle.',
  scanBoard: 'Panoyu tara',
  scanning: 'Pano okunuyor',
  scanNotDetected: 'Pano okunamadı — yaklaş, parlamayı önle ya da elle gir',
  scanPartial: 'Bazı satırlar okunamadı — aşağıdaki dilimleri kontrol et',
  scanFailed: 'Tarama başarısız — elle gir',
  scanUnavailable: 'Tarama tam uygulama sürümünde çalışır',
  amountPerHour: 'Saat başı tutar',
  flatAmount: 'Toplam tutar',
  endQuestion: 'Oturum bitirilsin mi?',
  savedWord: 'CEBİNDE',
  parkedWord: 'PARK',
  duration: 'Süre',
  paid: 'Ödenen',
  avoided: 'Tasarruf',
  costNow: 'Şu anki maliyet',
  locating: 'Konum bulunuyor',
  use: 'Kullan',
  youAreClose: 'Yaklaştın — etrafına bak',
  walkToCar: 'Okun gösterdiği yöne yürü',
  indoorHint: 'Burada sinyal zayıf — fotoğrafı ve kat notunu kullan.',
  noSpotDetails: 'Bu park için fotoğraf veya kat notu yok.',
  photo: 'Fotoğraf',
  addPhoto: 'Fotoğraf ekle',
  retakePhoto: 'Yeniden çek',
  removePhoto: 'Kaldır',
  parkedWhen: 'Park ettim',
  justNow: 'Az önce',
  minutesAgo: '{minutes} dk önce',
  custom: 'Özel',
  customMinutes: 'Dakika',
  notParkedYet: 'Burada park etmedin mi? Kaydı sil',
  remindMe: 'Hatırlat',
  reminderOff: 'Kapalı',
  hoursShort: '{hours} sa',
  simpleReminder: '{duration} süredir parktasın.',
  offlineTimer: 'Çevrimdışı — sayaç çalışmaya devam ediyor',
  weakGpsNudge: 'Sinyal zayıf — fotoğraf veya kat notu ekle',
  locationOff: 'Konum kapalı · Aç',
  notificationsOff: 'Bildirimler kapalı · Ayarlar’dan aç',
  cameraOff: 'Kamera kapalı · Ayarlar’dan aç',
  noSessions: 'Henüz park yok.',
  firstParkHere: 'İlk parkın buraya düşecek.',
  noActiveSession: 'Aktif oturum yok',
  proHeadline: 'PRO PARKI KENDİ ANLAR',
  proBody: 'Sen hiç düşünmezsin.',
  proFeatureAuto: 'CarPlay kesilince sayacı başlatmayı sorar',
  proFeatureScan: 'Tarife panolarını kamerayla tara',
  autoRenewNotice: 'Abonelik iptal edilene dek kendini yeniler. Ücret onayda ve her yenilemede Apple kimliğinden tahsil edilir. Ayarlar’dan yönetebilir veya iptal edebilirsin.',
  proFeatureFind: 'Arabaya pusula ve AR ile geri dönüş',
  proFeatureFilter: 'Otoparkı şarj, kapalılık ve mesafeye göre filtrele',
  planPerMonth: 'ayda {price}',
  planSave: '%{percent} TASARRUF',
  terms: 'Şartlar (EULA)',
  planYearly: 'Yıllık',
  planMonthly: 'Aylık',
  planLifetime: 'Ömür boyu',
  continueYearly: 'Devam — {price}/yıl',
  continueMonthly: 'Devam — {price}/ay',
  continueLifetime: 'Devam — tek seferlik {price}',
  freeThen: '{intro}, sonra {price}',
  demoPlans: 'Örnek fiyatlar — yalnız geliştirme derlemesi.',
  plansError: 'Planlar yüklenemedi. Bağlantını kontrol et.',
  retry: 'Tekrar dene',
  restore: 'Satın alımları geri yükle',
  privacy: 'Gizlilik',
  restored: 'Geri yüklendi.',
  noPurchases: 'Satın alım bulunamadı.',
  purchaseFailed: 'Satın alma tamamlanamadı.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: 'Etkin',
  updateRequiredTitle: 'GÜNCELLEME GEREKLİ',
  updateRequiredBody: 'Bu sürüm park tutarlarını doğru hesaplayamıyor. Devam etmek için güncelle.',
  updateNow: 'Güncelle',
  settings: 'Ayarlar',
  appearance: 'Görünüm',
  themeLight: 'Açık',
  themeDark: 'Koyu',
  themeSystem: 'Sistem',
  language: 'Dil',
  currency: 'Para birimi',
  alertThreshold: 'Şu kadar önce uyar',
  minutesShort: '{minutes} dk',
  autoDetect: 'Oto-algılama',
  autoDetectHint: 'Aracının Bluetooth’u veya CarPlay bağlantısı kopunca konumu kaydeder.',
  autoDetectPro: 'Oto-algılama Pro’da',
  autoParkedAsk: 'Park mı ettin? Sayacı burada başlatmak için dokun.',
  autoParkedNotice: 'Park konumun kaydedildi. Sayaç başlasın mı?',
  permissions: 'İzinler',
  locationGranted: 'Konum açık',
  notificationsGranted: 'Bildirimler açık',
  data: 'Veri',
  deleteAllData: 'Tüm oturumları sil',
  deleteAllConfirm: 'Tüm oturumlar silinsin mi? Bu geri alınamaz.',
  delete: 'Sil',
  cancel: 'Vazgeç',
  developer: 'Geliştirici',
  devPremium: 'Premium açık',
  devPremiumHint: 'Yalnız geliştirme derlemesinde. Kapatınca paywall ve kilitli haller görünür.',
  devResetOnboarding: 'Onboarding’i tekrar göster',
  manageSubscription: 'Aboneliği yönet',
  exportData: 'Verilerimi dışa aktar',
  support: 'Destek',
  rateAskTitle: 'PARKIQ İŞİNİ GÖRÜYOR MU?',
  rateAskBody: 'Puan vermen başka sürücülerin bulmasını sağlar. Bir sorun varsa bize yaz.',
  rateYes: 'Evet, puan ver',
  rateNo: 'Pek değil',
  later: 'Sonra',
  goProUpsell: 'Pano tara, arabana yönlendirilsin, otoparkı filtrele',
  rateUs: 'ParkIQ’yu değerlendir',
  about: 'Hakkında',
  version: 'Sürüm',
  lockedSessions: 'Pro’da {count} kayıt daha',
  history: 'Geçmiş',
  shareMonth: 'Bu ayı paylaş',
  monthlySaved: 'Aylık tasarruf',
  totalSaved: 'Tasarruf',
  sessionsCount: 'Park',
  avgDuration: 'Ortalama',
  sessionDetail: 'Oturum',
  fixLocation: 'Park konumunu düzelt',
  clockFormat: 'Saat biçimi',
  clock12: '1:04 PM',
  clock24: '13:04',
  units: 'Mesafe',
  unitsMetric: 'Metre',
  unitsImperial: 'Fit ve mil',
  followDevice: 'Cihazı izle',
  headingUnavailable: 'Pusula yönü yok — mesafe yine de doğru',
  calibrateCompass: 'Pusula kalibre değil — telefonu 8 çizerek salla',
  poiError: 'Yakındaki otoparklar alınamadı — bağlantını kontrol et',
  locationMissing: 'Konum alınamadı — haritadan işaretle',
  locationRough: '±{{meters}} doğrulukla kaydedildi — haritadan düzelt',
  deleteSessionTitle: 'Bu park kaydı silinsin mi?',
  deleteSessionBody: 'Kayıt ve fotoğrafı silinir. Geri alınamaz.',
  compassLocked: 'Pusula ve AR Pro’da. Konumun, fotoğrafın ve notun ücretsiz kalır.',
  openInMaps: 'Haritada aç',
  back: 'Geri',
  today: 'Bugün',
  yesterday: 'Dün',
  stillParkedShort: 'Hâlâ parkta mısın? Bu oturum dünden beri açık.',
};
