// TR karşılıklar. Damga çevirileri design.md §3.3 whitelist'inden:
// "PARK ETTİN." / "₺X CEBİNDE." — birebir çeviri değil, aynı duygu.
import type { CopyKey } from './en';

export const tr: Record<CopyKey, string> = {
  onbTitle1: 'PARK ET',
  onbBody1: 'Tek dokunuş arabayı bıraktığın yeri işaretler. Kat, fotoğraf ve not isteğe bağlı — yalnız otopark karışıksa doldur.',
  onbTitle2: 'TASARRUF ET',
  onbBody2: 'Tarifeyi bir kez gir, ParkIQ bir sonraki fiyat kademesine kalan süreyi saysın. Kademe atlamadan çıkarsan aradaki fark cebinde kalır.',
  onbTitle3: 'BUL',
  onbBody3: 'Pusula ve harita seni arabaya geri götürür. GPS’in çalışmadığı kapalı otoparkta kaydettiğin fotoğraf ve kat devreye girer.',
  skip: 'Atla',
  enableLocation: 'Devam Et',
  notNow: 'Şimdi değil',

  iParked: 'Park Ettim',
  findMyCar: 'Arabamı Bul',
  shareLocation: 'Konumu Paylaş',
  endSession: 'Bitir',
  done: 'Tamam',
  keep: 'Devam',
  undo: 'Geri Al',
  shareCard: 'Kartı Paylaş',

  whereTo: 'Nereye?',
  filterAll: 'Tümü',
  filterCharging: 'Şarj',
  filterCovered: 'Kapalı',
  myLocation: 'Konumum',
  noResults: 'Sonuç bulunamadı.',
  poiParking: 'Otopark',
  poiCharging: 'Şarj noktası',
  directions: 'Yol tarifi',
  minWalk: '{minutes} dk yürüme',

  shareMessage: 'Araba burada.',
  parkedStamp: 'PARK ETTİN.',
  parkedAt: '{time} itibarıyla parkta',
  savedStamp: '{amount} CEBİNDE.',
  parkedDurationStamp: '{duration} PARK.',
  stillParked: 'Hâlâ {place} konumunda mısın?',
  addTariff: 'Maliyeti görmek için tarife ekle',

  exitWithinPay: '{minutes} dk içinde çık, {next} yerine {now} öde',
  exitNowPay: 'Şimdi çık, {next} yerine {now} öde',
  nowNext: 'Şimdi {now} · Sonra {next}',
  nextTier: 'Sonraki dilim',
  tierAlert: '{minutes} dk sonra {tier}. dilim. Şimdi {now}, sonra {next}.',
  flatRate: 'Sabit {amount}',
  perHour: '{amount} / saat',
  lastTimeTariff: 'Geçen seferki: {summary} — kullan?',

  detailsOptional: 'Detaylar opsiyonel',
  floor: 'Kat',
  floorPlaceholder: '-2. kat, C blok',
  note: 'Not',
  notePlaceholder: 'Asansörün yanında',
  tariff: 'Tarife',
  tariffNone: 'Yok',
  tariffHourly: 'Saatlik',
  tariffFlat: 'Sabit',
  tariffTiered: 'Dilimli',
  untilHours: 'Kaç saate kadar',
  totalSoFar: 'Ödenecek toplam',
  addTier: 'Dilim ekle',
  cumulativeHint: 'O süre içinde çıkarsan ödeyeceğin TOPLAMI gir, ek tutarı değil.',
  scanPro: 'Pano tarama Pro’da',
  findParkingPro: 'Yakındaki otopark ve şarj Pro’da',
  osmAttribution: 'Otopark verisi © OpenStreetMap katkıcıları',
  scanBoard: 'Panoyu tara',
  scanning: 'Pano okunuyor',
  scanNotDetected: 'Pano okunamadı — elle gir',
  scanFailed: 'Tarama başarısız — elle gir',
  scanUnavailable: 'Tarama tam uygulama sürümünde çalışır',
  amountPerHour: 'Saat başı tutar',
  flatAmount: 'Toplam tutar',
  endQuestion: 'Oturum bitirilsin mi?',
  savedWord: 'CEBİNDE',
  parkedWord: 'PARK',
  duration: 'Süre',
  paid: 'Ödenen',
  avoided: 'Tasarruf',
  costNow: 'Şu anki maliyet',

  locating: 'Konum bulunuyor',
  use: 'Kullan',

  youAreClose: 'Yaklaştın — etrafına bak',
  walkToCar: 'Okun gösterdiği yöne yürü',
  indoorHint: 'Burada sinyal zayıf — fotoğrafı ve kat notunu kullan.',
  noSpotDetails: 'Bu park için fotoğraf veya kat notu yok.',
  photo: 'Fotoğraf',
  addPhoto: 'Fotoğraf ekle',
  retakePhoto: 'Yeniden çek',
  removePhoto: 'Kaldır',
  parkedWhen: 'Park ettim',
  justNow: 'Az önce',
  minutesAgo: '{minutes} dk önce',
  custom: 'Özel',
  customMinutes: 'Dakika',
  notParkedYet: 'Burada park etmedin mi? Kaydı sil',
  remindMe: 'Hatırlat',
  reminderOff: 'Kapalı',
  hoursShort: '{hours} sa',
  simpleReminder: '{duration} süredir parktasın.',

  offlineTimer: 'Çevrimdışı — sayaç çalışmaya devam ediyor',
  weakGpsNudge: 'Sinyal zayıf — fotoğraf veya kat notu ekle',
  locationOff: 'Konum kapalı · Aç',
  notificationsOff: 'Bildirimler kapalı · Ayarlar’dan aç',
  cameraOff: 'Kamera kapalı · Ayarlar’dan aç',

  noSessions: 'Henüz park yok.',
  firstParkHere: 'İlk parkın buraya düşecek.',
  noActiveSession: 'Aktif oturum yok',

  proOverline: 'PARKIQ PRO',
  proHeadline: 'PRO PARKI KENDİ ANLAR',
  proBody: 'Sen hiç düşünmezsin.',
  proFeatureAuto: 'Arabadan inince otomatik kayıt',
  proFeatureScan: 'Tarife panolarını kamerayla tara',
  proFeatureFind: 'Yakındaki otopark ve şarj noktalarını bul',
  autoRenewNotice: 'Abonelik iptal edilene dek kendini yeniler. Ücret onayda ve her yenilemede Apple kimliğinden tahsil edilir. Ayarlar’dan yönetebilir veya iptal edebilirsin.',
  proFeatureHistory: 'Sınırsız geçmiş ve istatistik',
  proFeatureVehicles: 'Birden fazla araç',
  planYearly: 'Yıllık',
  planMonthly: 'Aylık',
  planLifetime: 'Ömür boyu',
  continueYearly: 'Devam — {price}/yıl',
  continueMonthly: 'Devam — {price}/ay',
  continueLifetime: 'Devam — tek seferlik {price}',
  freeThen: '{intro}, sonra {price}',
  demoPlans: 'Örnek fiyatlar — yalnız geliştirme derlemesi.',
  plansError: 'Planlar yüklenemedi. Bağlantını kontrol et.',
  retry: 'Tekrar dene',
  restore: 'Satın alımları geri yükle',
  terms: 'Şartlar',
  privacy: 'Gizlilik',
  restored: 'Geri yüklendi.',
  noPurchases: 'Satın alım bulunamadı.',
  purchaseFailed: 'Satın alma tamamlanamadı.',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: 'Etkin',

  settings: 'Ayarlar',
  appearance: 'Görünüm',
  themeLight: 'Açık',
  themeDark: 'Koyu',
  themeSystem: 'Sistem',
  language: 'Dil',
  currency: 'Para birimi',
  alertThreshold: 'Şu kadar önce uyar',
  minutesShort: '{minutes} dk',
  autoDetect: 'Oto-algılama',
  autoDetectHint: 'Aracının Bluetooth’u veya CarPlay bağlantısı kopunca konumu kaydeder.',
  autoDetectPro: 'Oto-algılama Pro’da',
  autoParkedNotice: 'Park konumun kaydedildi. Sayaç başlasın mı?',
  vehicles: 'Araçlar',
  vehicleNamePlaceholder: 'Araç ekle',
  multiVehiclePro: 'Birden fazla araç Pro’da',
  permissions: 'İzinler',
  locationGranted: 'Konum açık',
  notificationsGranted: 'Bildirimler açık',
  data: 'Veri',
  deleteAllData: 'Tüm oturumları sil',
  deleteAllConfirm: 'Tüm oturumlar silinsin mi? Bu geri alınamaz.',
  delete: 'Sil',
  cancel: 'Vazgeç',
  developer: 'Geliştirici',
  devPremium: 'Premium açık',
  devPremiumHint: 'Yalnız geliştirme derlemesinde. Kapatınca paywall ve kilitli haller görünür.',
  devResetOnboarding: 'Onboarding’i tekrar göster',
  manageSubscription: 'Aboneliği yönet',
  exportData: 'Verilerimi dışa aktar',
  support: 'Destek',
  rateUs: 'ParkIQ’yu değerlendir',
  about: 'Hakkında',
  version: 'Sürüm',

  lockedSessions: 'Pro’da {count} kayıt daha',
  history: 'Geçmiş',
  shareMonth: 'Bu ayı paylaş',
  monthlySaved: 'Aylık tasarruf',
  totalSaved: 'Tasarruf',
  sessionsCount: 'Park',
  avgDuration: 'Ortalama',
  sessionDetail: 'Oturum',
  openInMaps: 'Haritada aç',
  back: 'Geri',
  today: 'Bugün',
  yesterday: 'Dün',
  stillParkedShort: 'Hâlâ parkta mısın? Bu oturum dünden beri açık.',
};
