export const tr = {
  auth: {
    login: "Giriş Yap",
    register: "Kayıt Ol",
    email: "E-posta",
    password: "Şifre",
    loginButton: "Giriş Yap",
    registerButton: "Kayıt Ol",
    appleLogin: "Apple ile Devam Et",
    googleLogin: "Google ile Devam Et",
    facebookLogin: "Facebook ile Devam Et",
    backToLogin: "Girişe Dön",
    noAccount: "Hesabınız yok mu?",
    hasAccount: "Zaten hesabınız var mı?",
    forgotPassword: "Şifremi Unuttum",
    resetPassword: "Şifre Sıfırla",
    sendResetLink: "Sıfırlama Linki Gönder",
    firstName: "Ad",
    lastName: "Soyad",
    phone: "Telefon Numarası",
    bloodType: "Kan Grubu",
    licensePlate: "Plaka",
    confirmPassword: "Şifre Tekrar",
    passwordsDoNotMatch: "Şifreler eşleşmiyor",
    passwordTooShort: "Şifre en az 6 karakter olmalıdır",
    emailRequired: "Lütfen e-posta adresinizi girin",
    passwordRequired: "Lütfen şifrenizi girin",
    firstNameRequired: "Lütfen adınızı girin",
    lastNameRequired: "Lütfen soyadınızı girin",
    phoneRequired: "Lütfen telefon numaranızı girin",
    bloodTypeRequired: "Lütfen kan grubunuzu seçin",
    licensePlateRequired: "Lütfen plakanızı girin",
    resetLinkSent: "Şifre sıfırlama linki e-posta adresinize gönderildi",
    enterEmailForReset: "Şifre sıfırlama linki almak için e-posta adresinizi girin",
    loginSubtitle: "Hoş geldiniz! Devam etmek için lütfen giriş yapın.",
    registerSubtitle: "Başlamak için hesabınızı oluşturun",
    optional: "Opsiyonel",
    emailConfirmationRequired: "E-posta onayı gerekli",
    emailConfirmationMessage: "Kayıt başarılı! Lütfen e-posta adresinize gelen onay linkine tıklayın. E-posta onaylandıktan sonra giriş yapabilirsiniz.",
    emailConfirmationProfileMessage: "Kayıt başarılı! Lütfen e-posta adresinize gelen onay linkine tıklayın. E-posta onaylandıktan sonra profil bilgileriniz kaydedilecek.",
    emailNotConfirmed: "Giriş yapmadan önce lütfen e-posta adresinizi onaylayın. E-posta kutunuzda onay linkini kontrol edin.",
    emailNotConfirmedExpoGo: "E-posta adresinizi onaylayın. Email'deki link'e tıklayın, sonra buraya dönüp tekrar login yapmayı deneyin.",
    resendConfirmationEmail: "Onay Mailini Yeniden Gönder",
    confirmationEmailResent: "Onay maili yeniden gönderildi. Lütfen e-posta kutunuzu kontrol edin.",
    confirmationEmailResentExpoGo: "Onay maili gönderildi. Email'inizdeki link'e tıklayın, sonra buraya dönüp login yapın.",
    resendConfirmationEmailError: "Onay maili gönderilirken bir hata oluştu. Lütfen tekrar deneyin.",
    profileNotFound: "Hesap bulunamadı.",
    completeProfile: "Profil Bilgilerini Tamamla",
    completeProfileDescription: "Devam etmek için lütfen profil bilgilerinizi tamamlayın",
    profileIncomplete: "Profil bilgileriniz eksik",
  },
  onboarding: {
    skip: "Atla",
    next: "İleri",
    getStarted: "Başlayalım",
    slide1Title: "Otoparkı Kolayca Bulun",
    slide1Description: "Gerçek zamanlı müsaitlik ve fiyat bilgileriyle yakındaki otopark noktalarını keşfedin.",
    slide2Title: "Parkınızı Takip Edin",
    slide2Description: "Akıllı zamanlayıcılar ve otomatik hatırlatıcılarla park oturumlarınızı izleyin.",
    slide3Title: "Para Tasarrufu Yapın",
    slide3Description: "En iyi otopark fiyatlarını alın ve akıllı bildirimlerle gereksiz ücretlerden kaçının.",
    slide4Title: "Başlayalım",
    slide4Description: "Bugün daha akıllı park etmeye başlayın. Hesabınızı oluşturun ve yolculuğunuza başlayın.",
  },
  map: {
    parkingDetails: "Otopark Detayları",
    distance: "Mesafe",
    priceInfo: "Fiyat Bilgisi",
    noPriceInfo: "Fiyat bilgisi bulunamadı",
    addPriceInfo: "Fiyat bilgisi eklemek ister misiniz?",
    openInMaps: "Apple Maps'te Aç",
    priceTier: "{{duration}} saat: {{price}} {{currency}}",
    priceDisclaimer: "Fiyat bilgileri kullanıcılar tarafından gönderilmiştir, doğruluğuna güvenmeyin.",
    addPriceTitle: "Fiyat Bilgisi Ekle",
    addPriceDescription: "Bu otopark için fiyat bilgisi ekleyin",
    currency: "Para Birimi",
    priceTiers: "Fiyat Tarifesi",
    addTier: "Tarife Ekle",
    tierDuration: "Süre (saat)",
    tierPrice: "Fiyat",
    removeTier: "Kaldır",
    submitPrice: "Fiyatı Gönder",
    priceSubmitted: "Fiyat bilgisi başarıyla gönderildi",
    priceSubmitError: "Fiyat bilgisi gönderilirken bir hata oluştu",
    currencyRequired: "Para birimi seçilmelidir",
    tierRequired: "En az bir fiyat tarifesi eklenmelidir",
    userNotFoundError: "Kullanıcı profili bulunamadı. Lütfen uygulamayı yeniden başlatın veya tekrar giriş yapın.",
    title: "Harita",
    startParking: "Park Etmeyi Başlat",
    noLocation: "Konum mevcut değil",
    nearbyPrices: "Yakındaki Fiyatlar",
    noPrices: "Fiyat bulunamadı",
  },
  parking: {
    title: "Park",
    startParking: "Park Etmeyi Başlat",
    activeParking: "Aktif Park",
    endParking: "Parkı Bitir",
    timer: "Park Süresi",
    noActiveSession: "Aktif park oturumu yok",
    sessionEnded: "Park oturumu sona erdi",
    setupParking: "Park Etmeyi Başlat",
    currentLocation: "Mevcut Konum",
    note: "Not (isteğe bağlı)",
    notePlaceholder: "Bu park oturumu hakkında bir not ekleyin",
    parkedMinutesAgo: "X dakika önce park ettim",
    startTimeAdjustment: "Başlangıç Zamanı Ayarı",
    ago: "önce",
    minutes: "dakika",
    enableReminder: "Hatırlatıcıyı Etkinleştir",
    reminderOffset: "Hatırlatıcı Gecikmesi",
    reminderAfter: "Sonra Hatırlat",
    photo: "Fotoğraf",
    photoPlaceholder: "Fotoğraf özelliği yakında",
    takePhoto: "Fotoğraf Çek",
    confirmParking: "Parkı Onayla",
    reminderTitle: "Park Hatırlatıcısı",
    reminderBody: "Parkınızı kontrol etmeyi unutmayın!",
    editNote: "Notu Düzenle",
    reminderEnabled: "Hatırlatıcı Etkin",
    reminderDisabled: "Hatırlatıcı Devre Dışı",
    summary: "Park Özeti",
    adjustedStartTime: "Ayarlanmış Başlangıç Zamanı",
    location: "Konum",
    reminderStatus: "Hatırlatıcı Durumu",
    summaryTitle: "Park Özeti",
    atTime: "Belirli Saatte",
    afterDuration: "Süre Sonra",
    remindAt: "Şu saatte hatırlat",
  },
  history: {
    title: "Geçmiş",
    noHistory: "Park geçmişi yok",
    startTime: "Başlangıç",
    endTime: "Bitiş",
    duration: "Süre",
    pullToRefresh: "Yenilemek için çekin",
    details: "Park Detayları",
    detailTitle: "Park Detayları",
    delete: "Sil",
    deleteSession: "Oturumu Sil",
    deleteConfirm: "Bu park oturumunu silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    timeDetails: "Zaman Detayları",
    parkingCost: "Park Ücreti",
    total: "Toplam",
  },
  prices: {
    title: "Fiyatlar",
    submitPrice: "Fiyat Gönder",
    placeId: "Yer ID (isteğe bağlı)",
    currency: "Para Birimi",
    priceJson: "Fiyat JSON",
    submit: "Gönder",
  },
  profile: {
    title: "Profil",
    statistics: "İstatistikler",
    totalSessions: "Toplam Oturum",
    totalTime: "Toplam Süre",
    saved: "Tasarruf",
    recentActivity: "Son Aktiviteler",
    noRecentActivity: "Son aktivite yok",
    quickActions: "Hızlı İşlemler",
    rateApp: "Uygulamayı Değerlendir",
    helpSupport: "Yardım ve Destek",
    shareApp: "Uygulamayı Paylaş",
    moneySaved: "Tasarruf Edilen Para",
    noSavings: "Henüz tasarruf hesaplanmadı",
    savingsDescription: "Tasarruflar, bir sonraki fiyatlandırma seviyesinden 15 dakika önce biten oturumlar için hesaplanır",
    actual: "Gerçek",
    wouldBe: "Olacaktı",
    noEmail: "E-posta yok",
    user: "Kullanıcı",
    parkingSession: "Park Oturumu",
    justNow: "Az önce",
    minutesAgo: "{{count}} dakika önce",
    minutesAgo_plural: "{{count}} dakika önce",
    hoursAgo: "{{count}} saat önce",
    hoursAgo_plural: "{{count}} saat önce",
    yesterday: "Dün",
    daysAgo: "{{count}} gün önce",
    daysAgo_plural: "{{count}} gün önce",
    personalInfo: "Kişisel Bilgiler",
  },
  settings: {
    title: "Ayarlar",
    theme: "Tema",
    light: "Açık",
    dark: "Koyu",
    system: "Sistem",
    logout: "Çıkış Yap",
    logoutConfirm: "Çıkış yapmak istediğinizden emin misiniz?",
    reminderOffset: "Hatırlatıcı Gecikmesi",
    currency: "Para Birimi",
    language: "Dil",
    languageEnglish: "English",
    languageTurkish: "Türkçe",
    selectCurrency: "Para Birimi Seç",
    selectLanguage: "Dil Seç",
    deleteAccount: "Hesabı Sil",
    deleteAccountConfirm: "Hesabınızı silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    deleteAccountMock: "Bu bir deneme eylemidir. Hesap silme özelliği yakında geliyor.",
    accountDeleted: "Hesabınız başarıyla silindi.",
    deleteAccountError: "Hesap silinirken bir hata oluştu. Lütfen tekrar deneyin.",
    appearance: "Görünüm",
    reminders: "Hatırlatıcılar",
    notifications: "Bildirimler",
    pushNotifications: "Anlık Bildirimler",
    emailNotifications: "E-posta Bildirimleri",
    enabled: "Etkin",
    dataPrivacy: "Veri ve Gizlilik",
    exportData: "Verileri Dışa Aktar",
    privacyPolicy: "Gizlilik Politikası",
    termsOfService: "Hizmet Şartları",
    about: "Hakkında",
    version: "Sürüm",
    buildNumber: "Yapı Numarası",
    account: "Hesap",
    delete: "Sil",
  },
  common: {
    loading: "Yükleniyor...",
    error: "Hata",
    retry: "Yeniden Dene",
    cancel: "İptal",
    save: "Kaydet",
    done: "Tamam",
    select: "Seç",
    hourShort: "s",
    minuteShort: "d",
    ongoing: "Devam Ediyor",
    today: "Bugün",
    yesterday: "Dün",
    info: "Bilgi",
    ok: "Tamam",
  },
};

