import type { CopyKey } from './en';

// Geleneksel Çince (TW). Hitap "你"; damga noktaları ASCII '.' bırakıldı — DisplayStamp /\.$/ ile kırpıp renkli noktayı kendi basıyor.
export const zhHant: Record<CopyKey, string> = {
  // Aksiyonlar
  // Onboarding (§7.1) — poster başlıkları noktasız saklanır, nokta bileşende renklenir
  onbTitle1: '停車',
  onbBody1: '點一下就記住車停在哪。樓層、照片、備註都是選填 — 停車場太繞的時候再補。',
  onbTitle2: '省錢',
  onbBody2: '費率輸入一次，ParkIQ 就替你倒數到下一個價格級距。跳級前開走，差額就留在你口袋。',
  onbTitle3: '找到車',
  onbBody3: '指南針和地圖帶你走回去。GPS 收不到的地下停車場，就靠你存的照片和樓層。',
  skip: '略過',
  enableLocation: '繼續',
  notNow: '先不要',
  iParked: '我停好了',
  foundIt: '找到了',
  arMode: '相機視角',
  arHint: '沿著光束走',
  arInitializing: '慢慢移動手機開始追蹤',
  arFailed: '相機追蹤失敗 — 改用指南針',
  findMyCar: '找我的車',
  shareLocation: '分享位置',
  endSession: '結束',
  done: '完成',
  keep: '繼續',
  undo: '復原',
  shareCard: '分享卡片',
  // Keşif
  whereTo: '要去哪裡？',
  noNearbyForFilter: '附近沒有符合這個篩選的地點',
  filters: '篩選',
  searchRadius: '範圍',
  results: '附近 {count} 處',
  filterAll: '全部',
  filterCharging: '充電',
  filterCovered: '室內',
  myLocation: '我的位置',
  noResults: '找不到地點。',
  photoAdded: '已加入',
  close: '關閉',
  noTariffYet: '這個地點還沒有存費率',
  editTariff: '編輯費率',
  preferences: '偏好設定',
  laParked: '已停車',
  laNextTier: '下一級距 {price}',
  laNowNext: '現在 {now} · 之後 {next}',
  wNoSession: '沒有進行中的停車',
  wSavedLabel: '本月省下',
  wParkTitle: '停車',
  wParkHint: '點一下記下車位',
  poiParking: '停車場',
  poiCharging: '充電站',
  directions: '路線',
  minWalk: '步行 {minutes} 分',
  // Oturum
  shareMessage: '車在這裡。',
  parkedStamp: '已停車.',
  parkedAt: '{time} 停車',
  savedStamp: '省下 {amount}.',
  parkedDurationStamp: '停了 {duration}.',
  stillParked: '還停在{place}嗎？',
  addTariff: '加入費率才看得到費用',
  // Tarife / para (§5.9–5.10 formülünden)
  exitWithinPay: '{minutes} 分內開走付 {now}，不是 {next}',
  exitNowPay: '現在開走付 {now}，不是 {next}',
  nowNext: '現在 {now} · 之後 {next}',
  nextTier: '下一級距',
  tierAlert: '{minutes} 分後進第 {tier} 級距。現在 {now}，之後 {next}。',
  flatRate: '單一價 {amount}',
  perHour: '{amount} / 小時',
  lastTimeTariff: '上次：{summary} — 要用嗎？',
  // Park sheet'i + tarife formu (§7.3–7.4)
  detailsOptional: '細節都是選填',
  pickOnMap: '在地圖上選',
  pickOnMapHint: '移動地圖，讓圖釘對準你的車',
  pickAreaHint: '移動地圖決定要搜尋的範圍',
  useThisArea: '搜尋這裡',
  pickArea: '從地圖選',
  usePin: '就用這裡',
  parkLocation: '位置',
  useMyLocation: '用我目前的位置',
  floor: '樓層',
  floorPlaceholder: 'B2、C 區',
  note: '備註',
  notePlaceholder: '電梯旁邊',
  tariff: '費率',
  tariffNone: '無',
  tariffHourly: '按小時',
  tariffFlat: '單一價',
  tariffTiered: '級距',
  untilDuration: '時間',
  unitMinShort: '分',
  unitHourShort: '時',
  unitToggle: '切換單位',
  totalSoFar: '應付總額',
  addTier: '新增級距',
  cumulativeHint: '填那段時間內開走要付的總額，不是加價的部分。',
  scanPro: '掃描費率牌是 Pro 功能',
  osmAttribution: '停車資料 © OpenStreetMap 貢獻者',
  scheduleWeekday: '已套用平日費率',
  scheduleWeekend: '已套用假日費率',
  scheduleDay: '已套用日間費率',
  scheduleNight: '已套用夜間費率',
  scheduleChanged: '費率換了 — 這塊牌子在這個時段算法不同。重掃一次或手動改費率。',
  scanBoard: '掃描費率牌',
  scanning: '讀取費率牌',
  scanNotDetected: '讀不到費率牌 — 靠近一點、避開反光，或手動輸入',
  scanPartial: '有幾行讀不到 — 檢查下面的級距',
  scanFailed: '掃描失敗 — 請手動輸入',
  scanUnavailable: '掃描需要完整版 App',
  amountPerHour: '每小時金額',
  flatAmount: '總金額',
  endQuestion: '要結束這次停車嗎？',
  savedWord: '省下',
  parkedWord: '停車',
  duration: '時間',
  paid: '已付',
  avoided: '少付',
  costNow: '目前費用',
  locating: '定位中',
  use: '使用',
  // Foto / backdate / hatırlatıcı (§7.3)
  youAreClose: '快到了 — 看看四周',
  walkToCar: '往箭頭的方向走',
  indoorHint: '這裡訊號弱 — 看照片和樓層備註。',
  noSpotDetails: '這次停車沒有照片或樓層備註。',
  photo: '照片',
  addPhoto: '加入照片',
  retakePhoto: '重拍',
  removePhoto: '移除',
  parkedWhen: '停車時間',
  justNow: '剛剛',
  minutesAgo: '{minutes} 分鐘前',
  custom: '自訂',
  customMinutes: '分鐘',
  notParkedYet: '沒有停在這裡？刪掉這筆紀錄',
  remindMe: '提醒我',
  reminderAnchor: '從哪裡算',
  anchorAfterPark: '停車之後',
  anchorFirstTier: '第一次漲價前',
  anchorEveryTier: '每次漲價前',
  reminderAfterHow: '多久之後',
  reminderBeforeHow: '提前多久',
  reminderKind: '用什麼提醒',
  kindNotification: '通知',
  kindAlarm: '響鈴',
  kindBoth: '兩者',
  kindHint: '響鈴可以穿透專注模式。靜音時也會響的真正鬧鈴需要 iOS 26。',
  reminderNeedsTariff: '這需要費率 — 先加一個',
  reminderOff: '關閉',
  hoursShort: '{hours} 小時',
  simpleReminder: '你已經停了 {duration}。',
  // Durum satırları (§5.11)
  offlineTimer: '離線 — 計時繼續',
  weakGpsNudge: '訊號弱 — 加張照片或樓層備註',
  locationOff: '定位已關 · 開啟',
  notificationsOff: '通知已關 · 到「設定」開啟',
  cameraOff: '相機已關 · 到「設定」開啟',
  // Boş durumlar (§5.12)
  noSessions: '還沒有停車紀錄。',
  firstParkHere: '第一次停車會出現在這裡。',
  noActiveSession: '沒有進行中的停車',
  // Paywall (§7.10) — "unlock/amazing" tipi pazarlama dolgusu yasak (§10)
  proHeadline: 'PRO 自己知道你停了車',
  proBody: '你完全不用想。',
  proFeatureAuto: 'CarPlay 一斷線就問你要不要開始計時',
  proFeatureScan: '用相機掃描費率牌',
  autoRenewNotice: '訂閱在取消前會自動續訂。費用於確認購買時及每次續訂時由你的 Apple ID 扣款。可在「設定」中管理或取消。',
  proFeatureFind: '用指南針和 AR 帶你回到車旁',
  proFeatureFilter: '依充電、室內和距離篩選停車場',
  planPerMonth: '每月 {price}',
  planSave: '省 {percent}%',
  terms: '條款 (EULA)',
  planYearly: '年繳',
  planMonthly: '月繳',
  planLifetime: '買斷',
  continueYearly: '繼續 — {price}/年',
  continueMonthly: '繼續 — {price}/月',
  continueLifetime: '繼續 — {price} 一次付清',
  freeThen: '{intro}，之後 {price}',
  demoPlans: '示範價格 — 僅限開發版本。',
  plansError: '無法載入方案。檢查你的連線。',
  retry: '重試',
  restore: '恢復購買',
  privacy: '隱私權',
  restored: '已恢復。',
  noPurchases: '找不到購買紀錄。',
  purchaseFailed: '購買失敗。',
  proStamp: 'PRO.',
  goPro: 'ParkIQ Pro',
  proActive: '使用中',
  // Ayarlar (§7.9)
  updateRequiredTitle: '需要更新',
  updateRequiredBody: '這個版本已經算不準停車費用。更新後才能繼續。',
  updateNow: '更新',
  settings: '設定',
  appearance: '外觀',
  themeLight: '淺色',
  themeDark: '深色',
  themeSystem: '跟隨系統',
  language: '語言',
  currency: '幣別',
  alertThreshold: '提前多久提醒',
  minutesShort: '{minutes} 分',
  autoDetect: '自動偵測',
  autoDetectHint: '車上的 Bluetooth 或 CarPlay 一斷線就記下車位。',
  autoDetectPro: '自動偵測是 Pro 功能',
  autoParkedAsk: '剛停好車嗎？點一下在這裡開始計時。',
  autoParkedNotice: '車位已經記下。要開始計時嗎？',
  permissions: '權限',
  locationGranted: '定位已開',
  notificationsGranted: '通知已開',
  data: '資料',
  deleteAllData: '刪除所有紀錄',
  deleteAllConfirm: '要刪除所有紀錄嗎？無法復原。',
  delete: '刪除',
  cancel: '取消',
  developer: '開發者',
  devPremium: 'Premium 已開啟',
  devPremiumHint: '僅限開發版本。關掉就會看到付費頁和鎖定狀態。',
  devResetOnboarding: '重看新手導覽',
  manageSubscription: '管理訂閱',
  exportData: '匯出我的資料',
  support: '支援',
  rateAskTitle: 'ParkIQ 好用嗎？',
  rateAskBody: '你的評分能讓其他駕駛找到它。如果哪裡不對，直接告訴我們。',
  rateYes: '好，去評分',
  rateNo: '不太行',
  later: '稍後',
  goProUpsell: '掃費率牌、帶你回到車旁、篩選停車場',
  rateUs: '給 ParkIQ 評分',
  about: '關於',
  version: '版本',
  // Geçmiş (§7.8)
  lockedSessions: 'Pro 還能看 {count} 筆紀錄',
  history: '紀錄',
  shareMonth: '分享這個月',
  monthlySaved: '每月省下',
  totalSaved: '省下',
  sessionsCount: '次數',
  avgDuration: '平均時間',
  sessionDetail: '這次停車',
  openInMaps: '用地圖開啟',
  fixLocation: '修正停車位置',
  purchaseDoneTitle: '你現在是 Pro。',
  purchaseDoneBody: '費率牌掃描、指南針和 AR 導引、自動偵測和停車場篩選都開啟了。',
  restoredTitle: '已恢復。',
  restoredBody: '你的 Pro 權限已經回到這支 iPhone。',
  noPurchasesBody: '這個 Apple Account 沒有可恢復的購買。如果是用另一個帳號付的，請改用那個登入再試一次。',
  restoring: '恢復中…',
  introFree: '{period} 免費',
  introDiscounted: '{period} {price}',
  periodDay: '{count} 天',
  periodWeek: '{count} 週',
  periodMonth: '{count} 個月',
  periodYear: '{count} 年',
  lifetimeNote: '一次付清，不是訂閱',
  savedSoFar: 'ParkIQ 到目前為止幫你省下 {amount}',
  dailyMax: '每日上限（選填）',
  beyondSchedule: '超出費率牌寫的範圍 — 金額已經不確定',
  clockFormat: '時間格式',
  clock12: '下午 1:04',
  clock24: '13:04',
  units: '距離',
  unitsMetric: '公尺',
  unitsImperial: '英尺和英里',
  followDevice: '跟隨裝置',
  headingUnavailable: '沒有指南針方向 — 距離仍然正確',
  calibrateCompass: '指南針不準 — 拿手機畫 8 字',
  poiError: '載入不到附近的停車場 — 檢查你的連線',
  locationMissing: '取不到位置 — 在地圖上標出來',
  locationRough: '以 ±{meters} 的誤差存下 — 在地圖上修正',
  deleteSessionTitle: '要刪除這筆停車紀錄嗎？',
  deleteSessionBody: '紀錄和照片都會刪掉。無法復原。',
  compassLocked: '指南針和 AR 導引是 Pro 功能。車位、照片和備註仍然免費。',
  back: '返回',
  today: '今天',
  yesterday: '昨天',
  stillParkedShort: '還停著嗎？這次停車從昨天開始。',
};
